### ISSUE TITLE
Add highchart to openemr

### ISSUE THREAD

**Issue by A1Gard** [openemr/openemr#1251]
I want to add [highchart](https://www.highcharts.com) to openemr.
I think the best choose for start is vitals page:
`interface/patient_file/encounter/trend_form.php?formname=vitals`

@bradymiller what is the best choose of these [demo](https://www.highcharts.com/demo)? 
And tell me about what we need, that I'll contribute.

Because the flash shockwave chart is not browser friendly.

**Comment by bradymiller** [comment]
hi @A1Gard ,

Check out charting in the development demos (this is OpenEMR 5.0.1 that will likely be released in a couple months), and you will be pleasantly surprised:
http://www.open-emr.org/wiki/index.php/Development_Demo#Main_Demo_.28Ubuntu_16.04.29

Note that w actually had to drop the shockwave chart and go with a new one because of an unfixable security issue in the shockwave chart; and plan to hopefully get this new charting in the next 5.0.0 patch.

-brady

**Comment by sunsetsystems** [comment]
Also, I don't think "free for non-commercial use" licensing will work here and is surely not GPL-compatible.

**Comment by A1Gard** [comment]
@bradymiller Thanks for reply, I see the chart ;)
I think this very simple :)
@sunsetsystems thats right, and the [chartjs](http://www.chartjs.org/)  is  GPL-compatible and this modern and easy to use.

Now Mrs Miller can I any help about more charts in vitals ?

**Comment by bradymiller** [comment]
hi @A1Gard ,

See this issue thread for background (also discussed why we ended up going with dygraphs over chartjs):
https://github.com/openemr/openemr/issues/583

-brady
