### ISSUE TITLE
group_name to group_id upgrade

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#1268]
#1081 brings in group_id in layout_options table.  Is there an upgrade process for changing the existing layout?

After the upgrade, following errors are observed throughout various scripts:

> ERROR: query failed: SELECT * FROM layout_options WHERE form_id = 'DEM' ORDER BY group_id, seq
> 
> Error: Unknown column 'group_id' in 'order clause'

**Comment by mdsupport** [comment]
Another observation : 
While introduction of layout_group_properties is a good thing, deleting an column in core tables will affect several localized changes.  This probably needs some advisory.

**Comment by sunsetsystems** [comment]
PR 1081 that you referenced changes scripts in OpenEMR accordingly, but custom code is always at risk for many types of changes. I don't think it's reasonable to leave group_name in the table because anything referencing it will be broken anyway.

Existing layouts are converted. See the changes to  library/sql_upgrade_fx.php and sql/5_0_0-to-5_0_1_upgrade.sql.

Not sure if that answers your questions?

**Comment by mdsupport** [comment]
Thanks @sunsetsystems.  We were exploring the same direction. Since there were hits related to this column in upgrade sql, the original issue was raised to check if any manual step was missed.

Problem in our case appears that upgrade script depends on non-existence of 'layout_group_properties'.  As this table was not a custom addition, chances are this issue may occur for others as well.

Regarding the deletion of coulmns:
We use major version upgrades to introduce deletions since those upgrades get more attention.  That prompted the observation about advisory.
