### ISSUE TITLE
Critical Bug : New dialog instead of popup 

### ISSUE THREAD

**Issue by sharonco-matrix** [openemr/openemr#1304]
Hi @bradymiller 
I'm not sure to address this issue. There have been amazing improvements in the "pop-ups". The problem is that there are not being tested in the frames UI. So a lot of things are broken now.

The last thing we found is in
Create encounter-> add n issue-> click on codes->-> "no popup"... instead the "coded is under the page
See the 
![openemr 9](https://user-images.githubusercontent.com/17809889/34078369-9a2c3156-e321-11e7-8099-7a78bb2a53f1.png)

Thanks for your quick support and help

**Comment by sjpadgett** [comment]
Hi @sharonco-matrix I'm aware of these issues and am working very hard to finish this but, dialogs have transitioned several times over the life of codebase and are deeply rooted in the window style, making transition to responsive bootstrap a challenge, one I fully intend to overcome :). I have redone amendments, issues, pnotes well, mostly all of demographics and am working on browser compatibility issues. Works great all browser's except IE. I'm close to finish but I keep running up against existing bugs such as encounter delete is broken since before my foray this last go around. Anyway, please bare with me a day or two and this will all be sorted.
Appears the issue above is bootstrap is not loaded although dlgopen should load it. Regardless, it works on version i'm writing now so, hang tight and thanks for your patients...

**Comment by sjpadgett** [comment]
@bradymiller I'm ready to open new PR for dialogs and i'm telling you this is an adventure. I think i've seen every possible way a window/script can be closed or submitted. Some close first, some last and some may take a journey through three scripts. :) Anyway,fairly large commit and was wondering if my git can be setup with a docker that has demo data so you guys can help me finish testing?

**Comment by bradymiller** [comment]
Yep, can do that with the same demo data that is used in the online demos. Just let me know when the PR is ready and remember to sleep and eat :)

**Comment by sjpadgett** [comment]
@sharonco-matrix Here is new PR so if you guys can look over and see if i've done any harm to your module or any suggestions. https://github.com/openemr/openemr/pull/1307

**Comment by sharonco-matrix** [comment]
Thanks! we will take a look and we are waiting for this fixes to be merged as our system is super unstable. And we are in a critical phase :)

**Comment by bradymiller** [comment]
Is this issue resolved?
(if so, then will close this)

**Comment by bradymiller** [comment]
No reply, so assuming is fixed and closing this issue.
