### ISSUE TITLE
DICOM Web Viewer erroring on master

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#1362]
### STEPS TO REPRODUCE:

1. Clone and pull `master`
2. run `docker-compose up`
3. Login as admin
4. Create a test patient
5. Upload https://github.com/ivmartel/dwv/raw/master/tests/data/dwv-test-simple.dcm to the Lab Reports document category
6. Click on the uploaded file

### EXPECTATION:

It loads!

### ACTUAL:

White screen of death

**Comment by kofiav** [comment]
Thanks for the note, I will look into this within the next couple of days.

**Comment by MatthewVita** [comment]
@kofiav Let me know if you can't reproduce it.

Happy new year !

**Comment by kofiav** [comment]
I was able to reproduce it. Bizarre. Some other change on master must have clobbered the feature. I'll attempt to root it out using a git bisect.

**Comment by MatthewVita** [comment]
Cool, cool

**Comment by kofiav** [comment]
Looks like this is the offending commit that broke the feature on `master`:

c11874506437f56bf66f9bb841220c273b6b2c85

**Comment by sjpadgett** [comment]
How?

**Comment by kofiav** [comment]
Hi @sjpadgett,

It looks like the addition of this line (https://github.com/openemr/openemr/blob/master/templates/documents/general_list.html#L14) to `templates/documents/general_list.html` (from this commit https://github.com/openemr/openemr/commit/c11874506437f56bf66f9bb841220c273b6b2c85#diff-c70919673c887048ebd7fffed9c3f510) is what's causing our problems. 

A naive solution at the moment to get the dicom web viewer to work is to comment out / delete:

`<link rel="stylesheet" href="{$GLOBALS.assets_static_relative}/bootstrap-3-3-4/dist/css/bootstrap.min.css"> `

But since you and @bradymiller  have more context on what was going on in this commit (c11874506437f56bf66f9bb841220c273b6b2c85) and PR (https://github.com/openemr/openemr/pull/1271) you might have a better suggestion?

**Comment by sjpadgett** [comment]
I added the style sheet for the bootstrap modal however, dlgopen() will dynamically include if missing within dialogs scope. If handy, would you comment style out then double click on say a pdf or other document icon in tree (this is what uses the dialog) then try your viewer afterwards, it would save me the setup to test.

**Comment by kofiav** [comment]
I commented out the bootstrap line and tried uploading a PDF and it worked.

![pdf](https://user-images.githubusercontent.com/4621203/34920586-e075f89a-f942-11e7-8fcc-06772838e47e.png)

So I am now able to view the DICOM files and PDFs.

![dcm](https://user-images.githubusercontent.com/4621203/34920607-387a19e0-f943-11e7-8810-1f6268d3fe4a.png)

**Comment by sjpadgett** [comment]
yep, but if you look in the document tree for icon to the left of the pdf file name and doubleclick to popup full screen viewer then knock it down and try to load the lab image, does it work? I can't seem to get viewer to work either way..

**Comment by kofiav** [comment]
Thanks, I am now starting to understand the issue. 

DICOM file shows up when I click it as shown in the image I've already posted, but it doesn't work with the full screen viewer. All I get is a dialog asking me where to save the DICOM file.

![full_popup](https://user-images.githubusercontent.com/4621203/34920862-b2abc25a-f947-11e7-80fb-e62ed1543aab.png)

**Comment by kofiav** [comment]
So this is more than a bug fix. I guess the challenge will be integrating the new functionality you introduced in c11874506437f56bf66f9bb841220c273b6b2c85 with the existing DICOM web viewer.

**Comment by sjpadgett** [comment]
Yep, I can do that and at same time figure out why or what in bootstrap is bothering dicom. In the end I think we need to have the viewer work in bootstrap environment. I'm on windows now and viewer is not working and I think it has to do with mime type. Also bootstrap may be stepping on mime somehow plus I think I see a smarty problem in view template.

**Comment by kofiav** [comment]
Ha! I have had similar problems in the past on Windows (XAMPP) regarding mime type inconsistency. If it helps, the screenshot I provided is on Ubuntu 16.04, so I can't say the issue is being caused by anything intrinsic to Windows, although it's an issue that should definitely be addressed because there's a lot of people running OpenEMR on Windows.

**Comment by kofiav** [comment]
> In the end I think we need to have the viewer work in bootstrap environment

Indeed, this seems like the core issue.

**Comment by sjpadgett** [comment]
@kofiav This feature really needs to be in a container like an iframe. The imported libraries for the viewer are stepping on the tabs frame and resetting html classes for the tab, including adding a hidden class which is why the whole tab white screens because of bootstrap hidden class style. Moreover, windows wants to set the mime type to application/octet-stream (thinks it's a binary, which it is) so, I don't know if windows corrupts the mime on download or simply is not supporting dicom as a mime. We could look at the files header to determine dicom mime as a work around so i'm not too worried about that.
You can probably create a php script to house your viewer code and call it in an iframe like the other mime types.

**Comment by kofiav** [comment]
Interesting, I will look into implementing it the way you mentioned to see if it will take care of the bug. 

As for the mime type issue - it seems this is the code responsible for determining the mime type of a file: https://github.com/openemr/openemr/blob/master/library/classes/Document.class.php#L207-L214

Essentially, the `/usr/bin/file` command is being used to determine mime type (https://github.com/openemr/openemr/blob/master/sites/default/config.php#L13). Instead of using this command it might be better to rely on the mime_content_type (http://php.net/manual/en/function.mime-content-type.php) tool in PHP to ensure more consistent, platform agnostic behavior.

**Comment by sjpadgett** [comment]
Thanks for tracking the mime stuff down. So I will task myself to get mime working on windows and help ya test your changes on windows when you are ready. Also, I think we probably should not allow pop'ing out the viewer in a full screen unless you feel that would be a good option to have, if so, I can help with that.

**Comment by MatthewVita** [comment]
A +1 to putting the DICOM viewer in an iframe. Just make sure you hide the iframe borders so it looks natural.

Thanks for keeping things moving along, @kofiav and @sjpadgett 👍

**Comment by sjpadgett** [comment]
@kofiav @MatthewVita Hi guys, I went ahead and created a php script for the viewer and integrated into an iframe in documents.  Still need to decide where I want the script to reside and fix windows mime type for dicom. Will put up PR later today to review. I allowed viewer to pop out to full screen window in case one would want to view several images. If somebody were so inclined, I would look at resize for the canvas.

**Comment by sjpadgett** [comment]
P.R #1395 Have not tested on linux but should not be an issue unless I stepped on a path. Doubtful :)

**Comment by sjpadgett** [comment]
Tested well plus added viewer dialog from left tree file icon dblclick. I'm satisfied this issue is resolved so if you guys agree, please close.

**Comment by kofiav** [comment]
Agreed

**Comment by MatthewVita** [comment]
Amazing! Just did some QA. Everything is smooth.
