### ISSUE TITLE
popups->chart/Barcode/address Lable : tab name is Unknown

### ISSUE THREAD

**Issue by eyalvo-matrix** [openemr/openemr#1431]
When opening a document with the epdf lib the displayed document does not have title tag 
this causes the tab name to be displayed as "Unknown"
for example : 
related files to the barcode are
interface/patient_file/barcode_label.php
interface/main/tabs/js/custom_bindings.js

causing this: 

![image](https://user-images.githubusercontent.com/20621444/36430285-7d52060e-165d-11e8-8812-d4b2ca60fdaa.png)

I am not sure how to fix this one 
possibilities that I have considered are 
1. overwriting the epdf lib example:
http://www.fpdf.org/en/doc/header.htm

2. using   $pdf->SetTitle('barcode'); in  barcode_label.php
and catch it in custom_bindings.js

3. change custom_bindings.js to get the name from the link

**Comment by sjpadgett** [comment]
Hi @eyalvo-matrix, Maybe this way...
Setting title in pdf will write title to barcode so I suggest wrapping the barcode_label.php in html and set doctype and dynamic title. i.e <title><?php echo xlt($thistitle); ?></title>, Get patient data from globals or session.

**Comment by eyalvo-matrix** [comment]
Hi @sjpadgett but where to put  "<title><?php echo xlt($thistitle); ?></title> " ? 
putting it in  in barcode_label.php before "$pdf->Output();" causes the pdf not to be displayed 
and putting it after "$pdf->Output();" make no difference

**Comment by sjpadgett** [comment]
Hmm, Let me take a shot and i'll get back to ya @eyalvo-matrix.

**Comment by sjpadgett** [comment]
Hi @eyalvo-matrix , Just realized this is meant and is an actual popup in frame ui. Your purposed solutions would work but are tailored to tabs and I would much prefer a generic solution of treating the script as a popup in tabs and title the dialog. The fact this script is opened in a tab is an oversight from the frame to tab conversion and should present the same in both interfaces(Plus there is the other popups like, labels e.t.c). So, I think this is best done the dialog route and because I did the dialog in frames, I will take this issue on and resolve so we keep the feature consistent across U.I's. 
Are we using too many dialog's? I sometimes wonder!

Sorry about the title misread, forgot about header's. Duh! Right :).

**Comment by eyalvo-matrix** [comment]
great :) 
![image](https://user-images.githubusercontent.com/20621444/36528936-72d167de-17bf-11e8-93ef-b22642f3be0a.png)

**Comment by sjpadgett** [comment]
@eyalvo-matrix Hi,
Please see https://github.com/openemr/openemr/pull/1434 and close this issue if it resolves for you. Thank you.

**Comment by eyalvo-matrix** [comment]
Hi @sjpadgett  I rechecked the issue . It seem the issue still exist when selecting 
Modules->Multipledb
![image](https://user-images.githubusercontent.com/20621444/37566177-0306b730-2abe-11e8-8018-cee92d1585d0.png)

**Comment by sjpadgett** [comment]
This menu item has a view so should be able to add a title in the view. Barcode is different because there isn't a user interface and headers have already been sent before hitting script..

**Comment by eyalvo-matrix** [comment]
ok so I will fix this :)
