### ISSUE TITLE
styleguide issue for npm run build

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1688]
hi @d3sandoval and @zbig01 ,

Found another odd thing with `npm run build` in most recent codebase. I had to run it twice for it to work completely.
The first run, it compiled all the non-rtl css files.
Then on the second tun, it compiled the rtl css files.

-brady

**Comment by zbig01** [comment]
Not a bug that is the way the gulpfile.js is written. It first complies the style_*.css files first and uses it to then compile the rtl files. This was causing the sourcemaps for these css files to be written before the rtl styles that were being appended. @d3sandoval  is working on a fix that will complie the rtl stylesheets from scss rather than the on the complied css files and thereby have the sourcemaps added at the end of the css files as they should be.

**Comment by bradymiller** [comment]
Thanks for the explanation. Will wait patiently for the fix :)

**Comment by bradymiller** [comment]
this was fixed
