### ISSUE TITLE
OpenEMR v5_0_1_4: Cross-Site Scripting in interface/fax/fax_view.php

### ISSUE THREAD

**Issue by l00ph0le** [openemr/openemr#1781]
I found an application security issue in interface/fax/fax_view.php of OpenEMR v5_0_1_4 and likely earlier versions.

The vulnerability exists due to a lack of sanitation of user-supplied input. The vulnerability allows attackers to execute javascript on remotely authenticated users via the 'file' and 'scan' parameters.

Proof of Concept URL 'file' parameter:
http://192.168.246.144/openemr-5.0.1/interface/fax/fax_view.php?file=%3Csvg/onload=alert(1)%3E

Proof of Concept URL 'scan' parameter:
http://192.168.246.144/openemr-5.0.1/interface/fax/fax_view.php?scan=%3Csvg/onload=alert(1)%3E

**Comment by bradymiller** [comment]
hi @l00ph0le ,

Thanks for the report! Fixes are in this PR:
https://github.com/openemr/openemr/pull/1783

For future specific security vulnerability reports, rec. emailing them to me at brady.g.miller@gmail.com rather than posting them publicly (and even better if email it encrypted via my public PGP key at: https://pgp.mit.edu/pks/lookup?op=get&search=0x27DEF05B1A8A6D4F).

Thanks!
-brady

**Comment by danehrlich1** [comment]
I believe this should be closed since it's already been fixed. I will be going through this entire folder as well in the next couple of days as well.
