### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by vyas-vinay** [openemr/openemr#1820]
We were considering this project, but this london based firm found some security vulnerabilities. 
https://insecurity.sh/assets/reports/openemr.pdf

Could we prioritize and fix these ? I am not a PHP developer but I will see if I can contribute to some of these.

**Comment by bradymiller** [comment]
Hi @vyas-vinay ,

Read here to get background on the insecurity report along with how the community has already addressed these vulnerabilities:
https://community.open-emr.org/t/openemr-security/10597

Per the above forum thread, the only vulnerability that was not addressed in the initial set of fixes were the CSRF vulnerability since we needed to build a mechanism/framework for this first. This was then addressed in the most recent patch (the specific CSRF vulnerability mentioned in the report was fixed and we now need to address this in the entire codebase); see this PR to get an example for what I mean regarding CSRF:
https://github.com/openemr/openemr/pull/1803

We are definitely looking for contributions/help on improving security; just let me know what your interesting in working on and I can find something related to that and security.

thanks,
-brady

**Comment by alejosv** [comment]
The report link is broken

**Comment by bradymiller** [comment]
interesting. it looks like the entire http://insecurity.sh/ (Project Insecurity:https://en.wikipedia.org/wiki/MLT_(hacktivist)#Project_Insecurity) website has gone away...

**Comment by bradymiller** [comment]
Placed a copy of report here:
https://www.open-emr.org/wiki/images/1/11/Openemr_insecurity.pdf
