### ISSUE TITLE
unknown tab after click on content in messages in dev demos

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#1955]
choose a pt, go to messages, if there's a message click on content else click on "to add notes, please click here", then click on content

**Comment by stephenwaite** [comment]
looks like this was solved by removing the click function to open the dialog from all but the edit button and the type link (usually unassigned), for usability should this be extended?

**Comment by sjpadgett** [comment]
Hi @stephenwaite I'm almost finished with the fixes for Related/Patient Notes working in all three UI cases and your sign and stay for single results. As you will see from the PR it required getting creative for sure:). I'm addressing this issue in PR with removing the pointer cursor for entire row and restyle so edit and delete buttons are inline instead of stacked.
Two chances at edit select with button and type should be more than enough. If you agree then you can prob close this issue as solved.

**Comment by bradymiller** [comment]
@stephenwaite , Just checking if we can close this? -brady

**Comment by stephenwaite** [comment]
sure, thank you Jerry and Brady
