### ISSUE TITLE
package-lock.json changed when runing  npm install second time

### ISSUE THREAD

**Issue by matrix-amiel** [openemr/openemr#2019]
Hi @d3sandoval @bradymiller 

I found that package-lock.json was changed when I'm running command npm install, As I know this file need be updated only in the npm update command and supposed to save on stable version of dependencies libraries. 
Maybe it happen beacues the script `napa && gulp -i` that run after npm intall..?
Do you know what the reason?

This it the output of cli - 
![image](https://user-images.githubusercontent.com/17809866/49568134-baaa2e00-f938-11e8-97c0-049628c9916a.png)
 
Part of the git diff (very long diff file) -
![image](https://user-images.githubusercontent.com/17809866/49568207-fcd36f80-f938-11e8-96e4-8aaf52d7307b.png)

Thank you.
Amiel

**Comment by bradymiller** [comment]
hi,
I am also still trying to figure this out. Whenever I run npm install it also always seems to change. Guessing it is harmless, but not clear why. I remember @d3sandoval explaining this awhile ago, but I forgot :)
-brady

**Comment by matrix-amiel** [comment]
Look this - https://github.com/npm/npm/issues/20891

I think we have different versions of npm.. ):

**Comment by bradymiller** [comment]
hi @matrix-amiel ,
Thanks for that. I just realized I was using npm version 5 in my development version! I upgraded it to version 8 (using version 8 rather than version 10 for now, since this is what the most recent of alpine uses, which is what main openemr dockers are based). And I did a npm install run and pushed this to the codebase. Hopefully this will stop all the changes in that file now.
-brady
