### ISSUE TITLE
Bring parts of codebase up to PSR-2

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2055]
Issue for first timers only currently. Please contact dan@ehrlichserver.com for more info. 

PHP has style guidelines that most people agree on and were formulated via the PHP FIG group: https://www.php-fig.org

OpenEMR aligns currently to PSR-2: https://www.php-fig.org/psr/psr-2/

Please go through the `/contrib/forms` folder and align the spacing, style, etc to PSR-2. Don't worry about getting everything but hit the big ones: https://github.com/openemr/openemr/tree/master/contrib/forms

Some examples below of straightforward things you can work on. Be careful about changing the name / capitalization of functions and variables for now though:

```
Opening braces for classes MUST go on the next line, and closing braces MUST go on the next line after the body.

Opening braces for methods MUST go on the next line, and closing braces MUST go on the next line after the body.

Visibility MUST be declared on all properties and methods; abstract and final MUST be declared before the visibility; static MUST be declared after the visibility.

Control structure keywords MUST have one space after them; method and function calls MUST NOT.

Opening braces for control structures MUST go on the same line, and closing braces MUST go on the next line after the body.

Opening parentheses for control structures MUST NOT have a space after them, and closing parentheses for control structures MUST NOT have a space before.
```

**Comment by danehrlich1** [comment]
@bradymiller Should I delete this issue? Why did you remove those tags?

I'm probably missing something embarrassing so go easy on me in your response :)

**Comment by bradymiller** [comment]
hi @danehrlich1 ,

The code should already follows many of the PSR2 (there were 2 megacommits about a year ago that converted the codebase to mostly PSR2) and travis checks the new PR's for that stuff. There are several items left, which were not converted and are not checked (since manual fixing is required):
https://github.com/openemr/openemr/blob/master/ci/phpcs.xml#L6-L13

We could probably pick some of those (one for each issue) with goal of converting entire codebase for that issue (then we can remove the exclusion from travis); we shoudln't pick one that require arbitrary variable name formatting (like camelcase) since would just be painful and likely introduce lots of bugs. Another related introductory project more on a devops level would be to update codebase to most recent php_codesniffer version which could then update in travis: https://github.com/openemr/openemr/blob/master/ci/ci.sh#L31

-brady

**Comment by danehrlich1** [comment]
Ahhh got it.

Really just created this issue as an easy one for first timers but now we
have plenty of those.

My commits are totally not PSR2 and will fix these / look into this later
too.

**Comment by bradymiller** [comment]
hi @danehrlich1 ,
Any PR you do on the main openemr repo will get checked by travis for the PSR2 rules (minus the exclusions linked above to it); you'll see the travis fail at the bottom of the PR. We don't push to hard for developers to follow it since I can fix them in a commit (I just run a php_codesniffer command on codebase that takes about a minute) after bringing in the PR. If we do net new users that are interested in the stuff, there is a lot of cool stuff to work on.
-brady
