### ISSUE TITLE
Patient file->Prescription: redundant buttons  

### ISSUE THREAD

**Issue by eyalvo-matrix** [openemr/openemr#2144]
When pressing edit (Prescription) in the patient file 
There are "Add", "List", "Done" buttons 
I think  "List" is redundant and the "Done"  should maybe be "close"
furthermore after pressing "Add"  
There are "Add", "List", "Done" , "save" , "back" buttons 
I think  "Add", "List", "Done"  are redundant  and "Back"  should maybe be "Cancel"

![image](https://user-images.githubusercontent.com/20621444/51441115-e0b44380-1cd6-11e9-871d-7afb077a424b.png)

![image](https://user-images.githubusercontent.com/20621444/51440958-ffb1d600-1cd4-11e9-831d-6a0f881c565d.png)

Would like to know your thoughts about the matter.

**Comment by sjpadgett** [comment]
@eyalvo-matrix Add and List use to be Frames called from inline code. Either one(dialog footer) shouldn't go away. Maybe disable the dialog's List or Add depending on context or better yet remove the List/Add in the called script as not needed. Close is fine instead of Done, but in a UI that gives several feature capabilities you're generally done(Done) with session. Semantics and I don't care either way. The Back button too me is harmless and debatable if should go or not.
