### ISSUE TITLE
Configure certain php.ini settings via setup.php and stuff

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2208]
1. Should this line be changed in `setup.php`? Aren't the requirements slightly higher for the version?                         `if (version_compare(PHP_VERSION, '5.2.4', '>='))`
- https://github.com/openemr/openemr/blob/121c4b9792a07fa331ee6ab4fb4d826939c825b2/setup.php#L1163

2. Line 1171 and below - PHP config: 
- add additional configuration via `ini_set`. Would be setting the directives used in the Docker project, which would set `display_errors`, `expose_php`, `sid_bits_per_character`, and `sid_length`. The last two will depend slightly on whether it is 7.0 or 7.1+. 

3. Line 1267 and below - Apache config:
- Edit certain Apache config values? It sort of looks like we are already doing something? Maybe this wouldn't work AT ALL though feel free to comment. Ideally just a few lines would be added. I.e.:

```
ServerSignature off
ServerTokens Prod
TraceEnable Off
FileETag None
Header unset ETag
```

**Comment by danehrlich1** [comment]
Button to make this optional? Especially if ppl are using say older legacy sites on their server and need some weird/old PHP settings?

display_errors = 0

If 7.1 or above:
- sid_bits_per_character = 6
- sid_length = 49

If 7.0:
- session.hash_function = SHA256
- session.hash_bits_per_character = 6

Maybe [curl.cainfo](https://secure.php.net/manual/en/curl.configuration.php#ini.curl.cainfo). I think Scott Arcisnewski has a blog post on this along with a library.

Note that some directives cannot be set with `ini_set()`. See this:
- https://secure.php.net/manual/en/configuration.changes.modes.php
- https://secure.php.net/manual/en/ini.list.php

The following are good settings to have but can't be set except with shell script maybe and `sed`:
- expose_php = 0
- enable_dl = 0

**Comment by a-mt** [comment]
Alright, from my understanding, one can

I - get OpenEMR and use Docker to run it.  
Installs and sets up everything that is needed.

II- get OpenEMR and install manually:  
* Install Apache / MySQL / PHP
* Place OpenEMR in the web directory of Apache
* For developers using OpenEMR directly from the code repository: install the [dependencies](https://github.com/openemr/openemr#for-developers)
* Go to `http://localhost/openemr/setup.php` and follow the steps:

0. System checks if files and directories that need write permissions are writable
1. User has to choose whether to create a database or use an existing database
2. User has to enter the MySQL credentials — is stored in [`sqlconf.php`](https://github.com/openemr/openemr/blob/master/library/classes/Installer.class.php#L400)  
  And, if he chose to create the database, enter the infos (name, password, etc) of the first user to be created in the database.
3. System creates and populates the database of OpenEMR
4. System creates and populates the database of phpGACL
5. System checks the configuration of PHP ([php.ini](https://github.com/openemr/openemr-devops/blob/master/docker/openemr/flex-edge/php.ini))
6. System prints the configuration of Apache to set ([httpd.conf](https://github.com/openemr/openemr-devops/blob/master/docker/openemr/flex-edge/openemr.conf))
7. User has to select the theme of OpenEMR

---

Back to the issue.

1. *if (version_compare(PHP_VERSION, '5.2.4', '>='))*

   `php_ini_loaded_file()` is defined from PHP 5.2.4. Yet according to the docs OpenEMR should run on [PHP>=5.6](https://www.open-emr.org/wiki/index.php/OpenEMR_5.0.1_Linux_Installation) so this test is probably unnecessary (or replace with `get_cfg_var("cfg_file_path")`). All dockerfiles install PHP7, shouldn't it be PHP5.6 to make sure this version is supported?

2. *add additional configuration via `ini_set`*  

   I think we can set some ini variables with `ini_set` in `/interfaces/globals.php` (or in a file loaded by it). Not all of them though (`expose_php`, `enable_dl`, `curl.cainfo`) and root privileges would be necessary to edit php.ini, a PHP process running through Apache can't do that (runs as `www-data` or whatever user Apache is using). The user has to manually edit the file and reload Apache. Why not just let the user know of the variables to set (what is required, what is recommended, like [symfony 3.4](https://github.com/symfony/symfony-standard/blob/3.4/web/config.php) does)?  
  ![2019-02-12-222437_1920x1080_scrot](https://user-images.githubusercontent.com/1093382/52677505-691cb180-2f2e-11e9-82f3-280337559be0.png)

3. Same for Apache configs.

**Comment by danehrlich1** [comment]
Aurelie:

Extremely good and detailed write up.

1. Yes you are right about the incorrect / too low version number. I believe it should be actually 7.0 as of now. 

2. Many users implementing OpenEMR will be Medical Doctors with limited technical skill. I would not necessarily expect them to be able to  move around Linux and edit files. This should be as easy/auto as possible.

**Comment by a-mt** [comment]
Results of my digging:

PHP project easy to install: Wordpress.  
It uses [`header()`](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp.php#L399), [`ini_set() or php.ini`](https://codex.wordpress.org/Editing_wp-config.php#Configure_Error_Logging) and mostly [`.htaccess`](https://codex.wordpress.org/htaccess).  
Rewrite rules can be edited via the app and they are [written in the .htaccess file](https://github.com/WordPress/WordPress/blob/master/wp-admin/options-permalink.php#L88).

---

# What to set

## PHP.ini

* `flex-edge/php.ini` values that differs from [php.ini-production](https://github.com/php/php-src/blob/master/php.ini-production)

      expose_php=Off
      max_execution_time=60
      max_input_time=-1
      max_input_vars=3000
      memory_limit=256M
      error_reporting=E_ALL & ~E_NOTICE & ~E_STRICT
      post_max_size=30M
      upload_max_filesize=30M

      pdo_mysql.cache_size=2000
      mysqli.cache_size=2000
      session.use_strict_mode=1
      session.cookie_lifetime=28000
      session.cookie_path=/var/www/localhost/htdocs/openemr
      session.cookie_httponly=0
      session.sid_length=46
      session.sid_bits_per_character=6

* `flex-edge/php.ini` values that differs from [php.ini-development](https://github.com/php/php-src/blob/master/php.ini-development) (add up to the previous diffs)

      disable_functions = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,

      display_errors=Off
      display_startup_errors=Off
      mysqlnd.collect_memory_statistics=Off
      zend.assertions=-1

* `5.0.0/php.ini` values that differs from `flex-edge/php.ini`

      serialize_precision = 17
      mail.add_x_header = On
      sql.safe_mode = Off

      session.use_strict_mode = 0
      session.cookie_lifetime = 0
      session.cookie_path = /
      session.cookie_httponly =
      session.gc_probability = 0
      session.hash_function = 0
      session.hash_bits_per_character = 5
      ;session.sid_length=
      ;session.sid_bits_per_character=

| Config | Can be set with
|---     |---
| `expose_php=Off`                        | php.ini, unset HTTP header `x-powered-by`
| `max_execution_time=60`                 | PHP_INI_ALL
| `max_input_time=-1`                     | PHP_INI_PERDIR
| `max_input_vars=3000`                   | PHP_INI_PERDIR
| `memory_limit=256M`                     | PHP_INI_ALL
| `error_reporting=E_ALL & ~E_NOTICE & ~E_STRICT` | PHP_INI_ALL
| `post_max_size=30M`                     | PHP_INI_PERDIR
| `upload_max_filesize=30M`               | PHP_INI_PERDIR
| &nbsp; | &nbsp;
| `pdo_mysql.cache_size=2000`             | [Removed since PHP5.3.0](https://github.com/php/php-src/pull/2777)
| `mysqli.cache_size=2000`                | [Removed since PHP5.3.0](https://github.com/php/php-src/pull/2777)
| `session.use_strict_mode=1`             | PHP_INI_ALL
| `session.cookie_lifetime=28000`         | PHP_INI_ALL
| `session.cookie_path=/var/www/localhost/htdocs/openemr` | PHP_INI_ALL
| `session.cookie_httponly=0`             | PHP_INI_ALL
| `session.sid_length=46`                 | PHP_INI_ALL
| `session.sid_bits_per_character=6`      | PHP_INI_ALL
| `session.gc_probability`                | PHP_INI_ALL
| `session.hash_function`                 | PHP_INI_ALL
| `session.hash_bits_per_character`       | PHP_INI_ALL
| &nbsp; | &nbsp;
| `disable_functions=...`                 | php.ini
| `display_errors=Off`                    | PHP_INI_ALL
| `display_startup_errors=Off`            | PHP_INI_ALL
| `mysqlnd.collect_memory_statistics=Off` | PHP_INI_SYSTEM
| `zend.assertions=-1`                    | PHP_INI_ALL

## httpd.conf

    Protocols http/1.1

    # Removes revealing HTTP Headers
    ServerSignature off
    ServerTokens Prod
    TraceEnable Off
    FileETag None
    Header unset ETag

    # Set HSTS and X-XSS protection
    Header set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    Header set X-XSS-Protection "1; mode=block"

| Config | Effect | Default value
|---     |---     |---
| `Protocols http/1.1`                        | Specify the list of protocols supported | `Protocols http/1.1`
| `ServerSignature off`                       | Enable or disable the footer line under server-generated documents ![](https://farm4.staticflickr.com/3897/14902970545_c3d406322f_o.png) | `ServerSignature Off`
| `ServerTokens Prod`                         | Control the content of `Server` HTTP response header + the server signature | `ServerTokens Full`
| `TraceEnable Off`                           | Enable or disable TRACE requests. Disabled: return a 405 (Method not allowed) error to the client | `TraceEnable on`
| `FileETag None`                             | Set the content of `ETag` HTTP response header for static files (used for caching) | `FileETag MTime Size`
| `Header unset ETag`                         | Unset `ETag` from HTTP response headers | ~
| `Header set Strict-Transport-Security ...`  | If sent over HTTPS, tells the browser to redirect all future HTTP requests to HTTPS | ~
| `Header set X-XSS-Protection ...`           | Tells the browser to prevent rendering of the page if an XSS attack is detected | ~

Wordpress also adds

* [X-Content-Type-Options: nosniff](https://github.com/WordPress/WordPress/blob/master/wp-includes/functions.php#L5585) for media files. Prevents the browser to determine the type of data by analyzing the contents of the resource — against « drive-by-download » attacks.

* [X-Frame-Options: SAMEORIGIN](https://github.com/WordPress/WordPress/blob/master/wp-includes/functions.php#L5694) for the login page. Prevents the browser to render the page in a frame tag, unless it is the same domain and port as the current page — against « ClickJacking » attacks.

```
<Directory /var/www/localhost/htdocs/openemr>
    # Only allow these HTTP Methods
    AllowMethods GET POST HEAD OPTIONS
    # No indexes anywhere
    Options -Indexes
    AllowOverride FileInfo
    Require all granted
</Directory>

 <Directory "/var/www/localhost/htdocs/openemr/sites">
     AllowOverride None
 </Directory>

 <Directory "/var/www/localhost/htdocs/openemr/sites/*/documents">
     Require all denied
 </Directory>

 <Directory "/var/www/localhost/htdocs/openemr/sites/*/edi">
     Require all denied
 </Directory>

 <Directory "/var/www/localhost/htdocs/openemr/sites/*/era">
     Require all denied
</Directory>
```

| Config | Effect | Default value
|---     |---     |---
| `AllowMethods GET POST HEAD OPTIONS` | Restrict access to the listed HTTP methods. Cannot deny  TRACE.<br> Disables: PUT, DELETE, CONNECT, LINK, UNLINK | `AllowMethods reset`
| `Options -Indexes` | Disable autoindex of directories without an index file | `Options FollowSymlinks`
| `AllowOverride FileInfo` | Allow htaccess to override directives: document types, mime types, meta datas, rewrite rules, aliases and actions | `AllowOverride None` (Apache>=2.3.9)
| `AllowOverride None` | Ignore all .htaccess files | `AllowOverride None` (Apache>=2.3.9)
| `Require all granted` | Accept all requests | `Require all granted`
| `Require all denied`  | Deny all requests | `Require all granted`

---

# How to set

## PHP configs

PHP configs can be set with:

| Permission level | Value  | Set With
|---               |---     |---
| PHP_INI_USER     |   1    | ini_set() + .user.ini
| PHP_INI_PERDIR   |   2    | php.ini + .htaccess + httpd.conf + .user.ini
| PHP_INI_SYSTEM   |   4    | php.ini + httpd.conf
| PHP_INI_ALL      |   7    | php.ini + .htaccess + httpd.conf + ini_set()

* <ins>.php script</ins>

  ```
  ini_set('memory_limit', '256M')
  ```

* <ins>php.ini</ins>

  ```
  memory_limit = 256M
  ```

* <ins>.user.ini</ins>    
  .ini file on a per-directory basis.  
  Only processed by the CGI/FastCGI SAPI, not mod_php.  
  Same syntax as php.ini

* <ins>httpd.conf</ins>

  ```
  php_admin_value memory_limit 256M
  ```

  * `php_flag` to set a boolean (On/Off)  
  * `php_value` to set a value  
  * `php_admin_flag`, only in .conf files, disables overwriting by .htaccess or ini_set()
  * `php_admin_value`, only in .conf files, disables overwriting

* <ins>.htaccess</ins>  
  Needs to be enabled in httpd.conf with `AllowOverride Options` (or AllowOverride All).  
  Same syntax as httpd.conf

## HTTP headers

* <ins>.php script</ins>  
  Static files would still have the headers.

  ``` php
  header('X-Powered-By: xxx');
  ```

  ``` php
  header_remove('X-Powered-By');
  ```

  Use [header_register_callback](http://php.net/manual/en/function.header-register-callback.php)

* <ins>httpd.conf</ins>

  ```
  <IfModule mod_headers.c>
    Header set X-Powered-By "xxx"
  </IfModule>
  ```

  ```
  <IfModule mod_headers.c>
    Header unset X-Powered-By
  </IfModule>
  ```

* <ins>.htaccess</ins>  
  Needs to be enabled in httpd.conf with `AllowOverride FileInfo` (or AllowOverride All).  
  Same syntax as httpd.conf

## Directory access restrictions

* <ins>httpd.conf</ins>

  ```
  Require all denied
  ```

* <ins>.htaccess</ins>  
  Needs to be enabled with `AllowOverride AuthConfig` (or AllowOverride All).  
  Same syntax as httpd.conf  
  Can't use `Directory` sections but `Files`

  ```
  <Files subdirectory/*>
      deny from all
  </Files>
  ```

## Method restrictions

* <ins>httpd.conf</ins>

  ```
  AllowMethods GET POST HEAD OPTIONS
  ```

* <ins>.htaccess</ins>  
  Needs to be enabled with `AllowOverride FileInfo` (or AllowOverride All).

  ```
  <IfModule mod_rewrite.c>
    RewriteEngine On 
    RewriteCond %{REQUEST_METHOD} ^(TRACE|TRACK|OPTIONS)
    RewriteRule .* - [F]
  </IfModule>
  ```

## Options

* <ins>httpd.conf</ins>

  ```
  Options -Indexes
  ```

* <ins>.htaccess</ins>  
  Needs to be enabled with `AllowOverride Options` (or AllowOverride All).  
  Same syntax as httpd.conf

---

# Conclusion

Configs could be set with `.htaccess` if enabled.  
It would work without having to edit anything if [Apache<2.3.9](https://httpd.apache.org/docs/2.4/en/mod/core.html#allowoverride) (.htaccess is now disabled by default).

<ins>Apache>=2.3.9</ins>:  
Assuming that the user just installed a webserver with the last version of Apache (2.4) and didn't change any configs from the defaults, he would have to edit the .conf file to add `AllowOverride All`.

The location of .conf / web directory depends on the OS.  
The best way to find it is to Google it (ex `[ubuntu|fedora|wampserver|xamp] apache .conf`)

```
<Directory /var/www/localhost/htdocs/openemr>
  AllowOverride All
</Directory>
```

<ins>SSL, vhost</ins>:  
In all cases, the user would need to edit .conf to add a SSL certificate or set up a virtual host.

<ins>Unsure of this (in httpd.conf)</ins>:
```
<Directory "/var/www/localhost/htdocs/openemr/sites">
   AllowOverride None
</Directory>
```
Users might upload a file named `.htaccess` in this directory?

---

I think I didn't forget anything.  
Thoughts?

**Comment by danehrlich1** [comment]
Absolutely outstanding work and incredibly detailed. I'm going to be bringing most of this into our Wiki documentation as well, will be useful for many people even in other PHP projects.

Tasks for now:
1. Set as much as possible / as you can with ini_set() in the `setup.php` file.
2. For everything else, create a bash script that does what is needed. We can provide this to our users, and tell them to just run that. That is easy enough non-technical ppl can eventually figure it out. Users can also selectively copy and paste code if they want. We will warn them to only use it on servers that are ONLY running OpenEMR unless they really know what they're doing (so as not to mess up other sites). 
3. Know that there are 8 total HTTP security headers including the latest ones, Feature-Policy and Expect-CT. They are all not set currently because they interfere with how OpenEMR works. Working on fixing that though :)


Any other questions? 💯

**Comment by a-mt** [comment]
Sorry, still trying to figure out what to do and how to do it :)  
Please tell me if I got it right:

The app currently uses the following configuration files:

* `sites/SITE_ID/sqlconf.php`:  
  MySQL credentials. Generated during setup.

* `sites/SITE_ID/config.php`:  
  contains various configs such as bank id, logo location, etc.  
  Its content can be edited via the app: Administration > Files > config.php

* `library/globals.inc.php`:  
  contains the list of settings that can be changed via the app with a form (lang, theme, etc):  
  — Administration > Globals (global settings). Choices are saved in the database: `openemr.globals`  
  — USERNAME > Settings (user settings). Choices are saved in the database: `openemr.setting_user`

* A bunch of others described in [the docs](https://www.open-emr.org/wiki/index.php/OpenEMR_System_Architecture#Customization_of_OpenEMR) that I don't really care about.

---

Retained todolist:

* make manual installation as easy as possible for non-tech people (do not use jargon).
* init server configs during the setup

  1. configs that can be defined with `ini_set`
     * set them in a php file, say `sites/SITE_ID/ini.php`  
     * load that file in `/interfaces/globals.php`  
     * be able to edit that file via the app: Administration > Files > ini.php  
       Should we let the user edit that file during the setup as well / just indicate how to edit it later?

  2. other configs
     * provide a bash script that edits the configuration files  
       1/ warn the user about it, not to use it on a server that runs other websites  
       2/ should be run as root / with admin privileges

       Should the user download that bash file (he has access to the server via a GUI) / should we create it in a specific location, say `sites/SITE_ID/install.sh`, and add `unlink` at the end (he has access to the server via a terminal)?
     * provide configs to copy/paste in php.ini and httpd.conf if the user would rather have control or if his webserver/OS isn't supported (wampServer/BSD).

* remove `version_compare` in setup.php (l.1163)

* personal todo: lookup 8 HTTP security headers

**Comment by danehrlich1** [comment]
Tasks:

1. Please write `ini_set()` commands in [setup.php](https://github.com/openemr/openemr/blob/master/setup.php). 

2. Please write a bash script that edits the things `ini_set()` can't set. Post the script as a comment on this thread. We will then decide where to host it / put it later. 

Feel free to call me or chat me on RocketChat (chat.open-emr.org) if you have any questions.

**Comment by bradymiller** [comment]
btw, An easy no brainer todo to get in a PR is to yank the outdated version_compare call in setup.php. Since we mandate PHP 7.1 or greater, can just remove that if version_compare line and always run the block of code within it. And if looking for bash scripts that change settings etc check out this related script in the ubuntu/debian openemr package for examples:
https://github.com/openemr/openemr/blob/master/contrib/util/ubuntu_package_scripts/production/postinst

**Comment by a-mt** [comment]
I understand less and less what you're trying to achieve.  
I think there might be a few misunderstandings along the way

1. The effect of `ini_set`.  
   Sets the configs at runtime, it won't actually change the values stored in the configuration files.

   >  Sets the value of the given configuration option. The configuration option will keep this new value during the script's execution, and will be restored at the script's ending.
   > [PHP doc about ini_set](http://php.net/manual/en/function.ini-set.php).

   If we call it in setup.php, it will only change the configs for the current request. I think this is not what we're going for. Other pages would still use the configs that are set with httpd.conf, php.ini or .htaccess — unless they call `ini_set` as well. `.htaccess` and `ini_set` are interesting since they doesn't require to restart the webserver to take effect, and don't require root privileges.

2. The way the webserver works with PHP.  
   We have a running daemon (Apache) that listens HTTP requests, then calls PHP.  
    I think the PHP doc about [Persistent Database Connections](http://php.net/manual/en/features.persistent-connections.php) explains it nicely.

   Whatever PHP does and sets gets ditched once Apache sends back a response to the client, including setting variables or configurations — unlike what would happen with a programming language such as Node.js or Python.

3. Setting configs in `httpd.conf`  
   I would assume it should be able to work with at least the different options that are listed in the [Download page](https://www.open-emr.org/wiki/index.php/OpenEMR_Downloads).  
  The real challenge here is
   * to find a systematic way to know the location of `httpd.conf`  
     No matter which OS/package is used, not only Ubuntu.

     For Linux distros: [Httpd Wiki](https://wiki.apache.org/httpd/DistrosDefaultLayout) / [PHP doc](http://php.net/manual/en/install.unix.php).  
     Need to search: Mamp, Xamp, WampServer, probably a lot more that I don't know about

   * give a script that can work with Windows (batch/bash/php)?

   * once we have our script, make it that the user can easily execute it  
     No matter which way he accesses the server, from running WampServer locally to installing a remote server

**Comment by danehrlich1** [comment]
1. The effect of `ini_set`
- You are 100% correct here and this is my mistake. We will not be using ini_set moving forward.

3. Let's do this:
- Create Bash Script for Ubuntu and one for RHEL (assume Apache 2.4 and PHP 7.1+ for now) @a-mt 
- For MAMP and XAMP you could do screenshots showing the correct settings to set? @a-mt 
- For Windows, maybe a Powershell PS1 script? Maybe there is an easier/ more secure way with Windows IIS? I will look into this - @danehrlich1 


Did everything make sense that time?

**Comment by danehrlich1** [comment]
@a-mt Also check out this other repo: https://github.com/openemr/docker-madness/issues

Its original purpose was to create a highly secure Docker container running OpenEMR. 

Now it is more used a testing ground for security configurations before merging into our main openemr-devops repo. 

Anyway look at the issues later and see, since you are more of a backend person, if anything interests you.

**Comment by a-mt** [comment]
Makes sense. My current todolist:

1. Create Bash script to set configs in httpd.conf + php.ini  
   Should support: Ubuntu and RHEL with Apache 2.4 / PHP>=7.1  
   I will post the script as a comment on this thread.

2. I'm not super familiar with Mac nor Windows (team Linux) but I will try to find out resources that explains how to run Apache for them / how to edit the configs and redact a synthesis.
   Might as well add Linux distros ([Httpd Wiki](https://wiki.apache.org/httpd/DistrosDefaultLayout) / [PHP doc](http://php.net/manual/en/install.unix.php)).
   Should I post it in this thread or on Confluence?

3. Remove `version_compare` in setup.php (l.1163)  
   I will end up doing a PR someday :).

4. Never used Powershell before. Gonna fix that.
5. Lookup 8 HTTP security headers
6. https://github.com/openemr/docker-madness/issues: will check it out later

**Comment by danehrlich1** [comment]
@a-mt You can see the 8 security headers at the bottom of this file btw: https://github.com/danehrlich1/very-secure-apache/blob/master/apache2.conf

**Comment by a-mt** [comment]
## Script

* <ins>Bash</ins>: [config_openemr.sh](https://gist.github.com/a-mt/4a96e90be3588f1d5b50ad9486b21699)  
  Should support: Lamp (Apache HTTPD 2.0, Debian/Ubuntu, Alpine, Fedora/CentOS/RHEL)

  A .sh script can be executed from
  * the Command Line Interface: `sh script.sh`
  * the Graphical User Interface: by double-clicking on it — if it has execution rights (`chmod. +x script.sh`)

* <ins>Powershell</ins>: [config_openemr.ps1](https://gist.github.com/a-mt/aab3d878a78010a91d5e89b6c3370feb)  
  Should support: Xamp (Windows)

  A .ps1 script can be executed from
  * the PowerShell Interpreter: `./script.ps1`
  * the Command Line Interface:  `powershell script.ps1` — if Powershell `Get-ExecutionPolicy` is not `Restricted` (Linux: `pwsh script.ps1`)
  * the Graphical User Interface: by double-clicking on it — if the default file association of `ps1` is `powershell.exe`

## Documentation

Is on its way, but I'd like to make sure of the dependencies:

| What for | Packages
|---       |---
| lamp     | `apache`, `php7`, `php7-*`, `perl`, `tar`, `curl`, `mysql-client`
| SSL      | `openssl`, `openssl-dev`
| certbot  | `git`, `python`, `py-pip`, `python-dev`
| [fax support](https://github.com/openemr/openemr/blob/master/Documentation/INSTALL#L259) | `libffi-dev`, `imagemagick-dev`
| [backup](https://www.open-emr.org/wiki/index.php/Automated_Backups_to_an_Alternate_Server) | `rsync`, `dcron`
| npm (dev) | `nodejs`, `nodejs-npm`
| composer (dev) | ~
| ? | `build-base`, `shadow`

What about `faxstat`/`sendfax` and `enscript` listed for fax support in the doc, I don't see it in the dockerfiles?

**Comment by danehrlich1** [comment]
@a-mt Please look at this page for the Linux dependencies (Debian): https://www.open-emr.org/wiki/index.php/OpenEMR_System_Architecture#Ubuntu_16.04_and_Mint_18_and_Debian_9_and_greater_versions_.28PHP7.29_.28With_MySQL_or_MariaDB.29

Does that help?

Sorry I'm not sure about the fax issue specifically.

**Comment by a-mt** [comment]
Hum looks like I did something wrong there. Please ignore the extra commit references :).

1. I documented the manual installation on Confluence.  
    I assumed the user wants to install the latest version of OpenEMR.

    I still have to add the actual command line instructions to run for specific OS/distros. As for the security part and other types of install, I would rather let someone with actual expertise fill that in.  
    You should: tell me if anything is incorrect / missing. Probably correct English mistakes as well.

2. Did a PR to remove version_compare (#2240).  
    I should add issues references in the PR description rather than the commit message?

**Comment by danehrlich1** [comment]
@a-mt 

1. Hey your stuff on Confluence looks beautiful. Like it is breathtaking compared to [current wiki](https://www.open-emr.org/wiki/index.php/OpenEMR_Wiki_Home_Page) that's been around for a while.
1a. Going to go through it later today for English edits and other stuff,. I also have some other people who will be adding to the AWS section. I'll be taking the Google Cloud/GCP section since that's my area of expertise :)

2. I would add issue references to both commit message and PR description. That way if someone is looking at just a history of commits only (which sometimes will exclude pull requests to make it easier to read) they can still see the issues you are talking about. 

3.
