### ISSUE TITLE
NGINX Reverse Proxy

### ISSUE THREAD

**Issue by junelsolis** [openemr/openemr#2378]
Hello everyone,

Is there anyone who could please shed some light on how to get OpenEMR to work with an NGINX reverse proxy with SSL termination?

**Comment by bradymiller** [comment]
hi @junelsolis ,

The OpenEMR demo farm uses a NGINX reverse proxy with SSL, so that is a working example. Can find the nginx/conf that is used for this here:
https://github.com/openemr/demo_farm_openemr/blob/master/docker/nginx/nginx.conf

Here's the run command for the nginx docker:
https://github.com/openemr/demo_farm_openemr/blob/master/docker/scripts/demoLibrary.source#L178-L189
(in this case, there's lots of demo farm specific stuff, which can remove and would recommend using docker-compose instead if go the route of a docker)

-brady

**Comment by bradymiller** [comment]
Also,
Note above example is still using apache/php for openemr (just using nginx as reverse proxy). If you are interested in using nginx/php-fpm for everthing, then can see an example for that here:
https://github.com/openemr/openemr/tree/master/contrib/util/docker/dockers/dev-nginx
(note it is overcomplicated since it is supporting a bunch of different endpoints since used for the insane docker dev environment: https://github.com/openemr/openemr/tree/master/contrib/util/docker#insane-development-docker-environment ;  also note it is using dummy ssl certs since this is just used for development)

Note that using nginx/php-fpm rather than apache would be considered "experimental" and unless are very proficient in nginx, would avoid in the production setting.

-brady

**Comment by junelsolis** [comment]
Thank you @bradymiller 

I did try using the OpenEMR reverse proxy config but it didn't work at that time. Given, I was reverse proxying other upstream sites on the same NGINX server also. I will keep trying to get this to work and report back once I get a working configuration.

**Comment by danehrlich1** [comment]
Joshua:

Can you work on this issue at some point? Consider it a separate project.
We'll discuss scope later. Should be very simple once we fix ModSecurity.
No reason we can't finish it by end of summer worst case scenario
