### ISSUE TITLE
Page Refresh: Athentication error

### ISSUE THREAD

**Issue by ophthal** [openemr/openemr#2530]
The Authentication error prevents a page refresh.  Do we have to unset the session token in interface/main/tabs/main.php?  A page refresh should not require a re-login should it?

> // this will not allow copy/paste of the link to this main.php page or a refresh of this main.php page
> unset($_SESSION['token_main_php']);

**Comment by bradymiller** [comment]
hi @ophthal , Check out this PR where this code change was discussed: 
https://github.com/openemr/openemr/pull/1926

**Comment by bradymiller** [comment]
Looks like should at least:
"If do this should I throw up a warning if a user tries to do a page refresh from browser (via window.onbeforeunload) to prevent user from doing a browser refresh and losing their work"

Will add this issue a a critical bug fix.

**Comment by bradymiller** [comment]
Hi @opthal ,
Here's a PR to address this issue (it shows a warning when either try to refresh or back out of main page):
https://github.com/openemr/openemr/pull/2551

**Comment by ophthal** [comment]
In my case, I refresh the page to start anew when I am done with a task and just want the default tabs opened.  Show me the Calendar and let me move on to another task.

The default action on any other website is to bring you to a main/default start page, with session cookies intact.  Re-login is not necessary.

Why not give the warning, keep the session active (maybe kill the active pid) and show the main page with Globals’ default tabs open?  That way you warning the people who forgot to save but don’t force everyone to login again?

**Comment by bradymiller** [comment]
hi @ophthal ,

Used a global to make this optional. There are now 3 options.
 - Default option is to warn and not allow refresh (it will kill the session and go to login screen)
 - Also option to warn but allow refresh (this allows what you want, but with a confirmation popup if for example you are using a mobile device where it's easy to swipe down and mistakenly refresh the browser)
-Also option to not warn and allow refresh (this gives what you want without a refresh)

The reason why it is default to warn and not allow refresh is because havoc can happen if a user simply copy/paste the web address in another tab since they will then share the same session id and then are in a position to mix patient records.

OpenEMR does not act like a standard website. It contains a mechanism to be able to open different patient's in different web browser tabs without them clashing, which is described here: https://github.com/openemr/openemr/blob/master/src/Common/Session/SessionUtil.php#L8-L13

This does the job, but is not ideal and will likely at some point not work in the future. This is because it requires the ability of javascript to be able to modify the session cookie. There is a cookie setting called cookie_httponly, which when sent to true does not allow js to even look at the session cookie, which is a huge security improvement (ie. session can't be stolen by cross-scripting attacks), and I predict in a couple years that browsers will force this setting.

On the flip side, the patient portal does act like a normal website (since only 1 patient is being edited), an in that case, we are taking advantage of the cookie_httponly setting:
https://github.com/openemr/openemr/blob/master/src/Common/Session/SessionUtil.php#L99

The future goal is how to support opening of multiple patient's safely within 1 OpenEMR login, and then we can drop the need for OpenEMR needing to have js edit the cookie, and then use the cookie_httponly setting . This is entirely possible, but would take a moderate amount of work. It's also something that would be best to work on after the 5.0.2 release after we remove all the frames gui (plan to only then offer tabs gui) code.

-brady

**Comment by bradymiller** [comment]
btw, migrated the session/cookie management improvents to this issue:
https://github.com/openemr/openemr/issues/2556
