### ISSUE TITLE
Session Troubles

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2612]
windows 10 PHP 7.1.7RC1
umm Unsure here but I think needs addressing.
If logged in one tab and new log in via new tab, new log in steps on session of previous tab instance. Result, original tab session is lost.
Of course, from same user agent.
Opening new tab from OpenEMR patient finder seems okay.

If memory serves, this use to work!

**Comment by sjpadgett** [comment]
I just checked this against my test bed based on master from around 4/5/2019 and works as I thought it always has.
However testing on chrome seems okay upto two tabs, three breaks. FF is the most broken at only two in 502 release...

**Comment by bradymiller** [comment]
hi @sjpadgett ,

When we updated zend and brought in the listener thingy, it unmasked a zend module issue (it was overwriting the session), which I thought I fixed by basically removing it (did extensive testing, or at least I thought I did).To help isolate this (ie. rule out is a windows issue), can you run your above testing on the following demo and let us know how it goes:
https://www.open-emr.org/wiki/index.php/Development_5.0.2_Demo#Demo_.28Alpine_3.10_-_uses_php_7.3.29
(use the without demo data one)

thanks, -brady

**Comment by sjpadgett** [comment]
@bradymiller 
Very broken. W/FF open tab, goto https://six.openemr.io/b/openemr/index.php. Open new tab goto https://six.openemr.io/b/openemr/index.php. Back to first tab shows Site ID is missing from session data!
Same result with chrome.

**Comment by bradymiller** [comment]
Oops, I should not of removed this code for the session/cookie refactoring:
https://github.com/openemr/openemr/pull/2615
(I also included your path fix on this)

**Comment by sjpadgett** [comment]
Hi @bradymiller 
Promoting you to Detective, First Grade! This works for me. Thanks for fix.
