### ISSUE TITLE
viewing sent messages

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#2677]
seems like there's a bug in the message center since after you send a message you can't view it again unless you know the patient and go to their chart, so basically messages.php should be able to look at pnotes and show some recent mesaages 

the show active and show inactive buttons don't seem to have any effect

**Comment by stephenwaite** [comment]
### re-describe the problem
sad state of affairs :)
### re-create 
we're going to add a new message to demonstrate some confusion with the messaging
![Screenshot from 2020-03-22 19-53-40](https://user-images.githubusercontent.com/5618372/77266780-dee96580-6c76-11ea-8b35-383e9d231e95.png)
odd, the patient already selected wasn't added to the patient subject so will have to click to add
![Screenshot from 2020-03-22 19-55-24](https://user-images.githubusercontent.com/5618372/77266847-1821d580-6c77-11ea-963b-ac75af47b036.png)
after adding Phil to list and clicking ok will send the message
ok, message is sent and here is new view
![Screenshot from 2020-03-22 19-57-59](https://user-images.githubusercontent.com/5618372/77266975-823a7a80-6c77-11ea-8956-29c506386d53.png)
we're viewing Active Messages now and we don't have any
![Screenshot from 2020-03-22 19-57-59](https://user-images.githubusercontent.com/5618372/77267048-b9109080-6c77-11ea-8bfe-49242aec5b1c.png)
the only way to view the message is to click the people icon to show messages for all users but this view doesn't have a To field
![Screenshot from 2020-03-22 22-19-02](https://user-images.githubusercontent.com/5618372/77274097-7eb0ee80-6c8b-11ea-92a4-5d2fe0a89923.png)

wanted to describe this a little more for @bradymiller @kchapple

**Comment by kchapple** [comment]
Thanks @stephenwaite I’m interested in getting this fixed, and adding some needed refactoring and enhancements to the messaging and reminders system. How do you think we can best manage a project like this? Could be quite a large commit. Have you heard of any other vendors with customers interested in messages enhancement?

**Comment by stephenwaite** [comment]
Hi @kchapple , thank you for following up and will be glad to hear what you have to propose since you're more experienced with project management in openemr. My first thought is just a simple fix to enhance the basic mail features we all expect. An inbox, sent items and the `to` field included in the default view. It may seem strange but feel like the current setup isn't too far off the mark.

I've not heard of any other vendors interested.

**Comment by kchapple** [comment]
@stephenwaite @bradymiller I would like to merge dated reminders and messages, as it is confusing what to use when. I'd like to improve the ability to sort, search, group and categorize messages.

**Comment by mdsupport** [comment]
I agree with @kchapple.  Over time instead of multiple single function services we have created a confusing set of components that address developer's need at that point.  E.g. 
1. all patient related reminders belong to either a single table like patient_reminders or that table and its component table(s).  That will make it possible for rules engine to include manual actions.
2. pnotes should be for purely notes about the patient at a given point in time.
3. messages should be purely for communicating with ability to include relevant pointers to various objects in emr.  Also it is time to stop tracking conversation as a single message.

Sorry for the rant but over years lot of time has been wasted to convince users about many of these issues.

@stephenwaite, re. your specific issue - I think it is a couple of lines of patch that allow user to select messages where 
pnotes.assigned_to = current user _OR pnotes.user = current user_.

**Comment by kchapple** [comment]
If Brady is on board, I’d like to tackle the messages as a whole for 503, and keep you guys in the loop on spec and design. I will start with prototype/sketches and some use cases. Sound good? I’m planning on joining meeting today if you’d like to chat about it. 

Ken

**Comment by sjpadgett** [comment]
Nobody asked for my opinion(the busy body I am) but I agree and even look forward to seeing what you come up with.

**Comment by mdsupport** [comment]
@kchapple ,
Here is user interface we have used for last few years leveraging bootstrap components and integrating reminders and messages in a single list.  User clicks on header to see message body and all related links like documents, lab results etc.  Status updates are done using status dropdowns.  Replies currently invoke original interface but that was our being lazy.
We can share code but full refactor using inline forms etc will be far easier.

![image](https://user-images.githubusercontent.com/399047/78457156-079d3200-765d-11ea-8571-3767bf418ce0.png)

**Comment by mdsupport** [comment]
Without appearing to pile on, there is an operation aspect currently missing.  If a message/reminder is sent to an user and that user leaves/goes on vacation, there is no easy way for another user to take over open items.  In many cases that can be malpractice.

**Comment by bradymiller** [comment]
@kchapple , heck yes, I am on board :)

**Comment by sjpadgett** [comment]
Okay Ken so when, tomorrow maybe or do ya need a couple more days?:)

**Comment by bradymiller** [comment]
lets be realistic. eta 9 days until finished product in codebase :)

**Comment by sjpadgett** [comment]
30 days if I help:)

**Comment by kchapple** [comment]
Are you volunteering to help? You’re signed up!

Ken

**Comment by sjpadgett** [comment]
> Are you volunteering to help? You’re signed up!

I was being facetious! I was joking on another issue and before ya know it, ding, Brady assigned the issue to me:) I must be more careful!!!
Besides i'm sure ya don't need my meddling:)

**Comment by tywrenn** [comment]
We have more work to do on this :(

**Comment by kchapple** [comment]
Please describe the use case in more detail @tywrenn

**Comment by tywrenn** [comment]
One of the sore thumbs of using this form is that in order to say something is "done" using this screen, you have to select "done" and then, for some reason, "send message" is the button you press to mark it as done.

Also on new portal appointment notifications, there isn't a way to make these messages push to SMS or Email so doctors can respond more quickly to new appointments (my practice really wants this function). Also with this you cannot send a message back to the patient confirming that you have received the request for the new appointment which is where I'd like a template of some sort to be put in so you can write a confirmation message back to the patient.

**Comment by stephenwaite** [comment]
bump

**Comment by kchapple** [comment]
Still on the chopping block

**Comment by tmccormi** [comment]
This is still an issue. Bumpity.

**Comment by kchapple** [comment]
This is still an issue. On the chopping block. Bumpity.

**Comment by growlingflea** [comment]
I'd be happy to take a swing at this  I've made some customization/ improvements to the messages widget and I'm familiar with the code.

**Comment by kchapple** [comment]
There’s a whole lot more to do than just sent messages....
Group messaging
Forward mapping (think when a provider leaves)
Consolidate reminders and messages
Threaded messages
Add status (task management)
Port to datatables
Inbox filters
Hooks to hook in external email/sms
Open message thread in new tab

**Comment by mdsupport** [comment]
@kchapple If we do all items on your list, it will be a collaboration platform. So instead of spending dev hours/$ on building one, it will be win-win if that effort is spent on integrating something like Zimbra. Effort is then limited to a mechanism to sync the communication information for users and patients. Then EMR users will benefit from a rich user interface with several workflow possibilities.

**Comment by kchapple** [comment]
@mdsupport I don't disagree, but I'd lean more towards a simple UI based on jQuery DataTables that can be integrated with external systems like Zambra, Zix, SMS, etc. via plugin/module. I don't think requiring a bohemith Java app that has to run side-by-side with OpenEMR is feasible. My list is really pretty basic requirements.

**Comment by kchapple** [comment]
I don't think you were too far off with your screenshot above.

**Comment by stephenwaite** [comment]
bump
