### ISSUE TITLE
Possible MedEx error

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2693]
Noted `require_once(dirname(__FILE__)."/../log.inc");` L-35 in `library/MedEx/MedEx.php`
However log.inc no longer exist or have I missed something?

**Comment by bradymiller** [comment]
hi @sjpadgett , That line should be removed.

**Comment by sjpadgett** [comment]
@bradymiller I'll put up a fix later today. I would have thought someone would have complained as this would be a show stopper!

**Comment by ophthal** [comment]
This file handles real-time callbacks, like a webhook, from MedEx.  If it fails, the background MedEx file picks up messages also.  However, I am noticing this file has another error:

`if (empty($_POST['callback_key'])) {`
 
should be

`if (!empty($_POST['callback_key'])) {`

If the callback key is present, a login and sync is attempted.  
Since this is a webhook from MedEx, MedEx generates this callback key.
If it doesn't match, the login does not occur.

Good thing the log.inc was removed or this bug would have been a security bug.

**Comment by sjpadgett** [comment]
I'll include the other in my PR however, MedEx should not even be able to load because the require_include('log.inc') will throw an error preventing the rest of MedEx loading. At least i'd hope it would or PHP is messing with Jerry again. :)

**Comment by ophthal** [comment]
Right.  It wasn’t loading from that error however if you only removed that line, the file would have worked and the other line would have been an issue…
Without this MedEx.php file, there is no realtime feedback for patient responses in the FlowBoard, Calendar or Recall Board.
Because some practices are off-line, and thus can never get realtime updates, MedEx also has the passive “background” method for syncing responses, and that is set at baseline to every 29 minutes.  However background services only runs when/if someone opens an OpenEMR session.
So we also advise low volume practices who may not open the OpenEMR program daily, to set up a cron command to run the background script 4 x /day.  
In addition, if a critical message is received (eg. call back requested to change an appointment), practices get an email alert if they enable that feature.

Between all of these, there is a fair amount of redundancy to ensure messages go out and responses are received, so the staff can act accordingly.
Fixing this bug keeps it all humming.  If you get a chance to look at the way it all functions for a live practice using MedEx on OpenEMR, you’ll appreciate how important this realtime feature is for a busy practice, how much staff time it saves and why the redundancy is critical. 

Thanks for identifying and putting up the PR.

**Comment by sjpadgett** [comment]
Yep I get it. Nice, no doubt. I'm looking now to add a node messaging server to pull some of the core burden of managing reminders etc running events. If I ever get it finished:)
You're welcome and will be sure it gets in 502 patch.

**Comment by sjpadgett** [comment]
fixed #2697 & #2696 (502)
