### ISSUE TITLE
HTTP ERROR 500 DURING INSTALLATION

### ISSUE THREAD

**Issue by faraimupfuti** [openemr/openemr#2727]
HTTP ERROR 500 pops up when i begin the installation process.

i am using wamp server 3.1.9 
PHP 7.2

**Comment by tywrenn** [comment]
Hello,

Before we debug this, please make sure that you have installed all PHP extensions required for OpenEMR. [You can find the extensions required here](https://www.open-emr.org/wiki/index.php/OpenEMR_System_Architecture#OpenEMR_Dependencies). If you do not have a certain PHP extension, most likely a 500 error will happen. Also make sure that the directories for OpenEMR are properly chmodded and that you are following the [install instructions](https://www.open-emr.org/wiki/index.php/OpenEMR_Installation_Guides).

If none of the above things work, please do the following to 
(left click) wampmanager icon -> PHP -> PHP Settings
Click on "Show all errors, warnings and notices including coding standards"
Restart apache then try running the install of OpenEMR again. You should see an error log for PHP instead of a 500 error. Let me know what that error shows.
