### ISSUE TITLE
Calendar refresh

### ISSUE THREAD

**Issue by jasoom8** [openemr/openemr#2773]
i add javascript function that auto refresh the calender using refreshme() function every 20 sec ,but that lead to increase the memory slowly until it takes the whole memory even after logout the memory not released, and i try location.reload() but nothing change is there anyway to slove it?
i use xampp 3.2.4 and try php7.2 and php5.6

**Comment by tywrenn** [comment]
Here are a few recommendations:
- When you are refreshing the calendar page, you are querying your server to pull up the calendar, therefore consuming server memory to load that page. Before setting up such a system that refreshes the page every 20 seconds, please make sure you have enough memory (at least 8GB of RAM) to run OpenEMR.
- To make sure the server is using its memory correctly, you must make sure your php.ini variables are set correctly for OpenEMR. OpenEMR requires the following to be set in your php.ini file:
short_open_tag: Off
display_errors: Off
register_globals: Off
max_input_vars: at least 3000
max_execution_time: at least 60
max_input_time: -1
post_max_size: at least 30M
memory_limit: at least 256M
mysqli.allow_local_infile: On
- Also I'm not recommending having 2 versions of PHP on your server as OpenEMR requires PHP 7 in order to work.
Let me know if any of these recommendations helped you or if you are still having issues.

**Comment by jasoom8** [comment]
thank you, but the RAM size is 16GB and the php.ini variabels is the same as yours comment already and still appache take all the RAM more than 13GB

**Comment by tywrenn** [comment]
Where are you placing the refresh function? 
Try adding the below code before the closing `</head>` tag in the file `interface/main/calendar/modules/PostCalendar/pntemplates/default/views/header.html`:
```
<script>
 $(function() {
	setTimeout(function() {
		refreshme();
	}, 20000);
});
</script>
```
I tested this and it works fine and i'm only using 4GB of RAM.

**Comment by jasoom8** [comment]
thank you for your help, i was placing my code in ajax_template page maybe thats cause the problem,
the code i wrote is check for mouse movement and keyboared pressing to stop refreshing with javascript but its not working now in the ' header.html '

**Comment by sjpadgett** [comment]
this is not really an OpenEMR issue or even designated for feature enhancement(dev custom code) so really should be on developer forum.
Closing.
