### ISSUE TITLE
Selected "Code" in Immunization Registry Not Displaying as a Whole

### ISSUE THREAD

**Issue by litemikx** [openemr/openemr#2794]
Under Reports->Client->Immunization Registry, when you select an option in the list, the code doesn't show fully. 

![2019-11-19_01-55-56](https://user-images.githubusercontent.com/8636946/69077225-1ac5b180-0a70-11ea-9ae4-bf1c0e5bbcec.png)

I can make adjustments via CSS, but not sure if I should do the change via inline, on file or in the global css files. 

Cheers!

**Comment by sjpadgett** [comment]
Or you could take a shot at restyle by adding some bootstrap classes to those tables. Just start at the top of the table tree and work your way down. Getting rid of any absolue sizes for containers and adding percentages. 
It's a smaller form and a restyle can be satisfying once you do one.

**Comment by litemikx** [comment]
Hi @sjpadgett , just to confirm, I can clean up styling on file immunization_report.php, use existing Bootstrap to style the table and change any absolute or static size values to percentage to have it more somewhat "responsive"?

**Comment by sjpadgett** [comment]
> somewhat "responsive"

Is the keyword:) I've found that adding a bootstrap table class to tables used in form layouts helps with responsive. zbig did some styling in those report headers but the left and right container aren't responsive.
However if you only want to fix the issue and move on then just add an inline style because eventually we will be circling around ro restyle these reports.

**Comment by litemikx** [comment]
Cool! I guess I'll take a shot on the restyling :) Thanks @sjpadgett !
