### ISSUE TITLE
Unexpected behavior in ci pipeline

### ISSUE THREAD

**Issue by zerai** [openemr/openemr#2840]
Hi, adding the command 'composer install' broke the ci pipeline.
the php_codesniffer process generates multiple unexpected errors, it scans the vendor folder, and this is a strange behavior (vendor folder is marked as 'excluded') in phpcs.xml and phpcs_strict.xml.

[Here](https://github.com/zerai/openemr/blob/travis-issue/.travis.yml) my travis file.
[Here](https://travis-ci.org/zerai/openemr/builds/624849543) can see travis result.

Related to #2838

**Comment by bradymiller** [comment]
It looks like the lint styling uses phpcs.xml, but not the php syntax checking, so it will include vendor. Will need to likely work in ignoring that directory in these crazy lines:
```
            if find . -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"; then failSyntax=true; fi;
            if find . -type f -name "*.inc" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"; then failSyntax=true; fi;
```
As an aside, I'm gonna bring in the PR that will address the styling issues tomorrow (https://github.com/openemr/openemr/pull/2835) and also add php 7.4 to the grid (and drop php 7.1).

**Comment by bradymiller** [comment]
Also another route to go for your builds would be to include a new grid item in the env section maybe called CI_JOB=phpunit (or whatever plan to do) and then place the testing for it in ci.sh. Then it won't get touched by the lint syntax or styling section and will be testing on all the php versions.

**Comment by bradymiller** [comment]
hi @zerai ,

I just updated main codebase to use php 7.4 and also added another test for the build, which is where can place testing (this then gets tested in all php version environments):
https://github.com/openemr/openemr/commit/ab351f175fbee7333945195b3627c333318f27a5

Hopefully this is what you were thinking. If not, let me know.

thanks! -brady

**Comment by zerai** [comment]
Hi @bradymiller ,
the new statement ('build_test') in the bash script works well, now we have a PHPUnit set up and the first test in place(NumberToTextTest.php).
the php-codesniffer job still fails, sorry I don't have knowledge about this tool, usually, I use php-cs-fixer.

[Here](https://github.com/zerai/openemr/blob/ci_improvments_%232838/.travis.yml) my travis file.
[Here](https://travis-ci.org/zerai/openemr/builds/625346443) can see travis result.

**Comment by bradymiller** [comment]
hi @zerai ,
What are your thoughts on the approach on following PR?
https://github.com/openemr/openemr/pull/2844

**Comment by zerai** [comment]
Hi,

Now the pipeline is green and this is a good thing,
with this configuration we can start writing unit tests.
before merging, it is possible to activate the composer cache in travis.yml and see the result?

Secondary / future points to consider:
- At some point we should run phpunit with different param (--coverage-clover = coverage-report.clover --log-junit = test-report.xml) at least once for the minimum version (7.2).
then we will need a variable COVERAGE = true / false in travis.yml, the sh script will be able?


- "$ BIN_DIR / phing vendor-clean" this command is necessary? Is time expansive and may be dangerous.

**Comment by bradymiller** [comment]
hi @zerai ,

Brought in the code here (gave you authorship since I basically hacked your work):
https://github.com/openemr/openemr/commit/5038e5b08c68a63242ced44a4602f226c52a13ab

Definitely change this as you see fit (for example, if best to migrate it all of ci/ci.sh to travis.ci)

Regarding the cache stuff, just wary if something weird/breaks on upstream package (since goal is to duplicate a production build at that instance).

Regarding phpunit in composer, not I am bringing that in as a global package. If that won't work long term, feel feel to bring it in non-global. We avoid using the require-dev in composer.json since end users use composer for modules (and generally forget the no-dev flag, so figured best to just not put anything in there).

Regarding Tests class inclusing, definitely feel free to bring that back in if needed (just bring it in the standard psr-4 inclusion in composer.json).

thanks! -brady
