### ISSUE TITLE
pdf download selected statement not printing payment stub

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#2846]
hey @sjpadgett could you help me figure out why nothing is getting printed out in the pdf past this line https://github.com/openemr/openemr/blob/master/sites/default/statement.inc.php#L398

**Comment by stephenwaite** [comment]
it's writing the output and it's probably the settings in the `new Cezpdf`

**Comment by sjpadgett** [comment]
I'll take a look.

**Comment by sjpadgett** [comment]
> shouldn't we be using pdf globals here?

Yes, not sure when it got hard coded. Just in case tho, may be because globals margins may not work well for this form.
A second thought, why are we even printing card logo's by default. Many may not accept these cards and therefore should not be printed. I say, take em out.

My test with pdf download works as for content however, not sure if bottom of statement is printing on same page.
Is your problem not printing portion of page at all?

**Comment by stephenwaite** [comment]
yes, there's no bottom part to return with the statment
[Stmt_Stephen_1(48).pdf](https://github.com/openemr/openemr/files/3979569/Stmt_Stephen_1.48.pdf)

**Comment by sjpadgett** [comment]
umm, what the heck! :)

**Comment by sjpadgett** [comment]
@stephenwaite 
Jeez.. such a simple thing as a missing single quote can get you everytime. Check out L-406 of statement.inc.php!
`style='width:2.0in;vertical-align:middle;'>` portion was missing the single quote.
That tear off will still need to be styled though...

**Comment by sjpadgett** [comment]
Pr #2850

**Comment by stephenwaite** [comment]
bailed me out again ⛵️ thank you sjp

**Comment by sjpadgett** [comment]
Anytime. Well almost anytime :)
