### ISSUE TITLE
TOTP Verification code not valid

### ISSUE THREAD

**Issue by visolveaoh** [openemr/openemr#2890]
Hi @bradymiller 
When I create user and successfully login as first login and user change password as his own and then register TOTP is registered successfully and If user try to login all verification codes not valid 

But if user not change password and register TOTP it's works fine 

What's your suggestion to fix this?

note: OS ubuntu 18.04 Openemr 5.0.2(1)

**Comment by bradymiller** [comment]
hi @visolveaoh ,

There should only be one scenario where the TOTP secret key is encrypted with the password hash as the encryption/decryption key:
https://github.com/openemr/openemr/blob/master/interface/main/main_screen.php#L183-L199
(only done in the case when a user sets up TOTP during setup.php since there are no properly set up keys yet)
Note that in this scenario, the TOTP secret key is reencrypted/decrypted on first successful login with the standard OpenEMR encryption/decryption key, so it should not cause issues since the user needs to login before changing password.

Can I get more detailed steps on your workflow that is causing your bug so I can try to recreate it.

thanks, -brady

**Comment by bradymiller** [comment]
Additionally, also let me know what are you seeing in the error log when it happens.

**Comment by usama-kabel** [comment]
review this issue
https://github.com/openemr/openemr/issues/3053
