### ISSUE TITLE
Custom report fails if PDF version > 1.4 documents included in report.

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#2908]
The` custom_report.php` script needs some fixes in rel-502. When it generates a large pdf, it ends up failing and spitting out this message:
`Fatal error: Uncaught setasign\Fpdi\PdfParser\CrossReference\CrossReferenceException: This PDF document probably uses a compression technique which is not supported by the free parser shipped with FPDI. (See https://www.setasign.com/fpdi-pdf-parser for more details) in /var/www/openemr/vendor/setasign/fpdi/src/PdfParser/CrossReference/CrossReference.php:251 Stack trace: #0 /var/www/openemr/vendor/setasign/fpdi/src/PdfParser/CrossReference/CrossReference.php(210): setasign\Fpdi\PdfParser\CrossReference\CrossReference->initReaderInstance(Object(setasign\Fpdi\PdfParser\Type\PdfIndirectObject)) #1 /var/www/openemr/vendor/setasign/fpdi/src/PdfParser/CrossReference/CrossReference.php(68): setasign\Fpdi\PdfParser\CrossReference\CrossReference->readXref(2649156) #2 /var/www/openemr/vendor/setasign/fpdi/src/PdfParser/PdfParser.php(158): setasign\Fpdi\PdfParser\CrossReference\CrossReference->__construct(Object(setasign\Fpdi\PdfParser\PdfParser), 0) #3 /var/www/openemr/vendor/setasign/fpdi/src/PdfParser/PdfParser.php(203): setasign\ in /var/www/openemr/vendor/setasign/fpdi/src/PdfParser/CrossReference/CrossReference.php on line 251`

**Comment by sjpadgett** [comment]
Can you try same report settings without including documents in report?

**Comment by tywrenn** [comment]
@sjpadgett It does work when removing documents from the report -- we might have to remove that functionality since it causes it to flat out not work when generating.

**Comment by sjpadgett** [comment]
> we might have to remove that functionality since it causes it to flat out not work when generating.

lol my friend. maybe let's take a shot at fixing first. kind of important to doctors and patients.

Maybe try to narrow to what documents fail. Then take a look at it. Could be trying to convert to image where imagemagick(I forget, I think that's the php module) is not installed, config'ed etc.

**Comment by sjpadgett** [comment]
@tywrenn Okay, found issue not parsing out pdf's. don't remember if this worked before mPdf. Might need to zip up the download and include documents as separate files.

**Comment by sjpadgett** [comment]
@tywrenn @bradymiller 
So looks like we have an achilles heel concerning mPDF or FPDI specifically. Beginning with PDF version 1.5 there were new compression features introduced which may involve, depending on pdf creation compression technique, the free mPDF vendor FPDI PDF-Parser not working.
Going to need to write/add to our pdf classes(do we even have?) a validation to test for compression and pdf version if supported.
If not, i'm thinking we go ahead and provide the offending documents as separate downloads in an archive package that includes the newly created custom report pdf.. At least allow to complete at minimum...
Thoughts?

**Comment by sjpadgett** [comment]
@tywrenn 
Here's a fix that will need a better resolve for broken pdf parse but test anyway.
from BS4 project source but meat is at L-623 through L-659 if want to paste in 5.0.2.

[custom_report.zip](https://github.com/openemr/openemr/files/4176437/custom_report.zip)

**Comment by stephenwaite** [comment]
hi @sjpadgett , we have 2 PDF classes
https://github.com/rospdf/pdf-php
and
https://github.com/dompdf/dompdf
right?

**Comment by sjpadgett** [comment]
@stephenwaite 
Nope those are libraries that best not modify because then we have to maintain. I have a basic class I use for CCDA.service I could add to but I can get by with an exception.

Problem now is how to handle failed PDF parse/include so somehow they are included in report.
PDF v1.5 has been out for awhile now with depending on who generates PDF whether or not strict compression is used. Take labcorps, our free parser will handle but Quest generated doc's fail(require commercial parser). Our internal PDF's generation is okay for now but bares being cognitive of version....
Why in the world haven't any vendors/users complained about this bug???? I'm in mirth:)

This report is finally working very well with a few format issues and now this.

What do you think about pattern that if any document includes fail, we continue generating custom report to completion placemarking failed pdf parse in place.ie Error Doc xxxxx.pdf failed as my mod does but maintain list of failed documents until after custom report completes then create a zip/tar archive that would  include all the PDFs for download like custom-report.pdf, failedpdf1.pdf, failedpdf2.pdf and so forth?

**Comment by stephenwaite** [comment]
hi @sjpadgett , that sounds fine

**Comment by sjpadgett** [comment]
Okay this is what i've come up with:
in custom report
![image](https://user-images.githubusercontent.com/1859985/74285586-300b4e80-4cf4-11ea-9348-53ba4260f255.png)
Zip:
![image](https://user-images.githubusercontent.com/1859985/74285813-8e383180-4cf4-11ea-9312-449d297972b2.png)

Not sure what i'd take to bring back to v5.0.2 but here is source for those interested:
[custom_report.zip](https://github.com/openemr/openemr/files/4188862/custom_report.zip)
 This only happens if included pdf fails to parse to pages. otherwise works as normal except report won't fail and will complete with errors documented in pdf.

For fax will eventually open zip and send pdfs one at a time.

**Comment by sjpadgett** [comment]
close fixed in portal and BS4
