### ISSUE TITLE
Modifying/customizing existing forms

### ISSUE THREAD

**Issue by nasirtechnelligence** [openemr/openemr#2921]
Hello,
I am new to openemr and I need help regarding customizing existing forms.
I tried and was successfully able to customize the "Vitals" form by add new data fields. 
Now, I want to customize the SOAP form by adding some options within the form like new/clear/reset fields, load previous recorded data etc. But when i tried to customize the form, multiple problems started to occur like the form goes blank if tried to include my own javascript, or adding/calling php functions in .html file etc. I need help/information regarding customization of existing forms.
Customizing Vitals form was relatively easy as i used the code from the existing fields in the form to create new fields.

Currently, i am working as a Junior Web Developer with little experience of 4 months. So, any kind of help will be highly appreciated.

**Comment by mdsupport** [comment]
SOAP uses template as pure html with insertion of code generated from the php class scripts.  So you should make html changes in html file and php changes in appropriate php files.

Blank php form would suggest some syntax error introduced by your code that will be seen in error log.

**Comment by nasirtechnelligence** [comment]
Can you please specify or mention the files that should be changed in order to customize front end with functionality.

**Comment by mdsupport** [comment]
If [this](https://github.com/openemr/openemr/blob/master/interface/forms/soap/templates/general_new.html) is the html file you are changing, as long as you follow [Smarty](https://www.smarty.net/) syntax, you should not have any problems.

**Comment by stu01509** [comment]
Hello @nasirtechnelligence and @mdsupport 

Is this issue solve? If not I would like to fix it, It seems like related to #3303

**Comment by mdsupport** [comment]
I think #3303 is more generic issue.  But this one is very closely related to #3322 that can bring modern interface and a urgently needed feature to the project.  You will need green light from @ophthal / project admins as to if you can replace the whole directory and add couple of fields to form_soap table.  #3322 currently misses inserting an entry in 'registry' table for new form.  In this case no registry changes will be needed since the form already exists.  Also since this is existing form, there will need to be extra testing to make sure existing data / forms are not impacted.
Finally, if you end up doing this put a note on forum under COVID-19 as many existing installations would be interested in testing/using it.
