### ISSUE TITLE
Contrib Forms Need A Serious Makeover

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#2923]
This is my next issue that I plan to tackle after dealing with the huge BS4 pull - fixing a ton of the contributed forms as some are using outdated code standards and aren't responsive at all. This will take awhile to redo all of them but it will be worth it in the end.

**Comment by mdsupport** [comment]
A small percent of installations productively use contrib forms since they deal with specialties.  On the other hand most frequently used features are begging for complete makeover.  

One area that could effectively use your expertise is eliminating use of jquery-ui which makes it difficult to make content responsive.  A quick check finds 68 hits for `jquery-ui` in master.

Another area would be replacing knockout.js based menu system with BS navigation which will then permit inline forms and more.

**Comment by tywrenn** [comment]
Hmm...good point. Might come back to this later.

**Comment by sjpadgett** [comment]
> Another area would be replacing knockout.js

Knockout is very handy. Is it a dead project? I won't oppose but it is tied closely to several areas that could get dicey...
