### ISSUE TITLE
Required: suggestions for PR template

### ISSUE THREAD

**Issue by thesmallstar** [openemr/openemr#2981]
As discussed, we are adding the PR template and I need some suggestions from mentors before I proceed.

1. A  general PR template would include, Description and Fixes heading.
2. We can add a checklist that the contributor needs to follow, like
 a.  Reading some guidelines
b.  Ensuring Tests are passed
c.  Every commit is squashed unless individually required
d. There is a proper commit message 

Is there anything else we could add?

**Comment by bradymiller** [comment]
hi @thesmallstar ,
I'd focus on:
A proper explanation of the PR
(otherwise, wouldn't add many other requirements since don't want to scare folks away from contributing; we've had some really nice code contributions that come in all sorts of crazy messed up git branches since git proficiency and coding skills are not always aligned :) ; and the nice thing about github PR's is we can just squash the whole mess into 1 commit when bring it in :) )

**Comment by bradymiller** [comment]
I also should of added. It's not that uncommon that we end up fixing PSR2 issues (causes a travis fail) after bring in a PR.

**Comment by thesmallstar** [comment]
@bradymiller I guess a simple template will then work,  on it.
Sorry for the delays, I have college exams on going :)

**Comment by bradymiller** [comment]
no prob. college exams take priority :)

**Comment by thesmallstar** [comment]
Closed by #2991
