### ISSUE TITLE
Change help_files modal to use bootstrap instead of jquery-ui (interface/help_modal.php)

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3000]
Change help_files modal to use bootstrap instead of jquery-ui (interface/help_modal.php)

**Comment by sjpadgett** [comment]
I believe I changed all the drag/resize to new library on helps. May only need to remove the Header reference.

**Comment by mdsupport** [comment]
I must confess that I had not looked at the new help setup.  Over the years we have found large documents should be translated as a whole rather than collection of sentences.  It creates more confusion for international users.  

Wouldn't it be better to have these files as plain BS4 themed html that can be inserted in either a smarty template or `<div>` element of a small wrapper script?  For non tech users it would be easier to use any word processor and create well structured translation that can be included in a help files naming scheme that includes language as part of it.  

For others google will do increasingly decent job when the user chooses to translate the page option.

**Comment by bradymiller** [comment]
I guess I am just happy to see full sentences :)
(note many places in codebase with fragmented sentences)
