### ISSUE TITLE
Unexpected Behaviour of NavBar [UI-issue]

### ISSUE THREAD

**Issue by yashrajbothra** [openemr/openemr#3071]
### Describe the bug

When Opening more than 5 tabs (locked) there is a horizontal scroll bar and after scrolling the Navbar is not Sticked.
![image](https://user-images.githubusercontent.com/47683556/75878133-22527000-5e3f-11ea-980a-436ac9b9b772.png)

### To Reproduce

1. Open more than 5 tabs
2. Lock all the tabs 
3. Scroll side to the end 
4. See error there is no Navbar 

### Expected behavior
Either Navbar should be sticked. OR We should limit users to 5 tabs

### Additional Context
I would like to work on this 😃

**Comment by sjpadgett** [comment]
@yashrajbothra 
Pretty sure that 5 may not be the magic number depending on viewport size tabs are loading into. 
Looks like locked tab width is falling between a breakpoint or script is not setup with a collapse navbar. Not sure this will be predictable.
So, unsure how you would attack but it's yours and will assign.

**Comment by mdsupport** [comment]
@yashrajbothra It would be better to look at it from user's perspective.  If someone has 12 inch screen, having 5 tabs locked and usable is physically impossible.  However someone with 30 inch screen and readable font size would have no problem with same choice.

One of the options we have had in place for long time (PR #361) limits damage to tab header to a preset limit (8) using css.  In bootstrap wold, expected behavior would be for the tab headers to collapse into a button.  Ideally even the locked tab content will also become vertical display with scrolls.

Best.

**Comment by yashrajbothra** [comment]
I agree , Definetly only 5 tabs was bad idea. 
I will look for another way and will discuss before implementing

**Comment by im-Amitto** [comment]
@yashrajbothra 
Referencing some implementation you can use
http://embed.plnkr.co/4sNttlcmG6OXqE9tbzzS/
https://embed.plnkr.co/1p4KwR/
