### ISSUE TITLE
Add new patient not working

### ISSUE THREAD

**Issue by yashrajbothra** [openemr/openemr#3100]
### Describe the bug

"Click Here to add a new patient." link not redirecting to the add new patient page.

### To Reproduce
![image](https://user-images.githubusercontent.com/47683556/76139536-d2f68480-6076-11ea-84ff-6dda61d100b7.png)

1. Hover on  'Administration/Patients'
2. Click on 'Merge Patient'
3. Click on Input feild next to target patient 
4. Search any patient which doesn.t exist.
5. Click on "Click Here to add a new patient." 

![image](https://user-images.githubusercontent.com/47683556/76139582-4f896300-6077-11ea-8602-0ad7c58d3e9a.png)

### Expected behavior
Should redirect current page to "Add new patient" page.

[In another senerio] Currently onclick of this button it redirects the page to the "Add new patient" in Same page. IMO that new page should open in another window or Tab.  Otherwise the current state of tab is getting lost 🤔 

### Client configuration

- Browser: CHrome
- Operating system: Win 10

### Additional Context
I would like to contribute on this 😄

**Comment by bradymiller** [comment]
Hi @yashrajbothra ,

It's yours :)

Agree that this should be fixed, but it looks like that modal can produce different messages for when search is empty. For example, here is how it looks in the Reports->Financial->Pat Ledger

![image](https://user-images.githubusercontent.com/278968/76140336-5cbe3780-600e-11ea-8a32-e46552151aef.png)

I would have the modal do the same thing in the Merge patient gui since the goal of that gui is to merge 2 patients together; not search for patients.

**Comment by bradymiller** [comment]
@yashrajbothra , Here is a place though in the calendar where we should be supporting the Add New Patient link. Note it almost works except that it takes over the Calendar tab. Like you suggested above it should open in the separate tab that is used when entering in new patient.
![image](https://user-images.githubusercontent.com/278968/76140424-20d7a200-600f-11ea-9103-51a0845e2381.png)

**Comment by yashrajbothra** [comment]
>Like you suggested above it should open in the separate tab that is used when entering in new patient.
> ![image](https://user-images.githubusercontent.com/278968/76140424-20d7a200-600f-11ea-9103-51a0845e2381.png)

I will take care of both senerio's 👍. Can fix both scene in one PR ?

**Comment by bradymiller** [comment]
Definitely ok to fix both in one PR. thanks! -brady

**Comment by yashrajbothra** [comment]
Hii Sir @bradymiller  should i open "Add Patient" page in another dialog box on top of this or should we close all dialog box and open another which is not so cool. Any other suggestion will be fruitful. 😃

**Comment by sjpadgett** [comment]
> should i open "Add Patient" page in another dialog box on top of this

Hi @yashrajbothra 
First as a fyi, if you leave dlgopen() winname param(second param) empty and call inside another dlgopen() new dialog will auto cascade. You only need to make sure that opener depend is included in opening dialog.

Second, i'm kind of mixed opine as to workflow here. Currently, once add new is selected, a new Add/Search patient tab is opened. This is reasonable imo with most all times, we should never see/need to add a patient from appointments. Most times a new patient is already in system because appointments will be given on checkout after an encounter.
On the other hand, adding new patient could be nice if taking appoint by phone etc. So, if ya want to take it on then i'm never against giving more features of convenience to hard working providers/users.

My initial thoughts/approach might be
- add an onClosed event to search dialog to check if add new is clicked or cancel/x'ed out.
- now alert is disposed the onClosed routine would open new dialog calling normal Add/Search Patient. I'd add an onClosed in new dialog for validation and ensuring your appointment dialog has new patient info populated.
- get some applause from us administrators! 🥇 

Look forward to see what you come up with...
