### ISSUE TITLE
Create Patient Encounter API 

### ISSUE THREAD

**Issue by prondubuisi** [openemr/openemr#3131]
### Describe the problem

Write an endpoint for uploading patient encounter 

Write concise description of what feature you want
create a
POST /api/patient/:pid/encounter API endpoint

**Comment by prondubuisi** [comment]
@bradymiller How do I proceed any pointers

**Comment by bradymiller** [comment]
hi @prondubuisi ,

To get an idea how the api works, rec following how the `POST /api/patient/` endpoint works, which will create a new patient with the posted data (note the route sends it the the applicable Controller that then send it to the applicable Service):
https://github.com/openemr/openemr/blob/master/_rest_routes.inc.php#L74-L78
https://github.com/openemr/openemr/blob/master/src/RestControllers/PatientRestController.php#L28-L38
https://github.com/openemr/openemr/blob/master/src/Services/PatientService.php#L113-L160

So, in your case, the plan is to do something like that but rather than patient focus on creating the encounter by adding the route and adding code/function to the Encounter controller and service. To create the encounter, can leverage/use the code that is already in OpenEMR at interface/forms/newpatient/save.php

**Comment by prondubuisi** [comment]
Hello @bradymiller , thanks for the pointers

I am trying to access the Patient API to see how things work, I am using a docker Install. visiting `http://localhost:8300/api/patients` returns a page not found error, please what does the API URL for a docker install look like?

Also is there a documentation for the API's  currently available, I am particularly interested in what Query Parameters the APIs accept 

Thanks

**Comment by bradymiller** [comment]
hi @prondubuisi ,

Recommend checking out https://github.com/openemr/openemr/blob/master/API_README.md which list all the api functions.

First step is to turn it on in OpenEMR:
Administration->Globals->Connectors->"Enable OpenEMR REST API"

Note the API_README.md is showing examples in cron commands. The first one you always need to do is the token request, so try this to see if it works from command line (copy/paste whole thing):
```
curl -X POST -H 'Content-Type: application/json' 'http://localhost:8300/apis/api/auth' \
-d '{
    "grant_type":"password",
    "username": "admin",
    "password": "password",
    "scope":"default"
}'
```

It should return something like:
```
{"token_type":"Bearer","access_token":"eyJ0b2tlbiI6IjAwNld4VlpINllSdlMwMTRLb1FQTDZVMlNDS1hCNmZDdWttUHlVQytFSCtkXC9HU3d2VzliQkdKQlpiUTJ3RE9pa0lIcGc5YUNMSytBWVdRWmxjTWtzbHZPSzFUYmRWMHFYMDRrcHU2WWJ0aUZGaVUrN3RRSEpjU2VwSXhZZ28rQktOOUNSWFBraVdkVHZMY3c4cHc0dDJFK3htd1BobjdNU1N2SVk0VTVtUjhyclM1bFZvTFJ0STE1T1FmWVpxTHhhN1MiLCJzaXRlX2lkIjoiZGVmYXVsdCIsImFwaSI6Im9lbXIifQ==","expires_in":"3600","user_data":{"user_id":"1"}}
```

And then can use that token to run the function.

Recommend then start using Postman for the api calls, which is easier to use once you get it going.

-brady

**Comment by bradymiller** [comment]
sorry, didn't mean to close it. just re-opened it.

**Comment by prondubuisi** [comment]
> sorry, didn't mean to close it. just re-opened it.

Lol, Its a sign we are getting done with this issue soon D:

**Comment by prondubuisi** [comment]
Hello @bradymiller, I am trying to test the API and I have errors showing that I am not sending in required fields, even though I have filled them up, please what am I missing, thanks 
![Postman](https://user-images.githubusercontent.com/22311928/76540968-2e63b080-6483-11ea-8b8b-b11147d744d1.png)

**Comment by bradymiller** [comment]
hi @prondubuisi ,

Use the Body->raw (and pass a json)

![image](https://user-images.githubusercontent.com/278968/76589126-41d44300-64a6-11ea-9642-0fd8f5b0695d.png)
