### ISSUE TITLE
Timer not aware of focus

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#3138]
### Problem
Timer based scripts such as dated_reminders and background_services continue to be called even when user moves away from main window.
### Expected behavior
Main frame should listen to window focus event and suspend/activate timer accordingly.
Expected downside is returning user will have a few seconds of delay before message counter gets updated.

**Comment by bradymiller** [comment]
background_services needs to keep running whenever somebody is logged in (although agree as posted in your prior issue that is can be turned off if there are no background services)

message counter also should keep going since it places the reminders on the top title bar (unless I am missing something)

**Comment by mdsupport** [comment]
> background_services needs to keep running whenever somebody is logged in
Only browser push api will alert user of reminders irrespective of active tab/window.  Otherwise when emr window comes to foreground it triggers event which runs reminder and other checks and then begins timer cycle until user switches tab.
To put reminders in perspective, only date part is set.  So a reminder status is not dynamic unless someone sends one due today or in the past...
