### ISSUE TITLE
Align search icon with search text input field.

### ISSUE THREAD

**Issue by surendrap720** [openemr/openemr#3140]
### Describe the problem

Immediately when you log in there is a search field on the extreme right side. This search field has a search icon which is not properly aligned with the search field.

### Describe the solution you'd like

Make the search icon properly align with the search text input field. Remove the icon borders to make it look good.

![2020-03-11](https://user-images.githubusercontent.com/15845220/76382412-095e2900-632f-11ea-98c1-76a51da0d471.png)

![2020-03-11 (2)](https://user-images.githubusercontent.com/15845220/76382452-30b4f600-632f-11ea-869c-04665f87a988.png)

Please assign this issue to me.

**Comment by bradymiller** [comment]
hi @surendrap720 , 

There's been recent work on this here:
https://github.com/openemr/openemr/issues/3091
https://github.com/openemr/openemr/pull/3093

But definitely feel free to further improve it and I will assign it to you. Check out @sjpadgett 's comments on the links above for some things to also think about while working on this.

**Comment by surendrap720** [comment]
Looking at the search bar and search icon, I thought it is dislocated but later I understood the location is fine but the needs to be worked on making it look good.

**Comment by im-Amitto** [comment]
@bradymiller If we are working on it again, why won't we just change this search with simple UI as we are using in the entire codebase.
The current one uses `float`, `absolute positioning` and `rounded corners` which aren't necessary IMO. We can easily wrap the input and search button together as a single inline element like we are using search everywhere in the codebase.
@sjpadgett what you think about his?

**Comment by sjpadgett** [comment]
The dev that did this restyle had his reasons for doing the expanding and I think he was trying to make the search distinctive as it was a requested feature from our long time frame UI users.
Now with BS4 I think it should be consistent with the rest of the UI so i'd like to see it as any other search form ie normal input with append/prepend button.
We can keep the expanding if somebody can find a good reason for it but otherwise it just ends up pushing other elements on a fixed expand size. Just make it to expand dynamically while typing as @mdsupport suggested.

**Comment by bradymiller** [comment]
yep, agree with all to make consistent and simplify :)
