### ISSUE TITLE
CCDA module unexpected error

### ISSUE THREAD

**Issue by yashrajbothra** [openemr/openemr#3165]
### Describe the bug

cannot understand error message

### To Reproduce
![image](https://user-images.githubusercontent.com/47683556/76702704-f31ae900-66f1-11ea-958c-bc0d978dc279.png)

1. Open CCDA->View CCDA
2. See error

### Expected behavior

clear and understandable error message

**Comment by yashrajbothra** [comment]
Can anyone help me with this?

**Comment by sjpadgett** [comment]
hi yash,
this particular exception is being thrown because controller could not create a socket to the ccdaservice.
Best fix is to not throw an exception and die a pretty death. The error is being logged then exception thrown. Several options with easiest being to echo error in die or exit script.
Or wrap that connection setup in a try/catch and handle message from the catch.
 all this occurs in: `public function socket_get($ip, $port, $data)` of:
`interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php`

**Comment by yashrajbothra** [comment]
But why `socket_connect` cannot connect. i tried to check error with `socket_strerror( socket_last_error())` but output shows this
![image](https://user-images.githubusercontent.com/47683556/76708261-7ac91d80-671b-11ea-85e4-84573b60352c.png)

Both in demo server and local.
I think something is wrong with my config or globals 🤔

**Comment by sjpadgett** [comment]
> I think something is wrong with my config or globals

socket can't connect because the ccdaservice is not installed or did not auto start.
see openemr/ccdaservice/README.md
if the ZH ccda build is not being used then my ccda builder is used. The ZH builder requires an account with them with the socket connection to their mirth server.

**Comment by yashrajbothra** [comment]
Thank you sir @sjpadgett 👍

**Comment by yashrajbothra** [comment]
![image](https://user-images.githubusercontent.com/47683556/76709190-af8ca300-6722-11ea-8940-449bb953e711.png)
Definetly i turned debugging options on but
is this okay or a bug to be resolved ?

**Comment by stephenwaite** [comment]
hi @yashrajbothra, it's a bug, https://community.open-emr.org/t/ccda/9486/25?u=stephenwaite

**Comment by sjpadgett** [comment]
> is this okay or a bug to be resolved ?

We mostly got all theses static methods over the last year when update for PHP 7 but the original way this app was written they were all over so, yes a bug. Sometimes not an easy fix but give it a shot if you can. Eventually we'll have to fix.

If you still can't run the ccda module then you can bypass exceptions caused by the deprecated statis calls by turning off ~E_DEPRECATED & ~E_STRICT & ~E_USER_DEPRECATED in php.ini
this is only temp solution to make the app run.
hope this makes sense.

**Comment by yashrajbothra** [comment]
I will definetly give this a try. But as of now priority is to make proposal and gather knowledge about the project. So I will be back after 2 weeks and then i will give this a shot
