### ISSUE TITLE
Maintaining Fax SMS Module

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#3374]
I could use a little help with the best way to maintain our module repo.

Currently I am using branches for version control however this seems/is cumbersome. Okay for dev.
Is it best to merge the branches then tag them or keep maintaining branches.

Once a branch is merged and tagged, can/should you checkout the merged tag/branch, modify and retag?

https://github.com/openemr/oe-module-faxsms

**Comment by morg0n** [comment]
Hey!  I would say to merge then tag, then delete the old branch.  I think I am a little confused by the re-tagging part.

**Comment by sjpadgett** [comment]
I think that's what i'll do. I really meant move tags but best just to do new patch release etc.
Thanks @morg0n

**Comment by tywrenn** [comment]
This is OFT yet I believe that we need to invent an API for email/fax/sms which would allow us to consolidate all the old email/fax/sms code and focus on maintaining one file instead of a bunch of files. I've noticed there are so many methods that trigger emails in the code that I don't know if all the methods are working at all anymore. Here's some examples of areas that need attention:
- Batchcom is basically useless if ur using Twilio -- putting this in an API would make it somewhat better
- The folder `/modules/sms_email_reminder` is really really outdated and should actually be removed if possible

**Comment by sjpadgett** [comment]
Modules RC and Twilio classes extend an abstract dispatcher class thus allowing for REST endpoints. Vendor selection is automatic.

For emails didn't think it was a issue but and endpoint prob a good idea.


> * /modules/sms_email_reminder

Is legacy and we have to be careful removing especially email which is the only free choice provider have for appt notifications. Maybe can be spruced up though...

**Comment by sjpadgett** [comment]
> * Batchcom is basically useless if ur using Twilio

Here we could add a dispatcher event

**Comment by tywrenn** [comment]
@sjpadgett The only reason I bring up consolidation to one API is the fact that having too many ways to send out notifications will make things confusing for the end user. Having 1 instead of 3 ways to send notifications makes things generally easier to setup.

**Comment by bradymiller** [comment]
Regarding tags, note you can't really reuse a tag. If need to maintain separate versions (like we do with OpenEMR), then would rec mimicking what we are doing with OpenEMR now (branches for versions).
