### ISSUE TITLE
encounter summary dropdown: previously clicked forms appear selected

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#3383]
### Describe the bug
please see:

https://github.com/openemr/openemr/issues/3382#issuecomment-614203577

### To Reproduce

1. open an encounter
2. add a form like procedure order
3. go back to summary tab
4. go to add another form and you'll find procedure order still outlined as selected

### Expected behavior

dropdown entries should appear fresh afaik

### Client configuration

- Browser: firefox
- Operating system: ubuntu

**Comment by stephenwaite** [comment]
here it is @stu01509 , thank you

**Comment by stu01509** [comment]
> here it is @stu01509 , thank you

Thank you, I will fix it asap.

**Comment by stu01509** [comment]
Hello @stephenwaite 

I reproduced in Edge Chrome and Firefox and set the button state in focus mode, This problem seems only happened in Firefox.

Certainly, I also found a way to fix it. Just add a class style `outline: none`, but I'm not sure it is the best solution.

Chrome:
![image](https://user-images.githubusercontent.com/22230889/79702229-e3388b00-82d5-11ea-9707-d902830689a2.png)

Firefox:
![image](https://user-images.githubusercontent.com/22230889/79702231-e92e6c00-82d5-11ea-925d-035f6b1dac48.png)

**Comment by stephenwaite** [comment]
maybe defer to style expert @tywrenn ?

**Comment by stu01509** [comment]
I found some related articles about the Firefox button focus outline issue, It seems like most people use `outline: none;` to solve it.

https://medium.com/@hassadee/remove-blue-border-outline-in-chrome-and-dash-border-in-firefox-b857d452d136
https://stackoverflow.com/questions/71074/how-to-remove-firefoxs-dotted-outline-on-buttons-as-well-as-links

**Comment by stephenwaite** [comment]
nice,  then go for it @stu01509 :bowling:
