### ISSUE TITLE
TravisCI Failure

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3384]
### Describe the bug
Current TravisCI build is failing
Logs:
`Example E2e (OpenEMR\Tests\E2e\TestOpenemrPage\ExampleE2e)
 ✘ Url without token should redirect to login page
   │
   │ Failed asserting that two strings are identical.
   │ --- Expected
   │ +++ Actual
   │ @@ @@
   │ -'OpenEMR Login'
   │ +''
   │
   │ /home/travis/build/openemr/openemr/tests/Tests/E2e/TestOpenemrPage/ExampleE2eTest.php:38
   │
FAILURES!
Tests: 4, Assertions: 7, Failures: 1.`

### To Reproduce
Check TravisCI

### Expected behavior
No Errors

**Comment by bradymiller** [comment]
hi @tywrenn ,

This is an erratic bug since it is only failing about 1 in 5 times on the following e2e tests:
https://github.com/openemr/openemr/blob/master/tests/Tests/E2e/TestOpenemrPage/ExampleE2eTest.php#L30-L39

Hopefully just a transient bug.

**Comment by bradymiller** [comment]
For now, commented out the test that is related to the travis issue:
https://github.com/openemr/openemr/commit/353e9134bcbf2dcf6ba9f2aeb5601d011650ee74

**Comment by zerai** [comment]
Hi @bradymiller @tywrenn,
this test is not critical (IMHO), but you can see how "testing" is useful.
This is not erratic bug, the behavior of th esystem is changed, 
you should check the difference in 5.02 and 5.0.3 demo farm.

5.0.2 behavior
- go to login page
  http://seven.openemr.io/e/openemr/interface/login/login.php?site=default
- manualy change the url with   /interface/main/tabs/main.php
RESULT
- redirect in login page

5.0.3 behavior
- go to login page
- [http://eight.openemr.io/openemr/interface/login/login.php?site=default](http://eight.openemr.io/openemr/interface/login/login.php?site=default)
- manualy change the url with   /interface/main/tabs/main.php
RESULT
- white page with "Site ID is missing from session data!"

`$this->assertSame('OpenEMR Login', $title);`
The above code fail because there is no title in error page.

**Comment by prondubuisi** [comment]
Hello @zerai I tried replicating 5.0.3 behavior but I still get a redirect, and no white page, has anything changed?

**Comment by zerai** [comment]
Hi @prondubuisi,
A short video in order to see the behavior.
[https://drive.google.com/file/d/1PbtiBqW2VFdyJPl3pnh7CrcRT9HBbooa/view?usp=sharing](https://drive.google.com/file/d/1PbtiBqW2VFdyJPl3pnh7CrcRT9HBbooa/view?usp=sharing)

**Comment by prondubuisi** [comment]
> Hi @prondubuisi,
> A short video in order to see the behavior.
> https://drive.google.com/file/d/1PbtiBqW2VFdyJPl3pnh7CrcRT9HBbooa/view?usp=sharing

Thanks, will check it out once the site comes up again

**Comment by bradymiller** [comment]
hi @zerai ,

I can not confirm that bug on Firefox 75.0 . When I paste the /interface/main/tabs/main.php into the link it gets brought back to the login page. Make sure you clear your web browser cache.

This does appear to be a erratic bug since it happens only 30% of the time on the travis e2e testing (usually about 3 fails out of the 12 identical tests and not related to specific php/mysql/mariadb versions).

It all started with travis updating the chrome webdriver version, which broke all e2e testing since it appeared the symfony/panther version was not compatible with this. We then upgrades the symfony/panther version and this is when this bug showed up. Notably, the easy dev openemr docker environment which uses a chromium webdriver has no problems (I have run the test dozens of times with no fails).

**Comment by zerai** [comment]
> this test is not critical (IMHO)

It try to simulate malicious behavior from user, this type of tests should be (penetration test) in a separate line (maybe with a specific framework).

If you remember, the initial goal of this file (Example.php) was travis configuration, if the cause is chrome, you can remove or move this test to another travis job (like security-job/ penetrationTest-job with a penetrationTest fraework.)

**Comment by tywrenn** [comment]
This bug appears to have been fixed as I never see it happen at the moment. Closing.
