### ISSUE TITLE
Remove Squiz.Scope.MethodScope exclusion from PHPCS rules

### ISSUE THREAD

**Issue by prondubuisi** [openemr/openemr#3392]
### Describe the bug

write concise description of what the bug is.

The current Squiz.Scope.MethodScope exclusion in PHPCS allows one to write methods without access modifiers, while  this is non crucial, it makes for inconsistency within codebase and also goes against PSR2 rules

### Describe Possible Solution
I tried removing the exclusion and ran into tonnes of errors with PHPCS, will recommend that we create an Issue(Beginner friendly) where files having the errors will be fixed incrementally until we are able to reach zero errors, then we can remove this exclusion

@bradymiller If this is something we are willing to do, I can go ahead and create the sub issue with description of files involved and how  the issue can be solved. We can also solicit for beginners to give it a try through our various channels(Slack, Telegram, maybe Twitter)

**Comment by prondubuisi** [comment]
As an aside, If PHPCS had a baseline feature, this fix would have been easier though, looks like there is a discussion to that effect https://github.com/squizlabs/PHP_CodeSniffer/issues/2543

**Comment by bradymiller** [comment]
I've been forcing this on functions that get into the src/ directory (ie. PSR4 directory). Just missed it in the code review where public was removed on a couple functions. The problem is all the legacy classes don't follow this and it's not super simple what to do for each class. Goal is to migrate the classes (and legacy libraries) over to PSR4 over time, like for example this one was recently: https://github.com/openemr/openemr/pull/3180
(note on that PR that figuring out the scope of variables and functions is not entirely straightforward)
This PR is part of a longstanding goal to migrate legacy classes/libraries to modern PSR4 classes.

Something we could consider is doing a separate PHPCS run on code in the src/ directory that is much more strict in terms of PSR2/PSR12 to keep that code modern and avoid things like forgetting scope.
