### ISSUE TITLE
BUG URGENT: PHP notice : URGENT fill the error log with notices (HELP) server crashes

### ISSUE THREAD

**Issue by sharonco-matrix** [openemr/openemr#344]
**BE CAREFUL : REPRODUCING TH BUG FILLS THE APACHE ERROR LOGS AND KILLS THE SERVER**

Question 
 When adding a recurrent appointment something like this is saved in the database:

**a:6:{s:17:"event_repeat_freq";s:1:"4";s:22:"event_repeat_freq_type";s:1:"6";s:19:"event_repeat_on_num";s:1:"1";s:19:"event_repeat_on_day";s:1:"0";s:20:"event_repeat_on_freq";s:1:"0";s:6:"exdate";s:0:"";}'**

If i delete the event and choose only this occurrence this is saved in the database

**pc_recurrspec = 'a:1:{s:6:"exdate";s:8:"20161114";}'**

**If you try to enter this patient file the apache error log will fill the hard drive and crash the server:**

PHP Notice: Only variable reference should be returned by reference in encounter_events.inc.php on line 374

To fix this we can add a validation in the fucntion __increment:
if($t == REPEAT_EVERY_DAY **&& !is_null($t)**) {
        return date('Y-m-d',mktime(0,0,0,$m,($d+$f),$y));

But it may fall somewhere else. So maybe the real fix is to save all the recurrency there or to exit from the function if $t and $f are null??

**STR: CAUTION : IT WILL KILL THE SERVER 
The logs will be filled until no space left, so apache should be restarted and the apache/error.log removed**

Add this line to the DB with the correct pid, and then just click on the patient from the patient list to try to display the patient file

Row in DB:
INSERT INTO `openemr_postcalendar_events` (`pc_eid`, `pc_catid`, `pc_multiple`, `pc_aid`, `pc_pid`, `pc_title`, `pc_time`, `pc_hometext`, `pc_comments`, `pc_counter`, `pc_topic`, `pc_informant`, `pc_eventDate`, `pc_endDate`, `pc_duration`, `pc_recurrtype`, `pc_recurrspec`, `pc_recurrfreq`, `pc_startTime`, `pc_endTime`, `pc_alldayevent`, `pc_location`, `pc_conttel`, `pc_contname`, `pc_contemail`, `pc_website`, `pc_fee`, `pc_eventstatus`, `pc_sharing`, `pc_language`, `pc_apptstatus`, `pc_prefcatid`, `pc_facility`, `pc_sendalertsms`, `pc_sendalertemail`, `pc_billing_location`, `pc_room`) VALUES
(143, 20, 0, NULL, '1', 'תרופה', '2016-11-14 13:17:22', '', 0, 0, 1, '1', '2016-11-14', '2016-11-30', 900, 1, 'a:1:{s:6:"exdate";s:8:"20161114";}', 0, '13:00:00', '13:15:00', 0, 'a:6:{s:14:"event_location";s:0:"";s:13:"event_street1";s:0:"";s:13:"event_street2";s:0:"";s:10:"event_city";s:0:"";s:11:"event_state";s:0:"";s:12:"event_postal";s:0:"";}', NULL, NULL, NULL, NULL, NULL, 1, 1, NULL, '$', 0, 3, 'NO', 'NO', 3, '');

**Comment by bradymiller** [comment]
Sounds like we need @epsdky to come in and rescue us on this particularly nasty bug.

**Comment by epsdky** [comment]
Hello Brady and Sharon,

I cannot reproduce this. I set an rt3 appt with "We" option, saved, reopened and deleted with "Current" selected. Sharon, were you using a fresh test install or one that was previously worked on?

**Comment by bradymiller** [comment]
Hi @epsdky and @sharonco-matrix ,
It looks like the issue is a PHP Notice, so it could also be possible that epsdky does not have php notices turned on in php logging.
-brady

**Comment by sharonco-matrix** [comment]
@epsdky do you have php notices turned on?

**Comment by sharonco-matrix** [comment]
@epsdky @bradymiller Any news on this... its a critical bug... :)

**Comment by epsdky** [comment]
I am using OpenEMR code from this week (latest rt3 code) (with PHP Notices) and still cannot reproduce the second seriously eroded recurrspec with exdate that does not correspond to any of the original appt dates.

I selected 14-11-2016 on calendar set an rt3 appt with "We" (event_repeat_freq = "4" and event_repeat_freq_type = "6") save then select following Wednesday open appt and delete with "Current". Is this what you are doing?

(SQL line 7 is mostly backwards)

**Comment by bradymiller** [comment]
@epsdky and @sharonco-matrix ,
What PHP versions are you using?

**Comment by epsdky** [comment]
I have PHP 5.6

**Comment by epsdky** [comment]
If the persistent appt date bug is reinstated in the rt3 code then it is possible to set up an rt3 appt with "We", 2016-11-14 for eventDate and 20161114 for exdate however no erosion of recurrspec.

1 Set an rt3 appt on 14-11-2016 with "Mo" and "We"
2 Re-open and deselect "Mo", save
3 Delete selecting "Current"

**Comment by shachar058** [comment]
@epsdky @bradymiller @sharonco-matrix 
Hey all,
So I did some major research on this and finally found the scenario in which the bug occurs:

When multiple-providers global is enabled, the user can create an event (appointment) without choosing a provider. (This is not possible when multiple provider isn't enabled because it's a select box and a provider is always chosen).

Steps to reproduce:
-enable multiple providers in globals
-create a recurrence (doesn't matter which one, I went with every day) WITHOUT choosing a provider
-click on one of the events created
-delete only 'current' event

The reason for the bug is this line of code: (add_edit_event.php:700)
`$origEvent = sqlQuery("SELECT pc_recurrspec FROM openemr_postcalendar_events ".
                        " WHERE pc_aid = ? AND pc_multiple=?", array($provider,$row['pc_multiple']) );`
When no provider was chosen we're querying for 'pc_aid = null' and which of course returns false because for null we need to use IS and not equal sign.
So $origEvent is false and then the json that's built contains only the exdate... 

My solution for this is to add:
`   
                    if(!$origEvent){
                        $origEvent = sqlQuery("SELECT pc_recurrspec FROM openemr_postcalendar_events ".
                            " WHERE pc_aid is NULL AND pc_multiple=?", array($row['pc_multiple']) );
                    }
`

This seems like the simplest way.

My pull request for this: 
[https://github.com/openemr/openemr/pull/384](https://github.com/openemr/openemr/pull/384)

Would like to hear your thoughts on this.

Thanks,
shachar

**Comment by sunsetsystems** [comment]
A simpler way would be to use the null-safe comparison operator "<=>" instead of "=".  See this:
http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html#operator_equal-to

But also pay attention to whether the literal you are comparing with is null or 0.  If 0 then you can use "IFNULL(pc_aid, 0)" instead of "pc_aid".  Either way this fix should be a 1-line change and not a whole new condition.

**Comment by shachar058** [comment]
@sunsetsystems 
 Ok used "<=>", didn't know such an operator existed, its definitely a better solution.
As for the IFNULL I'm not sure how you wanted me to use it (if it's in the WHERE clause it's not good to use it, as it degrades the query performance .
Thanks!

**Comment by shachar058** [comment]
Actually just changing the sql isnt enough. If there is an event without provider it doesn't crash the server any more but causes many bugs when creating several recurrent events for the patient and deleting a current event (probably because the pc_aid is null pc_multiple is 0 in several events).

We need to make validation for choosing provider in multiple providers. This will solve the issue.

**Comment by shachar058** [comment]
Added validation for provider in multiple providers

**Comment by bradymiller** [comment]
Looks good. Just brought this into the codebase. Thanks for providing this critical fix! -brady

**Comment by stephenwaite** [comment]
hi Brady, it seems like this shouldn't be listed in the to-do section since it's been closed.  Maybe it's a flaw with the github ux?

**Comment by bradymiller** [comment]
@stephen-smith ,
Removed from the TODO in the Projects UI (that UI requires manually moving around of slides).

**Comment by stephenwaite** [comment]
thanks Brady
