### ISSUE TITLE
Fix Patient Portal Login Being Broken

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3481]
### Describe the bug

The patient portal currently has this issue where every so often it doesn't allow you to login at all and doesn't log it or give any reason why it is not working in php or the EMR logs (and am using the correct credentials as well). This was discovered while working on the patient portal RTL support. Since I don't know how this bug is happening, I need the community to help me out here. The login system for the portal is pretty jank at the moment so perhaps reinventing it might help.

**Comment by bradymiller** [comment]
I haven't noted this in my recent testing of the portal. Will try it out couple more times. When it happens, are you seeing any entries in the sql `logs` table (look at the `comments` sql column).

**Comment by tywrenn** [comment]
@bradymiller I'll have to encounter the bug again to test that out but I can tell you though there are no logs that pull up in the log viewer as well as php when I tested it.

**Comment by sjpadgett** [comment]
> The login system for the portal is pretty jank at the moment so perhaps reinventing it might help.

There is a lot that happens with portal security and reinventing is not an option!
I've just retested the current v5.0.3 and v5.0.2 master with no issues noted.
Beware that portal sessions and openemr sessions are completely different. This is by design so, running an openemr instance and a portal instance from the same user agent ie FF/FF can and will cause unpredictable results.

Brady's last session management update has help w/security but  normal portal workflow should not include running openemr/portal within same user agent regardless if in different tab or window!

However both New Documents send to review and Profile edit are broken.
![image](https://user-images.githubusercontent.com/1859985/81191066-9536af00-8f86-11ea-9721-c6e10bf4574a.png)

Unsure about 5.0.2 at the moment! 
I'll pull down latest RTL PR and test with it!

**Comment by sjpadgett** [comment]
Maybe this will have something to do with issue:

[06-May-2020 12:11:33 America/New_York] PHP Fatal error:  require_once(): Failed opening required 'C:/xampp/htdocs/openemr-rtl/library/authentication/common_operations.php' (include_path='C:\xampp\htdocs\openemr-rtl\vendor/pear/pear_exception;C:\xampp\htdocs\openemr-rtl\vendor/pear/console_getopt;C:\xampp\htdocs\openemr-rtl\vendor/pear/pear-core-minimal/src;C:\xampp\htdocs\openemr-rtl\vendor/pear/archive_tar;.;\xampp\php\PEAR') in C:\xampp\htdocs\openemr-rtl\portal\account\account.lib.php on line 135

I still have not seen any problem with login or resets etc.

**Comment by tywrenn** [comment]
Currently running Ubuntu 18.04.4 LTS btw

**Comment by tywrenn** [comment]
This is still an issue and 5.0.2 actually has an issue where sometimes you have to attempt to login twice before logging in which has been bothering the clinic I work for.
