### ISSUE TITLE
`fhir/Patient` FHIR endpoint not working

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3510]
`fhir/Patient` FHIR endpoint not working with following error:
```[Wed May 13 08:52:41.019313 2020] [php7:error] [pid 619] [client 172.20.0.1:39168] PHP Fatal error:  Uncaught Error: Call to undefined method OpenEMR\\Services\\PatientService::setPid() in /var/www/localhost/htdocs/openemr/src/Services/FHIR/FhirPatientService.php:131\nStack trace:\n#0 /var/www/localhost/htdocs/openemr/src/RestControllers/FHIR/FhirPatientRestController.php(31): OpenEMR\\Services\\FHIR\\FhirPatientService->setId(NULL)\n#1 /var/www/localhost/htdocs/openemr/_rest_routes.inc.php(370): OpenEMR\\RestControllers\\FHIR\\FhirPatientRestController->__construct(NULL)\n#2 [internal function]: {closure}()\n#3 /var/www/localhost/htdocs/openemr/src/Common/Http/HttpRestRouteHandler.php(32): call_user_func_array(Object(Closure), Array)\n#4 /var/www/localhost/htdocs/openemr/apis/dispatch.php(151): OpenEMR\\Common\\Http\\HttpRestRouteHandler::dispatch(Array, '/fhir/Patient', 'GET')\n#5 {main}\n  thrown in /var/www/localhost/htdocs/openemr/src/Services/FHIR/FhirPatientService.php on line 131```

**Comment by yashrajbothra** [comment]
Hey @dixonwhitmire Sir, Will your next PR will cover this issue?

**Comment by dixonwhitmire** [comment]
@yashrajbothra @bradymiller - Yep! I'll probably have a PR or two to address this. I just want to limit the scope of changes, rework, and make it easier to review. 

We will still need to determine how FHIR Resource ids and versions are supported before the endpoints are viable for integration with other systems.

**Comment by yashrajbothra** [comment]
I am a little confused here! Which version are you talking about https://www.hl7.org/fhir/resource.html#versions

**Comment by dixonwhitmire** [comment]
Hi @yashrajbothra Hopefully I'm not conflating things here or making it confusing. In regards to the "version" I am referring to the version id which is conveyed in the Resource's [meta element](https://www.hl7.org/fhir/resource.html#resource). I have also attached an example for reference
[fhir-patient.json.zip](https://github.com/openemr/openemr/files/4623182/fhir-patient.json.zip)

In order to have a "complete" FHIR implementation and support integration with other FHIR systems, OpenEMR will need to define how the resource id and the version are tracked within the OpenEMR system/database. So, I was pointing out that while I can definitely get the endpoint operational, these larger questions will need to be answered before integrating with other systems.

Also, if you need a lightweight way to test FHIR transactions you can take a look at the [IBM FHIR Server)(https://hub.docker.com/r/ibmcom/ibm-fhir-server) docker image. 

DIsclaimer: I am an IBM employee so I'm more familar with our offering. There are projects that support running the [HAPI server](https://github.com/hms-dbmi/hapi-fhir-docker) in a docker container, if that's your preference.

Thanks!

**Comment by sjpadgett** [comment]
The resource version will always be 1 in openemr. We don't track updated record versions so any history search will always result in the current version of the resource. Or am I missing something?

**Comment by dixonwhitmire** [comment]
Thanks @sjpadgett! - the only other use-case I can think if is if you wanted to track the current version number in a server that you are integrating with. There may not be much value in doing that as you could just query the server and see all of the version history anyway.

**Comment by sjpadgett** [comment]
> DIsclaimer: I am an IBM employee

Well Dixon, we all have our crosses to carry so, welcome anyway.:) Kidding of course where my sense of humor can be convoluted at times but, I get it.:)


> track the current version number in a server that you are integrating with

Yeah that will depend on our client I guess. Which once you get that going, I fully intend on jumping in and helping if you want...
Right now I have authentication weighing heavy as it is so important to our API before we get to far along in development. Especially auth permissions. I am leaning towards using OpenId Connect as it will cover both FHIR and mobile as a more common workflow. I believe this will also aid in supporting Smart on FHIR but, i'm not totally clear on that though.

**Comment by dixonwhitmire** [comment]
@sjpadgett Cool!

I haven't implemented a "SMART on FHIR" app, but my understanding is that a good "SMART" framework includes OpenID connect/OAuth2 with it to authenticate you within the EMR/EHR's "context". Of course I'm sure there is some configuration and integration that's required to get that to work, unless there is an "easy" button 😄

**Comment by adunsulag** [comment]
@dixonwhitmire from my reading of SMART on FHIR that is correct.

**Comment by rhausam** [comment]
> The resource version will always be 1 in openemr. We don't track updated record versions so any history search will always result in the current version of the resource.

Presumably this means that each create or "update" results in a new record?  If that's the case, then I agree it seems that the resource version will always be 1.

**Comment by dixonwhitmire** [comment]
Hi @rhausam - the intent, if I'm not mistaken, is that OpenEMR will not support resource versioning. @sjpadgett or @bradymiller can chime in here for clarification if I am incorrect. With that in mind I believe we were just returning a version of "1" at the moment since OpenEMR's implementation does not support versioning.

It may be more appropriate to omit the version field, since it's not meaningful,  and reflect that versioning is not supported in the system's capability statement.
