### ISSUE TITLE
bug setup script (layout)

### ISSUE THREAD

**Issue by zerai** [openemr/openemr#3537]
### Describe the bug
Setup script without bootstrap layout files, 
error 404 for all required files (7 file css/js)

![Schermata del 2020-05-20 11-20-30](https://user-images.githubusercontent.com/2405279/82429727-ac989080-9a8c-11ea-9024-3f2c1c47a628.png)

### To Reproduce

1. git clone https://github.com/openemr/openemr.git -b v5_0_2_2
2. change directory
3. docker-compose docker-compose.yml up

### Client configuration

- docker image: last openemr/flex digest: sha256:52c91d606d52e30ab1a4566c3581105bfd0e5a8e283ec5fbf40f040bdcb50c2b
- Browser: chrome/firefox
- OpenEMR version: v5_0_2_2
- Operating system: ubuntu 18.*

**Comment by stephenwaite** [comment]
hi @zerai , think @bradymiller just fixed this
https://github.com/openemr/openemr/pull/3483

**Comment by bradymiller** [comment]
hi @zerai ,
Alpine 3.10 decided to update to a nodejs version midstream that has caused weird permission issues in the build process for the openemr flex docker series, so the build is breaking here (as an aside alpine 3.11 also does this, which was fixed by bringing in a more recent nodejs version from the alpine edge tree). The fix here would to instead use the openemr:flex-3.9 image in that docker-compose.yml script.

**Comment by bradymiller** [comment]
Actually, above is the second reason it won't work if try openemr:flex-3.10 . The current openemr:flex image is based on alpine 3.11 (openemr:flex-3.11) which is using a nodejs version that is not compatible with 5.0.2 build process.
