### ISSUE TITLE
Consider storing uuid in byte format rather than string format

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3546]
@stephenwaite brought up a good point with recent uuid support to consider storing byte format of uuid instead of the string format since it's smaller and will be more efficient when used as keys. Been looking into this:
https://uuid.ramsey.dev/en/latest/database.html#storing-as-bytes

Since we are just at the beginning of uuid support, this is definitely time to make this critical decision (and I could fix the current implementation in patient_data to support this, if needed). thoughts?

**Comment by bradymiller** [comment]
Also definitely should be using char(36) (or char(16) if got with bytes) instead of varchar, so will at least plan to make that change.

**Comment by stephenwaite** [comment]
nice research @bradymiller , would this need an `sql_version` bump? or because you're just altering the table it's not necessary?

**Comment by dixonwhitmire** [comment]
I took a look to see what support if any MySQL 8 has for UUIDs. The MySQL team added some [convenience functions](https://mysqlserverteam.com/mysql-8-0-uuid-support/) for dealing with a UUID v1 but doesn't support any UUID version as a datatype.

Looks like MariaDB is contemplating a [UUID datatype](https://jira.mariadb.org/browse/MDEV-4958) as well.

Of course there's always [Postgres](https://www.postgresql.org/docs/9.1/datatype-uuid.html)! :smile:, but even here the db will store a uuid and won't generate it.

From an integration point of view it would have been quite nice if the db provided a bi-directional conversion function from "uuid" -> binary, since it's easy to plug into SQL statements and keep all of the data type handling in the data tier.

**Comment by bradymiller** [comment]
@stephenwaite ,
Gonna do the sql upgrade stuff on subsequent commit (rushing this and having the old varchar/char won't break anything), which will basically involve dropping the pertinent table/columns and redoing the uuid thing for the patient_data table if they don't have binary(16).

**Comment by bradymiller** [comment]
@dixonwhitmire ,
Yep, we are getting no help on this from mysql/mariadb. Also will mean that when/if we go to using these uuid's as primary keys, we will need to create a uuid via php on every insert :)

**Comment by bradymiller** [comment]
It's in codebase. Next step is the upgrade piece for the folks that brought in the varchar/char into their instance over last 3 days (note the change is not breaking for these folks, but will be very inefficient in the distant future).

**Comment by bradymiller** [comment]
Above post plan was completed awhile ago (forgot to close this issue at that time).
