### ISSUE TITLE
GACL project pages refine and refactor

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3594]
### Describe the bug

According to this https://github.com/openemr/openemr/pull/3572#discussion_r434041602, the in `/gac` directory pages have a lot of pages that need to refactor and change to the HTML5 standard.

**Comment by stu01509** [comment]
Hi @bradymiller and @tywrenn 

Can you help me check and list which pages can refine and refactor?

**Comment by bradymiller** [comment]
oh goodness, I'd probably make this a bonus project as part of your gsoc project. Meaning would only work on this at the end if you run out of things to do (very unlikely :) ). I say this because it would involve a huge amount of work for very minimal gain (since the gacl gui only gets minimal use by users).

**Comment by tywrenn** [comment]
I agree. I might fix this cause i'm so good with batch replacements...

**Comment by stu01509** [comment]
So assign this issue to @tywrenn?
