### ISSUE TITLE
What happened to Travis????

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3607]
The pass/fail check is mysteriously not showing up on commits and pulls
![image](https://user-images.githubusercontent.com/46497068/83989628-0b775a00-a915-11ea-9c27-97b5ac6ddc4e.png)

**Comment by bradymiller** [comment]
Travis spoke to me during my nap yesterday:

"
I have gone on a partial holiday. I do this sometimes. I am running but not registering on the github commits/PRs because I am showing you how vital I am to your project.
https://travis-ci.org/github/openemr/openemr/pull_requests

When this happens, just pretend I don't exist since easy to fix up things when I decide to come back to your project.

signed,
your best pal, travis

![tenor (5)](https://user-images.githubusercontent.com/278968/83955519-94ed3600-a808-11ea-825a-c6051062608b.gif)
"

**Comment by tywrenn** [comment]
@bradymiller Knew that lol -- just wanted to see when the ghost of Travis CI comes and spooks us all xD

**Comment by tywrenn** [comment]
@bradymiller The ghost of travis CI is back, yet it will scare us all again in the future.

**Comment by tywrenn** [comment]
@bradymiller Travis CI is back to being a ghost again lol

**Comment by bradymiller** [comment]
travis is just lurking under the waters:
https://travis-ci.org/github/openemr/openemr

![tenor (43)](https://user-images.githubusercontent.com/278968/91006372-0af27500-e58e-11ea-9fa3-aaefa73fbb1a.gif)
