### ISSUE TITLE
Docker Load Times = A REALLLL big issue

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3608]
Currently when docker runs it takes like a solid 5 to 10 minutes to even boot up OpenEMR the first time (on a regular laptop). We need to consider decreasing what docker does as this will cause headaches especially in docker-run environments. What we could do is have one version of docker that runs minimally and another that runs the full load and allow easy switching. Any thoughts?

**Comment by bradymiller** [comment]
Majority of build time is composer package collection and theme building. The flex docker does support build and no build, so that could be an option.

**Comment by bradymiller** [comment]
Also, I am assuming you are referring to the easy development docker environment.

**Comment by tywrenn** [comment]
@bradymiller Yeah I'm referring to the one that is run by default. We could create a slim version of it...

**Comment by bradymiller** [comment]
There seems to possibly be confusion regarding the dockers. There are development/testing dockers (flex series) and then production docker series.

The docker-compose.yml in OpenEMR's main directory is a development docker based on flex series for running the easy development docker environment. It needs to build (takes up most of the time) and then also auto-installs. To avoid confusion, plan to remove this docker-compose.yml script from production package builds in the future to prevent folks from running this in a production environment (would not be secure since opens apis/portals by default and turns on xdebug; also has a very unusual number of shared volumes to support ability to test from local repo without contaminating repo).

The production series dockers are already built (and then do an autoinstall on docker load up). So, these definitely load up faster. 5.0.2 is from production codebase. And there is a 5.0.3 which I build every couple weeks from development codebase. Here is an example docker-compose.yml for 5.0.3:
https://gist.github.com/bradymiller/0fcd186130c4ba8ebeb2a7f9a2fc7c81

Hopefully this helps to clarify the potential dockers.

**Comment by bradymiller** [comment]
I'll plan to make a DOCKER_README.md with centralized documentation.

**Comment by bradymiller** [comment]
started docker documentation here:
https://github.com/openemr/openemr/pull/3678

**Comment by tywrenn** [comment]
Closed as this was resolved
