### ISSUE TITLE
Horizontal Scrollbar shows when using EMR

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3611]
### Describe the bug
This bug is still an issue that I haven't been able to fix. A horizontal scrollbar shows when using the EMR on certain devices. This is due to the navbar being too big to show all the content on the screen. To reproduce this, you have to turn up your OS's text scaling (even though this isn't a default state for a browser to have high text scaling, we still want to eliminate all possible scenarios for accessibility reasons).

### Expected behavior
What I want to have happen is that if overflow occurs it either collapses or shows a scrollbar where the navbar is located instead of at the very bottom of the page.

### Client configuration
- Browser: Google Chrome
- Operating system: 20.04 LTS

**Comment by tywrenn** [comment]
@bradymiller Help is required for this item as I dunno how to address this

**Comment by tywrenn** [comment]
I'll have to figure out how to make the text in the navbar stay small even if you set your system settings to large text -- this issue probably won't be able to be fixed yet i'll see what I can do

**Comment by sjpadgett** [comment]
I think @robertdown added the ability to change font and size via globals back when our styling, templates and fonts were all over the place. Now it doesn't appear changing this setting is effective any longer.  The change is overridden in many places causing even more confusion.

First, just because BS4 defaults to 16px font size doesn't mean it makes sense for a font size that large in 90% of our forms. Many of our business forms are busy with view port size at a premium, especially our patient summary header.
Second, our padding and margins are getting way to large.

So, I propose and insist, that we set our default font size back to 14px. Restrict our default font-size selections in globals to 12-16px and fix the feature to work again.

Admins, could use some input on this...

**Comment by tywrenn** [comment]
@sjpadgett Ummm... The base font is already set to 14px by default, just in REM form (14px x 0.0625 = 0.875rem) ([link to line of code here](https://github.com/openemr/openemr/blob/master/interface/themes/oe-styles/style_light.scss#L79))

The real issue is getting rid of the `!important` tag in fonts. Once we get rid of that and override it in globals, everything will resize along with it.

**Comment by tywrenn** [comment]
Another issue is determining which items shouldn't be resized using the globals. Some could break styling if they are resized so we wanna be careful in those departments.
