### ISSUE TITLE
5.0.2 Bug: Portal asks to create new username when changing pass when email only is on

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3613]
The patient portal in 5.0.2 asks for the user to create a new username when they are changing passwords when email substitution for usernames is turned on. This shouldn't be happening when this is turned on.

**Comment by sjpadgett** [comment]
again! there is no setting to turn on email as username. that's a default workflow. user does not have to change username on password change, it's their choice.
if however user is being prompt for a password change when portal is off or allow portal demo choice is off then, that's a problem.

**Comment by tywrenn** [comment]
The issue here is that the user is _forced_ to change their username when "Enforce E-Mail in Portal Log On Dialog" is turned off which confuses the patient into thinking the username is their username they set. If we made it invisible while changing passwords it would be like the username isn't there (even though it is).

**Comment by sjpadgett** [comment]
> "Enforce E-Mail in Portal Log On Dialog"

Should have nothing to do with username! This only requires that the contact/direct secure email has to be used as additional security during logging on. Last time I tested all this it was working fine but still, i'm not sure its state now.

I'll look it over again tyler...

**Comment by tywrenn** [comment]
![image](https://user-images.githubusercontent.com/46497068/84217755-fcbaaf80-aa9a-11ea-8e9c-1a9e2a9db600.png)
This is where I'm seeing the issue

**Comment by sjpadgett** [comment]
That's right. username needs to be at least 12 chars. Account name is not a username

**Comment by tywrenn** [comment]
Yet the problem is that this does nothing when this option is off (and actually I just saw it bug up my login screen after using this but that's for a different issue request)

**Comment by sjpadgett** [comment]
> It also requires you to enter a new one which will never be used since the email is the username when this option is turned off.

This works as intended. You don't have to create a new username. It is there because we don't know if patient forgot username or password or both. Also does not need to be email for username. New portal patient default to email as username but even then admin can change when setting up account.
Though having New User Name as a label can be confusing so prob will change to populating User Name with current username and rewording label:
![image](https://user-images.githubusercontent.com/1859985/84419892-3d274400-abe7-11ea-81ce-5497541bfb60.png)
 I've tested this a hundred times now so I don't have a clue. The email for login flag has nothing to do with any of this. That flag only says that patient must use their registered email address along with there username and password to login. Not use email as their username!

**Comment by tywrenn** [comment]
@sjpadgett I just figured out what you mean 😂 -- so when the patient is given their credentials for first time setup by the clinic it autofills their email address as the username which sets it as the username (yet they can change that if they want to). Yet if they reset their credentials through the portal itself, it doesn't autofill their email address in the field, requiring them to set the username. So THATS the bug lol

**Comment by sjpadgett** [comment]
The intent was to make the patient retype or change their username on password change. You can also change credentials in portal.
![image](https://user-images.githubusercontent.com/1859985/84424229-c8a3d380-abed-11ea-99be-1b248511cee9.png)
