### ISSUE TITLE
Not Able to send the Gif images from KeyBoard and also from the Gallery. 

### ISSUE THREAD

**Issue by DhirajG** [openemr/openemr#3616]
It's strange I am unable to upload the Gif. It's not giving any error that I can report. Simply it rotates and then stops in case of KeyBoard. 

When I try to upload from the storage the progress bar never moves ahead.  What we are doing is saving the Gif from the assets folder and sending it. The png Stickers worked but not the Gif images

//This is our method to save the file This saves the image and the Gif correctly
           File file = saveFilefrom asset(assets);

Attachment attachment = new Attachment();
        attachment.config.setFilePath(file.getPath());
        attachment.setFile_size((int) file.length());
        if(assets.contains(".gif"))
        attachment.setType(ModelType.attach_giphy);
        else
            attachment.setType(ModelType.attach_image);
        attachment.setAuthor("Assets");
        Log.e(TAG, "onAssetClick: "+attachment.getFile_size()+file.getPath() );
        uploadAttachment(attachment, false, true);

**Comment by tywrenn** [comment]
Not too sure what you are trying to accomplish here...are you trying to attach a gif from something like Google Keyboard and insert it into the EMR? If so that's not compatible with OpenEMR.
If you're trying to upload it through the documents uploader it should go through as long as that isn't a file type in the blacklist/whitelist of OpenEMR. The way you tell if it's blocking it is scrolling to the bottom of the page and it shows a message.

**Comment by tywrenn** [comment]
Closed due to no response
