### ISSUE TITLE
Fix Mime Type Blocked Error Placement (For v6)

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3640]
Since I implemented this in the 5.0.2 I might as well implement this in 6.0.0

@bradymiller Do the changes we patch in 5.0.2 transfer over to 6.0.0 or does that not happen?

**Comment by bradymiller** [comment]
hi @tywrenn , Just let us know whenever you need something cherry-picked from one branch to another. In future, usually better to fix in master/6.0.0, and then just flag us that you want it cherry-picked to rel-502. If it ends up being more complicated (ie, each version has different changes) then best to have 2 separate PRs. I just cherry-picked your 5.0.2 changes into master/6.0.0 :)

**Comment by bradymiller** [comment]
https://github.com/openemr/openemr/commit/25df876079916b184786fe6c87dd6a2ff0694865

**Comment by tywrenn** [comment]
@bradymiller yeah I was gonna create 2 PR's for this and make sure this change was globally patched

**Comment by bradymiller** [comment]
No need to create 2 PR's if something simple and confident the code is going to be the same  (such as this case). Otherwise, when more complicated, then should do 2 PRs.

Also, github has a new permission called Triage that allows somebody to manage issues and PRs (can't bring in PRs though); so can add labels, milestones, etc.
I just gave you Triage permission to the openemr repo, so you won't need to ask me to set tags/milestones etc. :)

**Comment by bradymiller** [comment]
More info on Triage role here:
https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization
