### ISSUE TITLE
Past Encounters and Documents not refreshed when changing patients

### ISSUE THREAD

**Issue by boxlady** [openemr/openemr#3659]
### Describe the bug
When you switch patients the Past Encounters and Documents tab doesn't update, it shows the history from previous patient.  This seems to only apply to 503. Whereas the tab automatically updated when switching patients in 5.0.2.
### To Reproduce
Go to the demo server click on a patient. Check the Past Encounters and Documents tab, take note oh what is written there (Needs to have history to see).  Go to the Patient Finder click on a new patient check the history tab... you'll see the previous patients' history instead of the new patients. 

### Expected behavior
In all previous versions when switching between patients the history was refreshed without having to do anything extra.

**Comment by sjpadgett** [comment]
confirmed

**Comment by boxlady** [comment]
Side question... What is/what does it mean "Priority: Blocking" label?

**Comment by stephenwaite** [comment]
hi @boxlady , very high priority

**Comment by bradymiller** [comment]
I've also been seeing several places where tabs aren't refreshing or redirecting to scripts like they should. Am betting there are several bugs to address in the code that was added to avoid unnecessary refreshing of scripts within tabs (think it was added 1-2 months ago).

Your specific bug is definitely critical since it may lead to confusing patients.
