### ISSUE TITLE
Calendar Design Overhaul

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3661]
This is something that should be done now as it really needs to be updated. In the calendar currently implemented, there are numerous bugs and things that are problematic.

### Current Calendar System Issues
- The design is very unintuitive. To remove an IN block you have to click on the specific day and try to mash on the block to edit it.
- An IN requires an OUT for every time a doctor is in office. We should be using the duration that the person sets as the actual time and get rid of the OUT block.
- You cannot drag a calendar appointment to another day. You have to manually go in and change the date.
- The duration is measured in minutes for each event when it should be showing two time fields (e.g. 4:30pm to 5:30pm with military time support if needed).
- Recurring events are very finicky and sometimes outright disappear if you try deleting one in the series.
- The small month view in the left hand corner is too small.

### Proposed Solution
I suggest we either build off our old system and solve the bugs or create an entirely new calendar system. Since we want doctors to not have issues working with the calendar, this is a pretty high priority.

**Comment by mdsupport** [comment]
@tywrenn Recurring appointments are problematic as the php object is stored in database. That means the status and time get changed for all occurrences. So we run a cron job at night which converts past recurrences into normal appointments and resets the start of recurrence period to next appointment date.

Ideally in today's world we need to set up an interface to something like Zimbra or any decent collaboration solution that can handle scheduling as well as office and patient communications in all forms.

**Comment by tywrenn** [comment]
Btw the calendar module is dated back from 2002 😂😂😂

**Comment by tywrenn** [comment]
Since I have no idea how to fix these issues anyone wanna take this issue?

**Comment by mdsupport** [comment]
@tywrenn Replacing entire system is too big for current dev resources and too risky for practices. Modifying existing screens is a nightmare since it involves smarty. Even a simple table to grid was too complex because of all variations. However a personalized version may be easier to build from scratch. It could be something like a new UI for clinicians (so a single provider) that can be pulled up on their smartphones or tablets showing 1 or 2 days of appointments. That limits items to be displayed and BS will take care of max 12 column grid with may be max 2 overlapping appointments. Appointments function already has all filters. It can be displayed with "app" functionality and could provide ability to schedule next appointment using simple inline form in dropdown.

**Comment by tywrenn** [comment]
@mdsupport Maybe replacing it won't work -- yet it doesn't mean you can't overhaul the current system. I'm under the belief that nothing is impossible and in pull #3710 , I clearly show that overhauling the system is possible.
