### ISSUE TITLE
Setup fails on setting up access controls

### ISSUE THREAD

**Issue by sunsetsystems** [openemr/openemr#3741]
### Describe the bug

Setup ends with an error that it was unable to set up access controls. The web server log shows this:

[Tue Jul 14 08:15:05.682912 2020] [php7:notice] [pid 615] [client 127.0.0.1:47306] PHP custom error:
    from gacl src/Gacl/Gacl.php - Unable to set up UTF8 encoding with mysql database
    Access denied for user &#039;openemr&#039;@&#039;localhost&#039; (using password: YES)
[Tue Jul 14 08:15:05.682936 2020] [php7:notice] [pid 615] [client 127.0.0.1:47306] Unable to set strict sql setting:
    Access denied for user &#039;openemr&#039;@&#039;localhost&#039; (using password: YES)

"openemr" was NOT the chosen database name.

![Screenshot at 2020-07-14 09-04-06](https://user-images.githubusercontent.com/386879/87362152-2b073f80-c5b1-11ea-9d9a-bae130ae981f.png)
### To Reproduce

Install OpenEMR from master branch, having it create a new database. Specify database / login name / password that are not the defaults.

If you first modify sites/default/sqlconf.php to contain the desired database / login name / password, the problem does not occur.

### Expected behavior

No error.

### Client configuration

- Browser:
- OpenEMR version: from current master branch
- Operating system: Linux Mint 19

**Comment by sunsetsystems** [comment]
By the way if you wonder why my log file entries are dated tomorrow, I'm in Australia now. :)

**Comment by bradymiller** [comment]
hi @sunsetsystems from the future :)

That's really odd. I actually had that same issue when working on this, which was fixed with the following line:
https://github.com/openemr/openemr/blob/master/setup.php#L1158
(used a require instead of a require_once to force bringing in the credentials again after they got rewritten)

I am pretty sure you didn't change that line, but if you happened to change it to require_once, then change it back :)

I'll plan to test this again when I get to a computer this evening.

**Comment by sunsetsystems** [comment]
@bradymiller Hmm I do see that line in setup.php on my test site. I built it from the current master branch with no changes. Weird.

**Comment by sunsetsystems** [comment]
By the way this is PHP 7.2. I wonder if there's a bug with mixing require_once and require for the same module.

**Comment by bradymiller** [comment]
Just tested this to work on PHP 7.2.24. Very strange stuff. After the script breaks, does your sqlconf.php contain the new settings? (if not, then maybe a write issue, and if not that, then I wonder is some sort of buffer issue where it doesn't write until maybe the script is done (kind of like html output happens); just a wild guess).

**Comment by sunsetsystems** [comment]
Hi @bradymiller yes sqlconf.php does contain the new auth settings after the failure.

**Comment by sunsetsystems** [comment]
Just tried it on a hosted VPS with Ubuntu 18.04.4 and a pre-created database, and it fails there too in exactly the same way.

**Comment by sunsetsystems** [comment]
Can give you access if that helps.

**Comment by bradymiller** [comment]
I'll see if can spin up a ubuntu 18.04 docker to try this out on. agree that there's probably some weirdness with using require_once and require in some environments.

**Comment by sunsetsystems** [comment]
Think I have a solution. In Installer.class.php, function, function write_configuration_file(), add this after the fclose():

    opcache_invalidate($this->conffile, true);

**Comment by bradymiller** [comment]
neat stuff. does it work? If so, rec checking to ensure `function_exists('opcache_invalidate')` before running it since it looks like this is part of optimization module that is not always installed. For example, we are not installing this package in the alpine builds (https://pkgs.alpinelinux.org/package/edge/community/x86/php7-opcache).
quick reference I looked at regarding opcache here:
https://www.tecmint.com/install-opcache-in-centos-7/

If it works for you, can you push a PR for it?

**Comment by sunsetsystems** [comment]
Hi @bradymiller yes it worked for me. I'll make a PR as you suggest. Thanks.
