### ISSUE TITLE
Edit Medical Issue > "Delete" > "No, Cancel" doesn't cancel

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#381]
Version Number: v5.0.1-dev
Browser Firefox 42

First identify the medical issue you wish to edit:
![1](https://cloud.githubusercontent.com/assets/1715206/21077364/513a330a-bf17-11e6-9dfe-faedae66fde2.png)

Click Delete button:
![2](https://cloud.githubusercontent.com/assets/1715206/21077365/513b4d62-bf17-11e6-92e7-a295a78e25f2.png)

Change mind, click No Cancel button:
![3](https://cloud.githubusercontent.com/assets/1715206/21077366/513bcaf8-bf17-11e6-8788-036c389f43c5.png)

The modal doesn't close. Notice the fancybox issue in devtools:
![4](https://cloud.githubusercontent.com/assets/1715206/21077370/5f9de252-bf17-11e6-83f5-c4d4fe512714.png)

This is small bug because the "X" button works just fine.

**Comment by bradymiller** [comment]
Another helpful piece of information would be if this works(or doesn't work) on the frames layout.

**Comment by MatthewVita** [comment]
@bradymiller It works in the frames layout.

Unrelated: Can the frames layout be removed from OpenEMR in version 5? It is inferior to tabs from a UX perspective and seems like folks will be able to "ramp up" to it pretty quickly? Or am I missing something?

**Comment by bradymiller** [comment]
@MatthewVita ,
There are still folks out there that prefer it; for example, Matrix (working for dept health in Israel) is still using it since there is still work needed for tabs to support right to left. And at this point, it requires minimal effort to support both (thanks to Kevin's artful approach on the tabs ui core). I do predict that over time(and likely not that long), that it will get less and less use and will get phased out.

**Comment by mdsupport** [comment]
Could #383 be related to this?

**Comment by bradymiller** [comment]
Thanks to @sjpadgett , this bug no longer exists. Will close this issue.
