### ISSUE TITLE
CCR report generate is broken

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#3831]
after selecting a person and then choosing `Report` from their dashboard
click on Generate either with or without `Use Date Range`
![Screenshot from 2020-08-09 12-23-16](https://user-images.githubusercontent.com/5618372/89736931-34ae8680-da3b-11ea-9034-0b2fa98bea4d.png)
If you click `Download` the report will be generated.
Then go try to import it into their documents in the CCR folder which leads to a whitescreen.
Here's the log from these actions.
[ccr.log](https://github.com/openemr/openemr/files/5048038/ccr.log)

**Comment by stephenwaite** [comment]
if you take out this requirement it will load a default stylesheet but pretty sure it's going to be okay to remove `CCR` from our options since things have moved to `CCD`

![Screenshot from 2020-08-09 17-45-37](https://user-images.githubusercontent.com/5618372/89742460-24f96700-da68-11ea-994f-e491ed4a9031.png)

**Comment by sjpadgett** [comment]
@stephenwaite I believe you're correct.  Instead of removing we prob need to convert to send CCDA instead of relying on CCM.
fyi:
Electronic Transmission of Summary of Care Documents
For the EHR Incentive Programs in 2017, the HIE measure simply states that a provider is required to create the
summary of care records using CEHRT and to transmit the summary of care record electronically. The intent is to
promote and facilitate a wide range of options for the transmission of an electronic summary of care document.
The initiating provider must send a C–CDA document that the receiving provider would be capable of
electronically incorporating as a C–CDA on the receiving end. In other words, if a provider sends a C–CDA and
the receiving provider converts the C–CDA into a pdf or a fax or some other format, the sending provider may
still count the transition or referral in the numerator. If the sending provider converts the file to a format the
receiving provider could not electronically receive and incorporate as a C–CDA, the initiating provider may not
count the transition in their numerator. The provider may use a third party to send the summary of care record,
but it is not required.

**Comment by sjpadgett** [comment]
however, if you think this needs to be fixed, I can.

**Comment by stephenwaite** [comment]
thank you @sjpadgett , will close this and let you handle in #3835
