### ISSUE TITLE
BS4 font size.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#3838]
### Describe the bug
Not a bug per se but, it bugs me!
I have no idea why the authors at twitter decided to increase the default font size from 14 to 16px but, for a business application, 14px is more appropriate.

Remembering again, we implement BS mainly to ease responsiveness and styling uniformity . Doesn't mean we are bound by all that is bootstrap.

Having sprawling UI's is annoying with as many interfaces presented to the user as possible, not scrolling and requiring as few interactions(accept business logic) as possible.
This also includes large titles with overspacing.

Many of our UI's originally were designed with this in mind. This is why we have so many inling stylings etc and trying to achieve uniformity is very desirable however, these large UIs are counterintuitive imo. Sometimes we just have to bite the bullet and redesign some of our UI templates and not try to style around that templates original intent. Many times this requires converting the use of using the old pattern of using tables for layouts.

Originally my vision for BS4 was to have a default BS that had adjusted margins, padding and fonts to be more appropriate to our application.

I don't mind the push back but, for me, I can't seem to let this go.:)

**Comment by tywrenn** [comment]
@sjpadgett Your gonna laugh at this. The default font size is set at 14px for OpenEMR lol xD
If part of the text is set to 16px, it's probably from a CSS class.

**Comment by tywrenn** [comment]
If you go to style_light.scss, the line where I change it to 14 pixels is on line 79 and 80. It is represented in REM yet if you convert it back to pixels it's 14 pixels.

**Comment by sjpadgett** [comment]
hmm, not sure if i'll laugh, maybe feel a little foolish.:) but, last time I checked a few UI's, they were 16px! I'll look again.

I see where you've done the change but still, something's off. Why not make change in theme default?
Concerning rem, I recently did a test for a margin conversion from px to rem using the .875 conversion where the replacement for 14px was still larger. It came out to .75. I know, doesn't make sense, but, there you are. I'll test this again.

The point though, everything about our UI is much larger. At least using FF.

**Comment by tywrenn** [comment]
@sjpadgett 1 pixel equals 0.0625rem -- that might be why ur stuck in terms of rem conversions. The reason the change isn't in theme defaults is because these color variables and other stuff that are there go before I invoke Bootstrap into the theme. That way when Bootstrap kicks in it replaces BS4 variables with the ones that I set on compilation. It's a bit complex but it minimizes the amount of code I have to edit.
As far as the UI size goes, some areas were made larger to reduce clutter and to allow mobile devices to utilize the EMR more.

**Comment by sjpadgett** [comment]
> some areas were made larger to reduce clutter and to allow mobile devices to utilize the EMR more

Making UI larger to reduce clutter is where we sort of part ways. And how does making a UI larger help mobile? Styling to tablet is one thing but trying to completely be mobile friendly at the cost of desktop UX, is another. For mobile, we should gravitate to using mobile client apps for more specific user chores(thus all the work on API's).

I know this is hard and don't get me wrong, you're doing a great job. It's the size of our interfaces that are really bugging me.

I get that the mantra is, style to mobile first but, that lends itself well for single page, single goal oriented web apps where, the diversity of an EMR business app is a different story.

**Comment by sjpadgett** [comment]
yep, looks like we have a mix of font-sizes going on between .75, .875 and 1rem. Looks like theme builder tries to set to .75(this is due to globals default font size and seems to be overridden most everywhere i've checked so, why have it!) then we have an intermixing of sizes throughout. eg, why is a text class set to .9rem? Is it meant to be a sub title perhaps? Also in places i've noted BS default override theme default.

You could go nuts with some of this stuff....

**Comment by bradymiller** [comment]
Dumb question over here. In the future when codebase is fully bs4 and scss driven, would it be straightforward to make for example a compact style with reduced margins/padding?

**Comment by sjpadgett** [comment]
Possibly but the whole footprint of the UI has changed considerably. 
I think much of it is if we can get font-size smaller and if we're going to keep the global font selections, we honor those in our themes. Otherwise, i'm for removing because allowing user to enlarge say font-size, then all the padding etc would need to adjust also.

**Comment by tywrenn** [comment]
@bradymiller @sjpadgett Since I basically can tell Bootstrap how to format it's margins/padding/font size/colors/and more using SCSS, what I think I should do is replace theme builder with a few themes that have a more compact design.
The way this will work is if you are using BS4's margin/padding classes, I can shrink those in the themes. I can also remove the border radius around buttons, make buttons smaller, make font sizes smaller, and other things.

As far as general font sizes go, in my opinion, we tend to change the font size too much on a lot of OpenEMR stuff. What we should do instead of using the font-size attribute a billion times is working with the base font size of 14 pixels and only scaling up when absolutely necessary.

**Comment by sjpadgett** [comment]
Thanks Tyler, sounds like a good plan. Let me know if I can help. umm, a little.:)
