### ISSUE TITLE
Eligibility broken

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#3848]
### Describe the bug
[12-Aug-2020 18:05:06 America/New_York] PHP Fatal error:  Uncaught Error: Class 'OpenEMR\Billing\edih_271_codes' not found in C:\xampp\htdocs\openemr\src\Billing\EDI270.php:917
### To Reproduce
Run Elig from Insurance

**Comment by bradymiller** [comment]
Try to throw a `\` in front of the new class call (in phpstorm it seems to show the function exists). Not sure why that is needed there, though.

**Comment by bradymiller** [comment]
Actually, a better way is to just place this in the `use` block at top:
```
use edih_271_codes;
```

**Comment by sjpadgett** [comment]
thanks @bradymiller  that fix that but, why is it my stuff always gets broken.  I beg everyone to please turn on all modules, features etc when testing or doing mods. This includes turning on User Debug so one gets an immediate JS or PHP error to note.
![image](https://user-images.githubusercontent.com/1859985/90178385-d86c9f00-dd79-11ea-84f0-856d21ee2e43.png)

**Comment by bradymiller** [comment]
hi @sjpadgett ,

I generally blame travis for this kind of stuff, which is why it's so great to have a project antagonist like travis in the project
(sure it's irrational, illogical, and displaced blame, but blame nonetheless :) )

On this front, have been adding bunch of devtools to the dev environment to make testing of the less straightforward things easier. Agree, though, we gotta keep in mind systematic testing on new code.

On the User Debug, we could add that global to the easy development environment, which would then turn it on automatically for devs that use it:
https://github.com/openemr/openemr/blob/master/docker-compose.yml#L56-L67

If you want it there, just let me know, (and will also put it in the insane dev environment for the one dev, me, that actually uses that)

**Comment by sjpadgett** [comment]
This turned out to be just a flat diff between BS3/4. The styles were perfectly fine and that button should have been overwritten by returned html but nooo, lets aggravate Jerry.:) Not supposed to be shown if no report therefore shouldn't be able to click...

Travis is my scapegoat if no one else happens to be around!

User Debug: I'd turn it on. especially now it is mostly available in all our script. it is convenient as errors will confront you. This is how I catch many errors I report or fix..... next PR i'll do unless you do first..

**Comment by sjpadgett** [comment]
I gotta quit clicking on stuff:)

**Comment by bradymiller** [comment]
![tenor (42)](https://user-images.githubusercontent.com/278968/90215920-08d02f80-ddb2-11ea-9426-c48db9f2e7b7.gif)

yep, very dangerous. Next thing you know, 500 bug fixes later, it's 2021
