### ISSUE TITLE
Why file are stored in couchdb as a document directly and not as an attachement to a document ?

### ISSUE THREAD

**Issue by dummys** [openemr/openemr#3849]
Hi, let me explain what I'm talking about. When you look how the file are stored in couchdb it is at the form:

```json
 "_id": "testtif134060_2020-_06-_17_09_27_30",
  "_rev": "1-aad64eb052196a021cf738e51a039b75",
  "pid": "13406",
  "encounter": 0,
  "mimetype": "image/tiff",
  "data": "\"SUkqAAgAA"
}
```
But this is tedious in case of a problem to look at the file uploaded etc. It exist a function of attachement in couchdb, where the goal is to attach to a document a file.

For example, we create a document, with the name as the name of the file and then we can upload it. Thus when we want to debug something, we can simply connect to the fauxton interface, then search for the file name and then use the "View Attachement" options rather than directly saving the file as a document with data.

What did you think about this change ?

**Comment by bradymiller** [comment]
hi @dummys ,

There have been recent changes to this. Metadata is no longer stored in couchdb (since it was just redundant to data in the documents sql table entry representing it), the filename is now a uuid, and the file is encrypted (from key stored in OpenEMR's database; thus if the document store is compromised, will just be gibberish :) ).

![image](https://user-images.githubusercontent.com/278968/90220895-f5c35c80-ddbd-11ea-8e0c-264bc04c0ebb.png)

![image](https://user-images.githubusercontent.com/278968/90220912-fcea6a80-ddbd-11ea-8c1e-883d0bd4f2fc.png)

![image](https://user-images.githubusercontent.com/278968/90220946-0f64a400-ddbe-11ea-95f4-5f9d09a18dc9.png)

**Comment by dummys** [comment]
ok I see. Thanks for explanation.

**Comment by dummys** [comment]
@bradymiller we are running in a problem where fiel bigger than 8MB can't be uploaded in couchdb 3.x. WE get a "CouchDB save failed" inside openemr. We tried to bump the max_document_size to 20MB but it still did not work. Interestingly on one of our other instance, which are running with old couchdb 2.x and it was working fine. Any idea on that ?

**Comment by bradymiller** [comment]
@dummys , Anything in the php error log?

**Comment by dummys** [comment]
no unfortunately I get nothing. And inside the couchdb.log I see "undefined POST" with error 413

**Comment by dummys** [comment]
ok I have made the change and now I'm able to save huge files. thanks for the help
