### ISSUE TITLE
Layout data storage

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#388]
Current method of storing "|" delimited strings for layout data makes it's use by external applications difficult if not impossible.  We are planning to switch this to json format.  Would there be any interest in making it standard?

**Comment by sunsetsystems** [comment]
I don't understand "difficult if not impossible" but I do understand the appeal of a standard format.  Make sure UTF-8 is handled (I vaguely recall some issues with that and json_encode).  Also make sure there are no issues with overflowing limited column widths.

**Comment by mdsupport** [comment]
> difficult if not impossible

Restrictions we have repeatedly faced with lbf_data are:

1. External application(s) must be a php application or create a subsystem in php
2. Need to go through options.inc transformation which does not offer model / view separation.
3. Does not allow use of mysql queries on a specific field
4. Does not use advantages of mysql native formats

**Comment by mdsupport** [comment]
Sorry - didn't make clear that the purpose of this is to flag lbf_data in it's current form makes ORM (#357) incomplete/convoluted.

**Comment by sunsetsystems** [comment]
Are you talking about the new support in MySQL for a JSON data type?  That sounds interesting.  Note it's specific to MySQL 5.7.8 and above and we don't want to break compatibility with actively supported Linux distributions.

**Comment by mdsupport** [comment]
That is correct.  Using something as basic as a db built-in data type should be a criteria for development fork.  For us benefits from lower development costs are too attractive.

Will close this thread for now until the community version catches up with platform updates.  
Thx.

**Comment by bradymiller** [comment]
There is already use of storing json in several places (CDR engine reporting results and the newer client side validation module). It is also very nice because of the flexibility in the coding; for example, can add new fields without much work. If this is done in a way that also converted prior versions during upgrade script, then seems like a pertinent modernization project.

**Comment by sunsetsystems** [comment]
In the meantime there's nothing wrong with storing json in a varchar or text string.  There could also be an option to take advantage of the mysql json data type if it's supported.

**Comment by bradymiller** [comment]
They are currently stored as a text. wow on the new json type in mysql(I just looked it up); pretty cool, but agree that is something that would need to wait to use in the future. Out of curiosity, I wonder what happens if try to convert a text to json (if the text is a json object) for future planning.
