### ISSUE TITLE
SQL Error: Too many connections

### ISSUE THREAD

**Issue by dummys** [openemr/openemr#3904]
Hi,
We have something weird. Is it normal that with only one user connected to OpenEMR we get 150 connections to SQL ?

**Comment by stephenwaite** [comment]
hi @dummys , it is normal from my experience, that's why for a multi-setup have this
```
mysql> SHOW GLOBAL VARIABLES LIKE '%max_connections%';
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| max_connections | 5000  |
+-----------------+-------+
1 row in set (0.01 sec)

```

**Comment by dummys** [comment]
ohh ok. So it means for production we need a huge mysql instance at AWS then ? Because max connections is related to ram

**Comment by dummys** [comment]
we are not running multisite, only one.

**Comment by stephenwaite** [comment]
then should prob watch for now and see what your max is, will label this a `bug` and hopefully can get a handle on too many opens

**Comment by dummys** [comment]
yes but to have 5000 connections on AWS, it means running a monster with 48GB of memory. WTF ?

**Comment by stephenwaite** [comment]
my multisite with `5000` is not on AWS, you can probably use something like 500 but would have to monitor during usage to confirm

**Comment by dummys** [comment]
ok but how it is possible to use so much connections ? There is persistent one ?

**Comment by stephenwaite** [comment]
that's why it's labeled a :beetle:

**Comment by dummys** [comment]
Ohhh ok. But nobody see this before ?

**Comment by dummys** [comment]
can you told me how open  connection you had on a production system with like 10 doctors ?

**Comment by stephenwaite** [comment]
usually should max out ~150

**Comment by dummys** [comment]
ok so with an instance with 4GB we should be at 317 connections, it should be ok you think ?

**Comment by sjpadgett** [comment]
Busy body here but, with 10 doctors I don't think you can get by on 4GB! Remember also support staff.
I remember last year I help somebody with a multi site config that was running 20-30 users where we had to bump to 8GB mem.
Also, remember volume space as that will be an ongoing and ever growing headache for you.

Server connections is a bug imo as Stephen pointed out that I may address in my current PR for sql_upgrades. Our problem is that it looks like we rely on server releasing(time out) activity threads as we are not closing connections. A guess!

**Comment by bradymiller** [comment]
I'll have more to post on this later tonight (from work, my github/web
access is limited) since we've thought about this issue several times in
the past. This is related to connection pooling (connections are left
around and reused), which increases performance. We could have an option to
turn this off, which would then make ongoing connections super low (and may
be worth the performance trade off for some folks). I can't look now, but
the demo farm database that houses 40-50 demos (albeit only a couple get
moderate use), i think 300 or so has never been toppled yet.

**Comment by sjpadgett** [comment]
thanks Brady. I didn't know we used connection pooling so i'd leave it alone. Looks like we average 5-6 connections per user.
Besides while OpenEMR runs fine on 4GB for small office, i'd opt for the greater 8GB.
On average an instance will use 1.5-2GB with most of the rest being cached.

**Comment by bradymiller** [comment]
When I have time, I'll make a global to disable pooling just for allowing testing and show folks how to do it. It's not too tough to do (have tested this in past when added the ssl mysql stuff), and it may not get into the codebase, but will then allow profiling to get a clear idea of performance hit.

The max_connections setting in the demo farm has been very stable at 450 (never has run out of connections with this):
https://github.com/openemr/demo_farm_openemr/blob/master/docker/scripts/demoLibrary.source#L158

Note this is super safe, since over the last 30 days, the max concurrent connections has been 160 on the demo farm:
![image](https://user-images.githubusercontent.com/278968/92207376-f8095b80-ee3d-11ea-9204-a568d6b2c5f6.png)

Notably, without pooling, this number drops dramatically to the single digits.

**Comment by zerai** [comment]
Pooling settings is already a global variable [here](https://github.com/openemr/openemr/blob/0833d7d6dcff61a42399295f87b5ca980670642b/interface/globals.php#L299).
I don't think pooling config is the real problem, and it
works when we use doctrine, five entity/table (see the folder src/Entity)
versus all other tables (80? 100? or more table).

Actual state:
1 Gacl [creates](https://github.com/openemr/openemr/blob/0833d7d6dcff61a42399295f87b5ca980670642b/src/Gacl/Gacl.php#L152) e use an own connection. (adodb lib)

 2 There is a separate connection (laminas-db lib) if modules are active.

3 There is a doctrine connection [here](https://github.com/openemr/openemr/blob/0833d7d6dcff61a42399295f87b5ca980670642b/src/Common/Database/Connector.php#L99) for 5 entity. (original modernization process is terminated)

4 There is a separate connection [here](https://github.com/openemr/openemr/blob/0833d7d6dcff61a42399295f87b5ca980670642b/interface/main/calendar/includes/pnAPI.php#L260) (adodb lib) maybe for calendar stuff. 

5 [Here](https://github.com/openemr/openemr/blob/0833d7d6dcff61a42399295f87b5ca980670642b/library/sql.inc#L28) there is the main / most used connection $GLOBALS['adodb']['db'] 

Connection/database management should or could be optimized. IMO

**Comment by mdsupport** [comment]
> Is it normal that with only one user connected to OpenEMR we get 150 connections to SQL ?

If those are active connections working on different queries, that would be one busy user or a legit bug.

If you are an admin looking to fine tune the db operations, you know the connection mechanism. In general balance the small overhead of memory consumed by idle connection with user's ire when they spend few minutes filling the form and emr returns db error of not enough connections.

If the connections are affecting performance and you have small load factor, you could start with reducing the [wait_timeout](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_wait_timeout) at the cost of startup costs of a process.

**Comment by bradymiller** [comment]
hi,

Incorporated a global setting to turn on/off database connection pooling in this PR:
https://github.com/openemr/openemr/pull/3906

Note @zerai that the global setting your pointed to was only for the doctrine connection.

In doing this, I noted that the calendar, laminas, and portal were actually not using pooling in their connection schemes (the PR adds this in so that all the connections are using pooling or all are not). When turning the pooling off, there are basically no sleeping connections created, so this would dramatically decrease connections to only what is actively being opened and used. However, I think I can notice performance difference when pooling is off (but I may be biased and would require profiling to answer performance issue).

**Comment by bradymiller** [comment]
hi @dummys ,
Brought in a global in the above PR that is now in codebase (will be in 6.0.0) to turn off pooling/persistence. But you can see where changes are being made in case you want to try it out on your 5.0.2 instance if that is the direction you want to go. Added this setting to the setting guide with some guidance (links at least):
https://www.open-emr.org/wiki/index.php/Administration_Globals#Enable_Database_Connection_Pooling
