### ISSUE TITLE
Minor Serial Number Issue in External ID

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#4009]
Hello All,

There is a minor sequence issue in the patient list. When we click on arrange by External ID in patient list, after external ID as 1, it shows 10. Actually 10 should be after 9.

Clearly shown in the screenshot below

![pid number issue](https://user-images.githubusercontent.com/1074948/98151661-8d84a280-1ef6-11eb-8f12-e20354ff1120.png)

Kindly see to it if this arrangement can be fixed and it should get arranged by descending order truly.

Thanks
Dr. Arnab Naha

**Comment by arnabnaha** [comment]
any help on this please?

**Comment by arnabnaha** [comment]
hii....
can this be fixed????

**Comment by arnabnaha** [comment]
Any help on this...this looks really odd in patient finder

**Comment by mdsupport** [comment]
@arnabnaha, The external id field is designed to be a link between external systems and this emr - hence set to accept any characters. So the display order is correct. 

As a matter of convenience, the internal MRN is copied to external ID during patient creation process. If you have not manually set external ID in your system, use "patient list columns" list to display either `pid` or `id` as the column instead of `pubpid`. If you have manually entered external ID and continue to be annoyed by the display order, you will need to prepend `0`s so all entries are of same length.

Sort by Ext ID
![image](https://user-images.githubusercontent.com/399047/121961415-42e4c780-cd1c-11eb-9de5-fced38a48d92.png)
Sort by Int ID
![image](https://user-images.githubusercontent.com/399047/121961556-6c9dee80-cd1c-11eb-923c-09b1d3045e86.png)

Best.
