### ISSUE TITLE
Need to implement ACL for API contexts

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4109]
### Describe the problem
Currently we support permissions only for active openemr users. These are checked in our api route before dispatch.
E.g:
```
"GET /fhir/Encounter" => function () {
        RestConfig::authorization_check("encounters", "auth_a");
        $return = (new FhirEncounterRestController(null))->getAll($_GET);
        RestConfig::apiLog($return);
        return $return;
    },
```
However we have several more contexts we will need to check and easiest to reference the spec for these:
http://hl7.org/fhir/smart-app-launch/scopes-and-launch-context/index.html

The requesting user/patient/system/launch, through their client, will have several scopes based on what scopes are available to them from our supported scopes and authorized when getting their access_token. Scopes are embedded in token.
Based on these scopes permissions need to be determined.

For instance, consider a scope `patient/Patient.read`. 
We have a patient context where, based on preset permissions for the patient via user_id(patients UUID; also all patients will have the same canned permissions initially), they will need permission to be returned their available PatientResource FHIR or standard api response. Api type is determined as a scope too i.e api:fhir, api:oemr, api:port etc. but this should be determine in pre route authentication in resource server.

For Smart, we also have launch and/or intent permissions. For that @adunsulag may have some insight.

My thoughts @bradymiller and @sunsetsystems is ACL is best place to do this however, perhaps not so, do tell:)

**Comment by bradymiller** [comment]
Out of curiosity:
Are the scopes always in the access token? If so, does there also need to be a check to ensure a certain user/patient/system/launch has those scopes in oauth_trusted_user entry (or do we assume the access token can not be meddled with).

Something to consider. Could offer 2 strategies that are set in the oauth_trusted_user.
First is the standard one that uses the current authorization_check strategy.
Second is to use the scopes to decide if have access to the endpoint (in this case, not sure if even need complexities of acl stuff; probably just a function to see if the scope(s) has access to said endpoint (since there are wild-card entitities looks more complicated than just a simple match).

**Comment by bradymiller** [comment]
Another thing. How would non patient/user entities get an entry in the the oauth_trusted_user table (since that requires a login).

**Comment by adunsulag** [comment]
@bradymiller 

> Are the scopes always in the access token?
Yes they are.  I don't know enough about the oauth_trusted_user_entry so hopefully @sjpadgett can chime in on this.  The Access Token is supposed to be signed and hasn't been tampered with.  That's one of the reasons why we support a JWK so that the client can also verify the token has not been tampered with in transit from OpenEMR to the user agent by validating against our public key.

> Second is to use the scopes to decide if have access to the endpoint (in this case, not sure if even need complexities of acl stuff; probably just a function to see if the scope(s) has access to said endpoint (since there are wild-card entitities looks more complicated than just a simple match).

So the user agent's send us a request for the scopes they want which can include wildcards.  We send back to the user agent a list of claims which are the pieces of information the user agent is granted access to, so its up to us to determine what access we actually give to the requesting agent.  The spec states that if we don't want to allow wildcards we can send back a list of explicit claims that enumerate the resources that we give access to.  We also have the option to just reject any request for a wildcard.  I believe from reading Cerner's documentation that they follow this route.  To illustrate

User Agent Authorization Scope Request to authorize endpoint:
With request for **patient/*.read**
`HTTP GET https://localhost:9300/oauth2/default/authorize?client_id=I5lpBRdsrZKxECwBs6eYIixkExDMiS5EasLKXu66_As&response_type=code&scope=patient%2F*.read&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2F&state=9512151b-e5ca-cb4b-1ddc-aaf4cd8c6ecc&aud=https%3A%2F%2Flocalhost%3A9300%2Fapis%2Fdefault%2Ffhir

OpenEMR OAUTH2 Authorization /token endpoint response:

```
{
  "token_type": "Bearer",
  "expires_in": 3600,
  "scope": "patient/Patient.read patient/Patient.write patient/<Resource>.read patient/<Resource>.write",
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.....",
  "refresh_token": "def502005...."
}
```
If we only want to grant read only access on scopes we can also just send back these claims:

patient/Patient.read patient/Observation.read patient/<Resource>.read patient/<Resource>.write ...
```
{
  "token_type": "Bearer",
  "expires_in": 3600,
  "scope": "patient/Patient.read patient/<Resource>.read",
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.....",
  "refresh_token": "def502005...."
}
```

**Comment by sjpadgett** [comment]
Currently everything about permissions concerning apis are based on confidential apps using openemr users permissions.(Jerry overstating the obvious:)).
We can't rely on claims because the client will never send an id_token to our resource server where id_token is meant to be consumed by client to gain auth information about the server signed in user/patient session which the access/refresh tokens were issued against.(the main way id_token is used ,best I can see). So any permissions need to come from authorized scopes.

First thing we need to fix is the auth sign in dialog. Currently I validate requested scopes to supported claims which are populated and displayed. Though I save the validated scopes to the oauth_trusted_user, I don't display them in the user authorize dialog screen.(second screen). There will be, I assume, scopes that may not have a claim.
Best I can tell, smart doesn't need any claims except maybe fhirUser. Stephen will need to correct me here. Still, we'll always send any appropriate claims for OIDC.

So we could just leave id_token and claims out of this conversation for permissions except for any claims needed by the smart client to do its job. Restated for dispatch imo, access_token scopes beget scopes validated against trusted user scopes(if we wanted to verify access_token hasn't been tampered with) with permission context coming from app type, scopes and api type.

For wild cards, I recommend we not support and force explicite scopes. 
For permissions because apis are already setup with ACL for users, it just seems reasonable to keep and expand this workflow if possible.
I wonder what we will be talking about on Sat. call!

**Comment by sjpadgett** [comment]
> Another thing. How would non patient/user entities get an entry in the the oauth_trusted_user table (since that requires a login).

Besides patient/user we'd only have system via a client_credentials grant for backend. This is where client scopes will get used and treated as a user in many ways. i.e will generally have read/write.

I'm actually thinking I better go ahead and develop the manual/administrative UI while making the dynamic registration strict with perhaps three canned registration types that include set scopes etc. I don't see this happening in a week but I could if pressed.
