### ISSUE TITLE
FHIR Coverage Resource

### ISSUE THREAD

**Issue by vishnuyar** [openemr/openemr#4156]
### Describe the problem
Coverage Resource is required for implementing "Prior Authorisation" workflow(https://build.fhir.org/ig/HL7/davinci-pas/)

I am trying to implement FHIR Coverage Resource for OpenEMR.  (https://www.hl7.org/fhir/coverage.html)

Coverage Resource for a patient is retrieved based on beneficiary or patient reference in the search parameter.

This Coverage Resource should have the "Payor" details which is a reference to either an Organization (Insurance Company) or Patient( in case of self insurer )

The problem I am encountering currently.

FHIR Organization Resource for OpenEMR is returning only Organizations from table "faclity". These organizations are of type "prov" which is of type "Health Care Provider "

To incoporate "Insurance Company" as an organization, I can utilize the data from table "insurance_data" but would still need some data such as "address" , which I should probably able to take from the table "addresses" but I would need to store the UUID of these insurance organizations, should this UUID be created in the table "insurance_data"  or "addresses"

Ideally, we should have a table "organization" which has the required details, but going this way would involve code change for existing functionality

Second Problem

To know the insurance company of an patient, currently the API provides to ability to search by "pid" whereas the beneficiary or patient is known by "uuid".   I can create a new function to search by UUID but it would involve adding patient uuid column to "insurance_data" table

Any search of an FHIR Organization by uuid will involve searching in both "facility" and "insurance_data" because organization can be from either of these tables.

Do let me know your view points or any suggestions in my solution.

**Comment by sjpadgett** [comment]
Yes this is an issue that we need to address.
> but I would need to store the UUID of these insurance organizations, should this UUID be created in the table "insurance_data" or "addresses"

`insurance_companies` I think would be the appropriate place. This is because we are referencing the company as an Org rather than the patient data associated with the insurance company ie. policy info etc.
> To know the insurance company of an patient, currently the API provides to ability to search by "pid" whereas the beneficiary or patient is known by "uuid". I can create a new function to search by UUID but it would involve adding patient uuid column to "insurance_data" table

I believe we have this already but i'd have to look.

Bottom line is I recommend creating a standard service for Organizations to sort these issues out. FHIR would then instantiate this service instead of facility. Adding the UUID to insurance company would also need a minor code modification to create the UUID when creating new insurance companies.
We already have the create UUID mechanism in our database upgrade scripts so for implementing the new UUID for ins companies buring upgrades, one of us administrator will take care of. 

I wonder if other providers(labs, pharmacies, radiology...) will need to be included. An organization's table would be very handy where all Practice Settings referencing outside entities would be referenced from there. All existing sqls could remain as is where we'd just modify Practice Settings to populate the Org table with a relational reference back to entity. We could create an upgrade script for existing installations. This would be my preference and a more reasonable approach imo.

@robertdown, though on sabbatical, was looking into this recently and may have thoughts for us. Perhaps @bradymiller could give us some insights also. I think we could do the new table if that is your preference @vishnuyar.
