### ISSUE TITLE
LBF leaves patient_data columns unprotected

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#4406]
### Describe the bug

write concise description of what the bug is.
https://community.open-emr.org/t/dangerous-bug-in-lbf-forms/10880

### To Reproduce
play with LBF on a  demo and modify a column in demographics 

### Expected behavior
shouldn't be allowed to edit col names in core tables (summarizing Jerry here :) )

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by sunsetsystems** [comment]
Test it in current code. I thought there was logic to prevent deletion of a column that is in use, but perhaps that doesn't work in the case of date. Also the best solution for this and other things is to convert patient_data and history_data so that LBF fields go into a vertical table, as is the case with encounter LBFs.

**Comment by stephenwaite** [comment]
change an `ID`, in this case change `pubpid` to `pub_pid`
![Screenshot from 2021-05-19 18-53-42](https://user-images.githubusercontent.com/5618372/118895208-bb01ce00-b8d3-11eb-9049-e7df4481a7cc.png)
then try to use patient finder
![Screenshot from 2021-05-19 18-53-54](https://user-images.githubusercontent.com/5618372/118895221-c35a0900-b8d3-11eb-923d-aba5e2298dd2.png)

**Comment by sunsetsystems** [comment]
Yep that rename code is too permissive, and I think I also see a bug in the delete logic. I'll look into it.
