### ISSUE TITLE
Add relationships to Clinical Notes & Care Plan

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4462]
### Describe the problem
Just makes sense!
Difficult to make these relationships(problems, medications, procedure narratives and more) from API resources.
Also need document attachments in various places with relationships more specific to notes/procedures i.e. Document additions.

**Comment by adunsulag** [comment]
Something to make sure we handle this properly when mapping USCDI v1 Summary of Data Classes and Data Elements.  This is what we need to support for FHIR.

For Clinical Notes:
**Consultation Note** maps to **DocumentReference** using 
**Discharge** maps to **DocumentReference** 
**Summary Note** maps to **DocumentReference**
**History &amp; Physical** maps to **DocumentReference**
**Imaging Narrative** maps to **DocumentReference,DiagnosticReport**
**Laboratory Report** maps **DocumentReference,DiagnosticReport**
**Pathology Report Narrative** maps to **DocumentReference,DiagnosticReport**
**Procedure Note** maps to **DocumentReference,DiagnosticReport**
**Progress Note** maps to **DocumentReference**
**Consultation Note** maps to **DocumentReference**

For the DiagnosticReport note resources we have to support minimum LOINC category codes of 
LP29684-5 | Radiology
LP29708-2 | Cardiology
LP7839-6 | Pathology

So our pathology notes obviously will use the Pathology category code, I'm guessing imaging will use either Radiology or Cardiology codes?  Diagnostic Reports can be any LOINC code but are intended to be anything that we want to present structured code information rather than just a narrative text.  The same information will be represented / contained in a DocumentReference resource.

For the clinical notes DocumentReference each document will need a category flag identifying the note as a clinical-note.  We've talked about using the current labels/tags in our document handling system which has problems since clinics can edit these tags which will break the system (as Jerry can attest to clinics deleting CCDA categories).

In addition our clinical note documents that are generated need to have a single type code that represents what kind of document this is.  The types for clinical notes must be a valid LOINC code but at a minimum must support the 5 core requirements: 18842-5 (Discharge summary), 11488-4 (Consult note), 34117-2 (History and physical note), 11506-3 (Progress note), 28570-0 (Procedure note).

For our Document Reference resource we also need to support who authored the document, the organization, and the encounter the document is attached to.  I think we already have all of this information though but we don't require it on a document upload.  We may want to consider requiring an encounter to be populated when creating these kinds of documents are generated.

**Comment by sjpadgett** [comment]
hmm, there may be whiskey involved for this one!
Kidding, don't indulge.....

**Comment by sjpadgett** [comment]
@bradymiller 
Interestingly it appears that procedure orders are not and haven't been (at least all the time i've spent in form) correctly populating procedure type. Tables allows for it except from the wrong place imo. Procedure order form allows procedure type selection but for the entire order where it's expected(correctly so) for amc and documents from the procedure_order_code table(the test ordered). What's interesting is that Amc report and document property tag uses the type, mostly 'imaging'. Meaning do you know if ever worked? I'm trying to avoid breaking anything if I fix it(weird concept!)
Maybe @sunsetsystems has an insight?

**Comment by sjpadgett** [comment]
So far I tackled the document attachments to procedures. Some was already there but had to see it the rest of the way so to start I added a new field to the order test setup in configuration/compendium:
![image](https://user-images.githubusercontent.com/1859985/121756928-e4380780-cae9-11eb-88a5-94f746bdc521.png)

Then when a test is picked for the order the tests type is saved with it: The Default Procedure Type is there if configuration hasn't been configured and user can select in order form. 
![image](https://user-images.githubusercontent.com/1859985/121757163-a25b9100-caea-11eb-9a3a-273cf1b5ffab.png)

For Patient Documents I expanded the imaging tag for any procedure with its type.
![image](https://user-images.githubusercontent.com/1859985/121757527-de432600-caeb-11eb-80f0-133c8c463fc6.png)

So now any document can be tagged to any procedure and show in encounter or electronic reports.
![image](https://user-images.githubusercontent.com/1859985/121758032-bc4aa300-caed-11eb-9945-299dc8fc8cb5.png)

![image](https://user-images.githubusercontent.com/1859985/121758185-688c8980-caee-11eb-8443-2ccb96abda71.png)

**Comment by sjpadgett** [comment]
@bradymiller This has to go because that string can't word wrap meaning it holds responsiveness to that string width.
![image](https://user-images.githubusercontent.com/1859985/121759727-32063d00-caf5-11eb-8064-2cc4b98448af.png)
As you can see here:
![image](https://user-images.githubusercontent.com/1859985/121759814-95906a80-caf5-11eb-884a-5cf8f3ea27ac.png)

As compared to:
![image](https://user-images.githubusercontent.com/1859985/121759885-e99b4f00-caf5-11eb-8da9-029d1d60b2ed.png)

**Comment by adunsulag** [comment]
@sjpadgett as far as the hash breaking responsiveness, did you try using [word-wrap: break-word;](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) or probably even better the newer CSS property [overflow-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap).

I'm still looking through your pull request, I believe I'm following it all.  I'll let you know if I see any gotchas.

**Comment by sjpadgett** [comment]
I completely forgot about this neat little feature. I'm thinking we can use my text templating feature for both care plan and clinical notes. Could add the basic contexts to DB for encounter, notes and care plan.
Then add tags to the text representation or add to table.
![image](https://user-images.githubusercontent.com/1859985/121810325-63365880-cc2e-11eb-9f7a-0dc13923c5ba.png)
@adunsulag what'd ya think?
