### ISSUE TITLE
Bring Doctrine Back?

### ISSUE THREAD

**Issue by wesleylima** [openemr/openemr#4555]
Doctrine was removed here https://github.com/openemr/openemr/pull/3923 because of PHP8 compatibility.

Looks Doctrine got PHP8 compatibility!

https://github.com/doctrine/orm/issues/8350

Should we bring Doctrine back?

**Comment by adunsulag** [comment]
@wesleylima Do you have a project inside OpenEMR you would like to use Doctrine on?  I debated on using it in the current FHIR project as my own query builder stuff is really rudimentary compared to a full on ORM but due to the lack of PHP8 support at the time and the projects hesitancy of bringing in external dependencies I decided not to go that route.

I do really enjoy Doctrine though and so I'm interested in hearing your use cases for bringing it in.  We've got a lot of different access patterns scattered through the codebase and it would be nice to eventually consolidate them all (DataMapper, ActiveRecord, raw queries, spaghetti queries).

**Comment by sjpadgett** [comment]
Hi,
I'm fully onboard with bringing doctrine back. We'd need a reason first to justify sitting in core.
I also missed having when doing Oauth2/OIDC.

**Comment by stephenwaite** [comment]
when a post is edited the emojis should be wiped :)

can we back up to spaghetti?

![SPAGHETTI](https://user-images.githubusercontent.com/5618372/128076843-ea428706-7d31-4081-a63a-d282e9fdfb32.gif)

**Comment by wesleylima** [comment]
@adunsulag I'm writing a new patient portal route for appointment booking.

So is the sentiment in this thread representative of the overall project?
If I submit an MR that add doctrine and/or refactors some queries to use the doctrine it wont get rejected outright?

**Comment by bradymiller** [comment]
Lets put some more thought/research into this (says the person whom
expended large resources on the very unfun project of removing doctrine so
we could release 6.0.0 :) ). My take at that time was that doctrine's dev
support was winding down, so they were unable to keep up with the php
version releases. If we are very confident this will not happen again, then
would be ok with me.

**Comment by sjpadgett** [comment]
I get it @bradymiller however, you're always way ahead of most in our new PHP releases support and when I researched at the time, Doctrine was working on PHP8 support. I agree though, we'd need a very good reason to bring back. Mixing Doctrine into our API for one endpoint wouldn't make sense.

**Comment by juggernautsei** [comment]
I would agree that it would have to be a major feature build to justify bring doctrine back. I have been taught here not to have things just for the sake of having it or for the few. It would have to benefit the many to warrant bring it back into the codebase. Right now, we can forge ahead without it and really not miss having it in the codebase. As just said KIS. That was the advice given to me by my very first mentor. Do the simplest thing that works.
