### ISSUE TITLE
Cant Find the Batch Payment and Posting Links Under Fees

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#457]
Hello,

Currently using the dev tip 5.0.1 and I cant find the Batch Payment and Posting Links in the left side menu under fees. In globals, I can see both the "Enable Batch Payment" and "Enable Posting" already checked.
Please help

**Comment by arnabnaha** [comment]
UPDATE: 
I unchecked the Enable Bath Payment and Posting in the globals and saved it. Then Rechecked both of those options and saved it again. The Menu links appeared...

**Comment by bradymiller** [comment]
This happened because I forgot to increment $v_database in version.php for several recent global and database changes. We do this when add global or database changes, which then flags (in admin.php script) to do a sql_upgrade.php run. Note that when you save globals in OpenEMR, it will also bring in the new globals (this is why it worked for you after you saved the globals).

**Comment by bradymiller** [comment]
btw, just brought in a commit that incremented $v_database to fix this issue. And will ensure we increment this when needed in the future.
