### ISSUE TITLE
Main tab bar is not mobile-friendly

### ISSUE THREAD

**Issue by sunsetsystems** [openemr/openemr#4614]
### Describe the bug

The main tab bar is not responsive to small devices. That is, with several tabs open on a narrow screen it does not collapse nor otherwise do anything to prevent a horizontal scrollbar. This means that content within a tab cannot be properly laid out for the device and is an obstacle to responsive behavior of the entire application.

### To Reproduce

1. Open a few tabs.
2. Make the main window narrow.
3. Note that the tabs remain in one row.

### Expected behavior

The tab bar items should stack vertically as required.

### Notes

This is built with Knockout JS and has some nice features such as the ability to "lock" a tab onscreen, but is not mobile-friendly. I'm thinking it needs a rewrite with Bootstrap classes that sacrifices this feature, but perhaps there's an easier/better way?

**Comment by sunsetsystems** [comment]
Just a note that I've been working on bootstrapping LBF data entry, so this issue will become more relevant.

**Comment by mdsupport** [comment]
@sunsetsystems Just a simple feedback from past 5-6 years of support. Tab in jquery-ui world to Nav in bootstrap world is relatively easy migration if it is driven by database tables. In fact we even had some javascript reformatter that redid current screen layout. However that only addresses overall navigation. The content / forms that work well on desktop simply cannot be reformatted to work even a small tablet and definitely not on 6" phone screen.
Our response to that problem was "App" feature added to login. That lets mobile users have all things they need for their role and suitable for their device form factor. As an example mobile user will never fully use an text area for data entry. But they can have 10s of checkboxes that builds a nice list in that text area.
Our main problem with Layouts is standard library functions do not follow model and view principle. Hope as you work on LBFs you make it layered where data layer builds an field object that can be processed in very few common view routines. That will make future bootstrap 4 to bootstrap 5 or 6 migration trivial.

**Comment by sunsetsystems** [comment]
@mdsupport Thanks for the input. It won't be so fancy this time around, mainly I'm just converting tables to BS grids and making them stack for small devices and maintain sensible widths and spacing, without hurting the PC experience.

Some LBFs will present special problems for small screens and missing keyboards. For those the developer may want to look into LBF plug-ins, where custom form-specific code can be implemented on both server and client sides.

There's certainly much that can be done to make the code more modular and consistent. I'm pleased to see your interest in that.

**Comment by mdsupport** [comment]
@sunsetsystems Current approach has layout row as "inline form" layout. That is hard for the flex engine to handle with multiple rows. @tywrenn may have some ideas but you may want to switch vertical layout (field below label) otherwise the engine tries to keep label with the field but not always. And that becomes frustrating for the users. 

Another consideration would be Bootstrap 5 implements [floating labels](https://getbootstrap.com/docs/5.0/forms/floating-labels/), that eliminate chance of labels straying from the control.

**Comment by sunsetsystems** [comment]
@mdsupport Yes to field below label. PR with suggestions welcomed will be coming very soon. BS5 conversion will be interesting! Thanks again.
