### ISSUE TITLE
Document Download New Tab White Page of Doom

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#481]
Notice how a new tab opens when clicking on a document... I get the _white page of doom_. This is reproducible with the tabs version of the software as well.

![bug_report_new_tab](https://cloud.githubusercontent.com/assets/1715206/22858992/22599222-f09c-11e6-8b62-77a5aca0b41f.gif)

**Comment by MatthewVita** [comment]
At the end of the video, I show that by clicking "Download" button everything works as it should.

**Comment by MatthewVita** [comment]
I notice that the same thing happens with the CouchDB mode, but the page gives a failure response (grey screen of death)

**Comment by mdsupport** [comment]
If I am not mistaken, although table has mimetype field which is populated, click code expects specific extensions to decide whether to show file or download. Also browser settings have some role. Try document like xxa.pdf instead of xxx and make sure pdf has a viewer associated for browser display. Then try xxb.jpg, finally a document like xxc.  

Fix probably is to make mimetype user specified mandatory field and then rely on it throughout application.

**Comment by MatthewVita** [comment]
Closing this because it's due to my user, however, we can guard against it with this PR: https://github.com/openemr/openemr/pull/508
