### ISSUE TITLE
Layouts responsiveness needs work

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4842]
### Describe the problem
Everyone knows how much I love out LBF feature however in current web environment, supporting small devices is becoming more important every day.

The biggest issue is most all data types use tables for screen layouts.  These are only responsive to a certain point and to change to a grid pattern would require considerable work. If I had help, I'd tackle it.

But for now I will try to tweak what we do have that supports a grid which in the end generally is a column that holds a table.

**Comment by sunsetsystems** [comment]
As you doubtless know I bootstrapped the top-level layouts back in September but yes some of the field types use tables. It might be useful to work up some examples and figure out what behavior is wanted with smaller screen widths.

**Comment by sjpadgett** [comment]
True but just needed to add a breakpoint at lg(current md) to col-12 which helps considerably.
Also need to add breakpoint to our container-fluid class where fluid is not needed on larger desktops ie 990px

Some of these small adjustments make a big diff on mobile. You'll see when I put up some screenshots.

**Comment by sjpadgett** [comment]
Some restyle to demographics. I think this is more apt for data input and when lg breakpoint is reached, goes to 100% width.

![image](https://user-images.githubusercontent.com/1859985/150247464-e3b89f81-12a5-46c1-be3d-b4696ea71893.png)

768px BP:

![image](https://user-images.githubusercontent.com/1859985/150248459-3ccb7670-efe0-4d53-aa7d-453414917e62.png)

**Comment by sjpadgett** [comment]
comprehensive

![image](https://user-images.githubusercontent.com/1859985/150251433-2960fafa-4ac7-40d3-82c8-aa47abc40370.png)

**Comment by mdsupport** [comment]
The code needs to embrace bootstrap to fullest and options is not geared for that. As an example if you put pt prefix,fname,mname,lname and sfx in a BS input field group, it will take care of margins and keeping it together as most users want. Compare to code for that column with [bs approach](https://getbootstrap.com/docs/4.6/components/input-group/#multiple-inputs).

When playing with standard code our conclusion was the row column structure is rendered sometimes on tablets in horizontal(wide) mode but rapidly becomes collection of label/input. The layout presentation in view mode is even more difficult to work.

We currently post-process the standard output by moving all cells into divs (gasp - using jQ code) and then let bootstrap do its thing at the client. But that is constant struggle since options library emits highly targeted html. 

For standard code, suggestion would be to abandon label as separate column and move it on top of the input group using bs label-for. If the project keeps bootstrap as rendering engine, then also consider the [floating labels in 5.x](https://getbootstrap.com/docs/5.1/forms/floating-labels/#example).
