### ISSUE TITLE
Adodb + php7.1 (and other php 7.1 compatibility issues)

### ISSUE THREAD

**Issue by santiagosemhan** [openemr/openemr#488]
OpenEmr v5_0_0 tag needs to be adodb-php 7 compliant. So, i have to update adodb to 
`"adodb/adodb-php": "5.20.9"`
in composer.json. 

Please check this to update!

**Comment by bradymiller** [comment]
Thanks for reporting this. I just updated the adodb package in the 5.0.1 development branch (master). It will take awhile before it gets into 5.0.0 patch (it may not get into a patch since it involves quite a few changes, needs to be tested for awhile since it is a core package, and would require a new set of OpenEMR packages since it breaks install/upgrade). Going to keep this issue open as a reminder to port over to 5.0.0 if too much time passes before release of 5.0.1 .
-brady

**Comment by bradymiller** [comment]
Gonna convert this ticket also into other php 7.1 issues, if they exist, so keep the fixes tracked.
@santiagosemhan , have you noticed any other issues with php 7.1?

**Comment by santiagosemhan** [comment]
Hi @bradymiller . I don't have noticed another issues. Otherwise, i think that is necessary clear all warnings and notices in development phase. Its not related to php 7.1 but we can leverage this update to do that!

Thanks!

**Comment by bradymiller** [comment]
Going to close this since are creating separate issued for PHP 7.1 problems.
