### ISSUE TITLE
PDF from patient summary reports getting cropped

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#491]
Hello..
I have created many forms with xmlformgen. One of them is the history form which I use to take the initial history of the patient. whenever I try to print out the pdf from the patient Summary->Reports->Download PDF, I get the pdf which is cropped and most of the info is not shown due to cropping. Please see the attached image.
![lbf cut in pdf](https://cloud.githubusercontent.com/assets/1074948/23291108/dc72ed46-fa7b-11e6-9f6e-8ef140dbea0b.jpg)

In the above image, chief complaints is cropped, The present history is also completely cropped and is not shown.This makes the pdf feature useless as I am not able to print using that. Please help me!

**Comment by rahulteja526** [comment]
Hi @arnabnaha , have you tried the PDF tab in Administration-> Globals ?
If your answer is yes and you are still having the issue, 

please go with NONE for margins while giving print. If done this once, and you no need to do it again on same system. ( Caution : This is a temporary solution. )

I'm also working on this issue, because, lab reports which I uploaded to Documents are also breaking between pages. i.e some portion of  X-ray in page 1 and remaining portion in page 2. I'm trying to get that whole x-ray in one page. If anyone faced this issue, kindly reply here.

**Comment by sjpadgett** [comment]
@arnabnaha and @rahulteja526 If this hasn't been solved, I'd like to take a swipe at it. Not sure I understand the path the documents have taken to get to the reporting point. Are they scanned document or in case of formgen a form report.php is used. Maybe they are mixed pdf from patient document. Anyway, if you could clarify this and even send me the form or document I can test with maybe I can help as I've visited this code a few time.

**Comment by arnabnaha** [comment]
@sjpadgett Please take a look at it. I cant take print outs of the reports. can you send me your email ID? I will send you the form in zip format.

Thanks and Regards
Arnab

**Comment by sjpadgett** [comment]
@arnabnaha send it here: sjpadgett@gmail.com

**Comment by arnabnaha** [comment]
@sjpadgett Have sent it. Thanks

**Comment by sjpadgett** [comment]
@arnabnaha In your case there really isn't a bug in the patient reporting download because the issue of word wrapping in the TCPDF class is a limitation of the core html to pdf. In this report case the easiest solution is to restrict the number of columns to print in the report from 6 columns to 2. I don't remember how columns are calculate before calling report and that may need to have a second looked but, for now, I modified your report and will e-mail to you.
It may be time to change the core pdf engine in this module.

**Comment by arnabnaha** [comment]
@bradymiller 
Hi..
Have created a PR for this. Jerry has fixed the cropping issue by changing the report.php of a form and it now displays really nicely. I have introduced the changes done by Jerry into the xmlformgen to create the forms with the changes in place. Have tested them with my forms and also by creating new forms. works pretty well. 

Here is the link for PR:  https://github.com/openemr/openemr/pull/660

**Comment by bradymiller** [comment]
nice.
Just had a couple minor testing questions on the PR.

**Comment by bradymiller** [comment]
Also, if this works well, then we should think about bringing this into the report functions for all the main OpenEMR forms.

**Comment by arnabnaha** [comment]
@bradymiller 
Answered the questions in the PR

**Comment by bradymiller** [comment]
fixed, so closing this issue
