### ISSUE TITLE
oemr api functions not available during app registration

### ISSUE THREAD

**Issue by larjohn** [openemr/openemr#4982]
### Describe the bug

I am trying to register an app to make use of the API functions. During the registration, I can't select the oemr functions (lowercase first letter), only the FHIR ones (uppercase first letter). Later on, in Swagger I get 401 using the patients list function (oemr), while a correct list is returned using the FHIR equivalet (Patients).

### To Reproduce
1. Register an app
![image](https://user-images.githubusercontent.com/1288985/156903618-506fe436-21db-4a87-ab6d-b62f9e9e3bba.png)
2. Enable API client in settings
3. Select all available scopes
4. Go to Swagger and Authorize with the credentials, selecting all available scopes (except the system ones)
5. Invoke the patients list function (oemr)

### Expected behavior
1. The list should be returned, just like the FHIR one

### Client configuration

- Browser: Edge (Chromium)
- OpenEMR version: 6 Patch 4
- Operating system: Windows 11

**Comment by adunsulag** [comment]
I'd classify this more as an enhancement than a bug.  Registration can still be done via a API call to the registration endpoint.  This app registration screen is a GUI enhancement to make registering a SMART app easier.  We originally built it for the SMART on FHIR specification but we should enhance it so individuals can register for standard OpenEMR functionality as well.  

I'm happy to advise others if they want to take on this enhancement.  Shouldn't be that hard and an easy first issue.  Otherwise we'll take this on most likely after we finish ONC certification.
