### ISSUE TITLE
Add Default Billing Facility for Providers

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5006]
We support in the database for a user/provider to have an assigned default billing facility.  In the user admin add / edit functionality we need to be able to set the default billing facility for a provider.  This supports relationships needed by CCDA as well as for the AMC calculations.

**Comment by sjpadgett** [comment]
Having a default billing facility for the user is convenient on the encounter level however it become moot many times because provider can move from facility to facility.
I would think that if a provider provides service in a service location facility then the best place to have a default billing facility would be attached to the service facility.

This is the main reason to have a billing facility in the encounter since we are encounter based billing. Even still many times, I suspect, the billing folks have final word what facility gets payment for the encounter.
To take this further, consider the case that the supervising provider is responsible for the claim. Does the mean his default facility is used? I put in the supervising provider for just this case though I don't think it currently trickles down in billing.

**Comment by adunsulag** [comment]
So for AMC, the calculation can be run based on the primary care provider relationship or upon the encounter one.  I think pretty much everyone will use encounter but in order to support the primary relationship use case I need to be able to trace from the patient to provider and then to the billing facility from there.  I also traverse the supervisor relationship if there is one set.

I don't know how much of that relates to the claims.  Whoever handles the AMC reports will need to make sure they use the same relationship with whatever billing is submitting for claims (whether that's off the primary care designation or the encounter).

**Comment by sjpadgett** [comment]
Yep this is tricky. We need to update encounter to auto select though.

**Comment by stephenwaite** [comment]
good points, it's good to have flexibility for the billers on the encounter screen with the ability to default and the service facility default seems like a good add to trump the provider

**Comment by sjpadgett** [comment]
Does anyone know what the heck Facility Default User Information in Users UI is? It make little sense to me!

![image](https://user-images.githubusercontent.com/1859985/158480857-28b94faa-0a04-4667-ac33-a948ad21feb1.png)

**Comment by stephenwaite** [comment]
Pretty sure was never fully implemented.

**Comment by sjpadgett** [comment]
I guess it could be used to attach a provider to all their facilities.
