### ISSUE TITLE
Providers list being searchable

### ISSUE THREAD

**Issue by chaolewis** [openemr/openemr#5019]
**Describe the problem**

The Providers list under the calendar and within the appointment scheduling can get out of hand when you have 50+ providers listed there. With no way to manage or sort through them quickly.

https://community.open-emr.org/t/provider-list-search-function/18037

**Describe the solution you'd like**

Is there anyway to make this provider list into a searchable with a search box.

**Comment by sjpadgett** [comment]
@chaolewis Do you have plans to upgrade to our upcoming v6.1.0 release(maybe with in a week)?

**Comment by chaolewis** [comment]
> @chaolewis Do you have plans to upgrade to our upcoming v6.1.0 release(maybe with in a week)?

Is there a feature in v6.1.0 that will help with this issue that I am proposing?

**Comment by sjpadgett** [comment]
No, if not to hard I may be able to sneak it into next release. No promise though.

**Comment by monte213** [comment]
Thanks Jerry. To further elaborate on this request, we are a college focused on healthcare with a center we run that provides pro bono services to the community. Those services span several disciplines like OT, PT, PA studies and Speech Pathology. We are looking at OpenEMR as a possible solution to help us manage EMR aspects of our center.

The challenge we are having is that we will have hundreds of students in a provider role that we'd need to enter into the system. (and while less faculty in a physician role....there will still be a good amount of them as well)

What we've found is that areas like the display of providers in the Calendar area and (multi-) provider scheduling functionality don't seem to scale well to that number of providers. So this request was to see if there is a way to programmatically address this challenge or otherwise seek guidance on how to handle this amount of providers.

Thanks for considering

**Comment by sjpadgett** [comment]
To do this a select2 is best choice. You'd have to init the select2 in the calendar smarty template then handle the selections.
I just don't have time now. If you want to take a look source here: interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html L-318 to get a start

**Comment by infeg-khaleela** [comment]
Hi
We have used select2 to search the provider name (which will drill down the search and then select) in add appointment popup.

We would like to contribute the same to the codebase after your reviews.

**Comment by infeg-khaleela** [comment]
Hi
This feature is committed and here is the pull request - https://github.com/openemr/openemr/pull/5146

please review the same, test and share your review comments.

Thank You
INFEG

**Comment by monte213** [comment]
Hi INFEG - This is great to hear...I look forward to seeing it in action. Thank you for contributing!
