### ISSUE TITLE
CQM update OpenEMR interface for data entry of QDM elements

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5253]
Clinical Quality Measures (CQM) for MIPS reporting and our ONC certification relies on a number of additional data elements (Quality Data Measures or QDM) that currently can't be entered into OpenEMR through the user interface.  The only way currently data can be entered is through a CCDA import.  This is a parent issue that will hold the individual sub-issues for the UI elements we are modifying / changing to support CQM. 

- #5254 (This issue also addressed the vitals form reason codes)
- #5255
- #5267 
- #5260
- #5276
- #5277
- #5278 

We will add to this list as we find other items.

**Comment by stephenwaite** [comment]
Thanks for kicking off this parent issue. I think this is needed although it could be solved by looking in the fee sheet but figured this is probably simplest.
- #5260

**Comment by adunsulag** [comment]
@sjpadgett or @kchapple Can you explain what is intended by reason_date_low and reason_date_high in care_plan for?  I noticed those are also fields that need to be added to the CarePlan and I'll open a new issue for them but I need to understand how they are used to provide some guidance in the UX for those fields.

**Comment by kchapple** [comment]
Hey @adunsulag I don’t see anywhere those fields are used in qrda exports. I’m not sure why they were added, but I presume that they are intended to be the start and end dates for the reason code.

**Comment by adunsulag** [comment]
@kchapple @sjpadgett ok, that makes more sense if that is what they are intended for.  I can see they were added in this commit: https://github.com/openemr/openemr/commit/5c549edabd64e4f5c35df612216d5de3eb08aa28 .  If they are indeed the start and end date should we rename them to be reason_date_start and reason_date_end to avoid confusion?.  I know it was confusing to me.

**Comment by kchapple** [comment]
That makes sense to me. The high and low labels are terminology specific to describing ranges in this qdm/qrda stuff. Start and end is more consistent with OpenEMR. We’ll have to check with @sjpadgett to see if we are missing anything in the medication care plan exports, because those columns aren’t being used, but probably should be if they were added!

**Comment by sjpadgett** [comment]
Low and high date attributes are standard terms in CCDA spec. Since QRDA is a subset of CCDA with customs to QRDA, the terms carry through.
A low date or a high date could be either or depending on their context i.e may not be a date range.

You can refactor if you think it is necessary and better for consistency or I can do if you guys feel strongly about it. I tried to keep the naming similar to the template import because I thought it might be more relatable to Ken while he was figuring out populating the models.

A quick look at the spec IG doesn't show a requirement for an effective time. Although a review of all my current test patients has many reason observations w/o dates, some with just a low date and some with both. Negation isn't a determining factor.

My guess would be the high date could be considered a completion date with low date the record date for the reason if that help with a context for the user.

I can see where reason dates could be important to a measure calculation though unsure if it matters for our purpose since we haven't seen the issue in our current testing. However, doesn't mean that a different set of test patients may not use them.

It appears that the c(1) attribute entry test is certainly enamored with negation.

**Comment by adunsulag** [comment]
@sjpadgett Thanks Jerry that explains things.  Perhaps the easiest would be to add a comment to the careplan columns to explain what they mean?  I just know I was confused as to the column's purpose.  Then again, I'm not sure our upgrade script has any way of just updating a column if a comment is missing.

**Comment by sjpadgett** [comment]
If a macro isn't available you can do a stand alone alter column with the comment. i.e. always runs. We do this every now and then when necessary.

**Comment by bradymiller** [comment]
I think these changes are only in 7.0.0-dev so would just add comment in database.sql and the original code block in the 6_1_0-to-7_0_0_upgrade.sql upgrade script.

**Comment by adunsulag** [comment]
Since we certified this criteria, closing this item.
