### ISSUE TITLE
FHIR Resource Questionnaire

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#5300]
Does anyone know if [Resource Questionnaire(s)](https://www.hl7.org/fhir/questionnaire.html) are included in the codebase as part of FHIR work?

If so, are there services to map them to openemr data structures?

**Comment by adunsulag** [comment]
So the datatype exists in the codebase as it was part of our generated classes from R4.  I think the FHIR Questionnaire though has been updated in the 4.0.1 FHIR update as its prior maturity level was L2 instead of its current L3 so I don't know what additional fields may be different in the codebase vs the latest spec.  

I don't believe we have any services that utilize the class at this point in time.  I've heard of people discussing implementing those in private OpenEMR implementations but I don't know of any readily accessible code that's available for people to use.

Once I'm done with ONC projects that is something I want to implement if someone hasn't done so already at that point as my own mental health assessment company would leverage that resource.

**Comment by mdsupport** [comment]
To provide context for the original question, we are exploring possibility of eliminating use of anything goes type of layouts and/or "forms" - starting with at least the observations. Each practice can use standards based [NLM form builder](https://lhcformbuilder.nlm.nih.gov/) from predefined panels and generate their own forms. The LHC form widget can then provide the input as questionaire response which we will need to save in EMR in a generic observations table - something that can hold vitals, lab results, GDS responses - each with their related LOINC codes.
 
But it looks like FHIRQuestionnaireResponse objects are currently not stored in database. So we will need to come up with generic observations table - is that what your response meant?

**Comment by sjpadgett** [comment]
bump https://github.com/openemr/openemr/issues/5677

**Comment by sjpadgett** [comment]
bump
