### ISSUE TITLE
search for and select OID from cqm valueset with find_code_popup

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#5306]
after importing a good patient from cypress for CMS69v10, it looks like we'll need to be able to select an OID from the cqm valueset for the Care Plan Form `Code`

![Screenshot from 2022-05-09 14-50-08](https://user-images.githubusercontent.com/5618372/167478381-5d188afb-f522-4148-8c2f-ac9f562b1193.png)

![Screenshot from 2022-05-09 14-56-30](https://user-images.githubusercontent.com/5618372/167478509-d27c5ed6-b24a-44b8-b13c-f327339eff7c.png)

child of #5286

**Comment by adunsulag** [comment]
@stephenwaite @sjpadgett Isn't that what the CQM Valueset is for in the code popup dropdown?

**Comment by stephenwaite** [comment]
but only the `code` is selectable

**Comment by sjpadgett** [comment]
This is another screwy qrda deal where instead of a code they want a nullFlavor for the code and mustache populates the valueset.
The deal is how to know what valueset to use so, we may need to create a list however, there are times when we have negation and still set a code.
The theory being that for a negated component there'd be no code but part of a valueset that describes the component the reason code is based on.

I don't have an easy answer for this and have taken under advisement. I'm pretty sure I described this where we need to modify code selector to select valuesets to be returned.

**Comment by adunsulag** [comment]
@sjpadgett For some reason I thought that the creation of the list was the work you did with adding in the CQM Valueset as a codetype, ie being able to return the valuesets we needed for CQM.  I must not be understanding.

**Comment by stephenwaite** [comment]
for valueset we're going to need additional ability to select by valueset name and then choose the OID instead of the code it appears

**Comment by sjpadgett** [comment]
we need another call to get up to speed. too much to explain.

**Comment by stephenwaite** [comment]
ok, why don't we keep it simple and just create another code type called OID when importing valueset?

**Comment by sjpadgett** [comment]
I think this requires more thought @stephenwaite. I know you have all this giddy up currently but I need a little time to decide best approach and do some research. CodeTypesService may be a way to go as I have a function in the service that resolves many gotchas.
We really need to make this simple for user and may need to automate in some way.

**Comment by sjpadgett** [comment]
> ok, why don't we keep it simple and just create another code type called OID when importing valueset?

@stephenwaite I can't think of a quick easy way out except to do as you suggest.
You should be able to duplicate everywhere the CQM code type is used and adjust to grab and return the OID.
Are you okay doing this? If need some help just let me know.
