### ISSUE TITLE
Support patient previous addresses

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5367]
We need to support patient previous addresses as part of the US Common Data Interoperability (USCDI) specification.

**Comment by adunsulag** [comment]
@psoas this is the issue we'll use for commenting about this item.

**Comment by mdsupport** [comment]
Based on what was done In another project, you could handle addresses as follows -
1. Add address_use (id as pk, address_id as fk1, {use_type, use_id} as fk2, eff_from, eff_to, changed_by, change_note)
2. Move addresses.foreign_id as address_use.use_id and populate appropriate use_type
3. During setup dump distinct addresses from patient_data in addresses table followed by inserts of address_use
4. During transition leave current patient code in place but trigger address_use check to make appropriate updates to address tables.
5. Implement patient code updates that offer to populate all address fields from addresses entries and then maintain addr_use record.

This setup lets you link same address with multiple patients, insurance plans or other use_types. Also allows to record the moves that temporary/permanent at current or future dates.

**Comment by mdsupport** [comment]
On a related note, address is just one of the contact. If this project ever decides to start using json database fields, use_type can specify various groups of fields and let database views offer those fields as columns.

**Comment by psoas** [comment]
Interesting proposal, although I don't completely understand it.

We were planning on introducing the tables contact & contact address AND modifying address.  However, we did not discuss how to deal with insurance companies and pharmacies which use the address table and are referenced by the foreign id.  It looks like your proposal tries to address that.  Can we merge our idea and your idea?

CREATE TABLE `contact` (
  `id` BIGINT(20) NOT NULL auto_increment,
  `type_table_name` VARCHAR(255) NOT NULL DEFAULT '',
  `type_table_id` BIGINT(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`contact_id`)
) ENGINE = InnoDB ;

CREATE TABLE `contact_address` (
  `id` BIGINT(20) NOT NULL auto_increment,
  `contact_id` BIGINT(20) NOT NULL,
  `address_id` BIGINT(20) NOT NULL,
  `priority` INT(11) NULL,
  `type` VARCHAR(255) NULL COMMENT '[Values: Home, Work, Physical, Mailing, Shipping]',
  `room_number` VARCHAR(45) NULL,
  `notes` TEXT(255) NULL,
  `is_billing` BINARY(1) NULL,
  `is_mailing` BINARY(1) NULL,
  `status` BINARY(1) NULL COMMENT '[Values: Active, Inactive, etc],
  `created_date` DATETIME NULL,
  `activated_date` DATETIME NULL,
  `inactivated_date` DATETIME NULL,
  `inactivated_reason` VARCHAR(45) NULL DEFAULT NULL COMMENT '[Values: Moved, Mail Returned, etc],
  PRIMARY KEY (`contact_id`),
  KEY (`contact_id`),
  KEY (`address_id`)
) ENGINE = InnoDB ;

CREATE TABLE `addresses` (
  `id` BIGINT(20) NOT NULL auto_increment,
  `area_type` VARCHAR(60) NULL DEFAULT NULL COMMENT '[Values: Assisted Living Facility, Nursing Home, Neighborhood, Apartment Complex, Independent Living Facility]',
  `line1` VARCHAR(255) NULL DEFAULT NULL,
  `line2` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `state` VARCHAR(255) NULL DEFAULT NULL,
  `zip` VARCHAR(255) NULL DEFAULT NULL,
  `plus_four` VARCHAR(255) NULL DEFAULT NULL,
  `country` VARCHAR(2) NULL DEFAULT NULL,
  `area_name` VARCHAR(255) NULL DEFAULT NULL COMMENT 'neighborhood name, or apartment complex name, or facility name',
  `directions` TEXT NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `foreign_id` BIGINT(20) NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY (`foreign_id`)
) ENGINE = InnoDB

Would address_use be similar to our table contact?

**Comment by psoas** [comment]
Stephen, the following is a slight revision to the contact_address table, mostly based on our conversation:

CREATE TABLE `contact_address` (
  `id` BIGINT(20) NOT NULL auto_increment,
  `contact_id` BIGINT(20) NOT NULL,
  `address_id` BIGINT(20) NOT NULL,
  `priority` INT(11) NULL,
  `type` VARCHAR(255) NULL COMMENT '[Values: Home, Work, Mailing, Vacation, Relative, Friend, Caregiver]',
  `notes` TEXT(255) NULL,
  `is_active` BINARY(1) NULL,
  `status` BINARY(1) NULL COMMENT '[Values: Active, Inactive, etc],
  `created_date` DATETIME NULL,
  `activated_date` DATETIME NULL,
  `inactivated_date` DATETIME NULL,
  `inactivated_reason` VARCHAR(45) NULL DEFAULT NULL COMMENT '[Values: Moved, Mail Returned, etc],
  PRIMARY KEY (`contact_id`),
  KEY (`contact_id`),
  KEY (`address_id`)
) ENGINE = InnoDB ;

Also, in regards to mdsupport comment, dealing with the foreign key, insurance companies and pharmacies is beyond the scope of this issue.  However, I would like to discuss it AFTER this issue is addressed so that I can work on it in the future.

**Comment by mdsupport** [comment]
Our implementation was year ago. Now, as the push for inter-connectivity increases, any new development should faithfully implement FHIR structures rather than implementing something that will later need mapping efforts. These are well analyzed and thoughtfully designed structures. Why not implement structures specified including their column names?

1. [Address](https://www.hl7.org/fhir/datatypes.html#Address)
To minimize impact retain current table name as addresses with 1:n line denormalized to line1, line2, etc.

2. They identify address use in the following places: Claim, ClaimResponse, ExplanationOfBenefit, InsurancePlan, Location, Organization, Patient, Person and RelatedPerson.
We have always implemented these type of uses as a relation table. Considering there are so many, we include use_source as entity specifier along with use_id to link multiple tables. Also implement use(AddressUse), type(AddressType) and (start, end) pair as period in the linked table.

I think implementing centralized contact will make this rather complex for the staff to maintain.

**Comment by psoas** [comment]
I like your link.  I agree that we should mirror the database field names in the FHIR specification.

I also prefer to change the table  name 'addresses' to 'address'.  I strongly agree with you there.  I discussed this with Brady at the weekly conference call.  He strongly prefers not to change the names of tables and fields that are already established and used by existing code, due to the risk of introducing bugs.  Maybe you can speak to Brady about this.

I also agree that should have the fields 'use' and 'type' using the FHIR content definitions (and add them to the contact_address table).  

We should also change the names of the fields in the contact_address table from activated_date and inactivated_date to period_start and period_end.

And, finally to our addresses table we should add the field district (which is in the FHIR address table).

My table 'contact' is our equivalent to the 'relation table' that you referred to.  And, this table would be invisible to the user, so I don't see how it would be difficult for your staff to maintain.

Centralizing contact allows us to more easily use the same contact tables for: Claim, ClaimResponse, ExplanationOfBenefit, InsurancePlan, Location, Organization, Patient, Person and RelatedPerson.

With a good UI, it should be easier for your staff to maintain rather than more difficult when compared to how OpenEMR is currently structured.

Whether or not to normalize addresses is a different issue.

**Comment by adunsulag** [comment]
@psoas and @mdsupport.  I'm very much in favor of trying to mirror FHIR as much as we can.  

Perhaps there's a better name for the contact table, but that as David mentions, the contact table represents the join table between the various other data models (Claim, EOB, Insurance, Patient, etc) that you are desiring @mdsupport.  It contains the  **type_table_name** which is the same as your **use_source** and the **type_table_id** which would be the same as your **use_id** column.  I personally am more a fan of 'foreign_table_name', and 'foreign_id'.  But they all represent the same concept of the mapping table and mapping id.

Currently we are only targeting the Patient relationship as that is what is needed for us to get certification wrapped up.  ONC updated their testing requirements the last couple weeks apparently which exposed the fact we were missing previous address information for patients.  Future work should be able to leverage this foundation for connecting with the other Data Models you are discussing. 

I think we are all thinking in similar lines of thought as our plan was to attempt to follow a pathway very similar to what you've laid out @mdsupport in your first post in the thread.  I appreciate your willingness to help us engage on this since it sounds like you've already done similar work in the past.

**Comment by mdsupport** [comment]
@psoas, @adunsulag My only intent was to see if your designs leave room for future extensions with minimal code changes.

Prior to FHIR everyone addressed problem at hand which is something we did years ago resulting in address_use. Still have not figured how to consistently translate wealth of HL7/FHIR models. Basic challenge here is mapping the FHIR type document structures to emr's relational tables. 

Completely agree that certification is top priority. As long as we rely on objects we always have easier path for later updates. Wish you best and thanks for all work in making certification possible.

**Comment by psoas** [comment]
@psoas, @adunsulag
Please do change the field names in 'contact' to 'foreign_table_name' and 'foreign_id'.  That does make more sense.

And, in my other comments, I forgot to write @adunsulag, so I don't know if you read them, regarding my agreement to change field names to match the FHIR table field names 'use', 'type', and add 'district'.

**Comment by adunsulag** [comment]
@psoas, yea I read them.  Its on my list of changes to make.

**Comment by adunsulag** [comment]
@psoas I haven't incorporate all of our proposed changes just yet, but I did just push out a PR that you can see an initial stab at this.  I got pulled away to get things finalized for our Clinical Quality Measures certification this Wednesday.  Once that has settled I will wrap this up.

**Comment by psoas** [comment]
I really liked how you are doing it, using the ORDataObject to access the database.  It looks like this makes it easier for ContactService to manage the table relationships without needing to do complex joins.  Why don't I see many other services doing this (particularly InsuranceCompanyService)?

**Comment by adunsulag** [comment]
Thought I would throw this out there as I discovered that other people are having problems with ONC's previous address pieces as well.  Apparently this is all required for the visual inspection of the ONC test since the ONC tools don't automatically validate the previous address information.

https://groups.google.com/g/edge-test-tool/c/zHiDgHBYjnU

**Comment by adunsulag** [comment]
![image](https://user-images.githubusercontent.com/228117/174158173-5aa75197-8ce0-4b0c-8ba9-4c5404f5b185.png)

Here is a snapshot of the most current address list widget.  I've got the period selectors in there, use, and type.  I've also added in County/District as well.
