### ISSUE TITLE
Carecoordination hitting the refresh button after generating a zip file crashes the page

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5487]
Get the white screen of death when hitting the refresh button after generating a zip file 
![image](https://user-images.githubusercontent.com/228117/173624726-b280354d-80ea-4898-aa93-814dfa6ed473.png)

The intent was to reload the search results.  Further investigation needs to be done on why the file white screens.

**Comment by sjpadgett** [comment]
@adunsulag The search by date range from UI is broken. I thought I had this working but something happened during setting up date ranges for API type searches maybe. This is most likely because of time being added to encounters.
Did your last test after v7 branch for testing merge work okay? Did you test date range from UI?
It must have worked during SLI testing, right?
While the subject for this issue is indeed broken, we have new issue of date range is not working and should be a release blocking bug unless I can figure it out soon.
![image](https://user-images.githubusercontent.com/1859985/179132461-6cd3c196-e207-4491-8344-6723686b9078.png)

**Comment by sjpadgett** [comment]
@adunsulag Sorry never mind, I had locale date format set to yyyy-mm-dd so guess need to fix that. This is well known to me and I still forget to ensure it's set so user prob wouldn't have a clue.

**Comment by sjpadgett** [comment]
@bradymiller I am close to fixing this and using locale date format for search. So by this a.m

**Comment by sjpadgett** [comment]
locale display format yyyy-dd-mm

![image](https://user-images.githubusercontent.com/1859985/179157633-76649167-77ac-46f5-9cc4-bceaf398cfbf.png)

locale display format mm/dd/yyyy

![image](https://user-images.githubusercontent.com/1859985/179157843-c765a1f5-bc35-4087-9079-57721d1da15e.png)
