### ISSUE TITLE
release blocking issue with styling

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#5607]
Looks like the styling changes have caused systemic changes to the light theme.

For example, the title labels in the tabs not selected are lighter now:
![image](https://user-images.githubusercontent.com/278968/179339327-6a49861d-7c12-434f-9036-ff37e08c752e.png)

And it is really obvious in the About menu where the buttons/links all have essentially gone away:
![image](https://user-images.githubusercontent.com/278968/179339418-49b02869-6f91-4ecb-903d-218b9c5523dd.png)

Here is what happens if hover over the user manual button:
![image](https://user-images.githubusercontent.com/278968/179339350-0c4e58b4-4830-4b95-9247-276685487aa4.png)

Regarding colors, may make sense to completely back out of those related changes in the styling and then just hard code the color where it was specifically needed in the address form stuff. Or else risk putting out a release with systemic color/contrast issues and seems quickest way to fix it.

**Comment by bradymiller** [comment]
another oddity here where can't see the group labels in new patient gui:
![image](https://user-images.githubusercontent.com/278968/179339480-72455510-8d53-45ac-bd50-77a8fa0303be.png)

**Comment by bradymiller** [comment]
btw, confirmed above issue in the development demo (color themes are fine but light isn't)

**Comment by bradymiller** [comment]
also btw, I am going to try out my suggestion above (fingers crossed :) )

**Comment by psoas** [comment]
@bradymiller  @sjpadgett 
Or, you could have fixed the error in "style_light.scss" to allow us to import "default-variables".

Insert 2 lines before the import:
```
$gray: #6c757d;
$secondary-color: #6c757d;

@import "../default-variables";
```

But, I know that you don't have time to test it.  Maybe, we can try it after the release.

**Comment by bradymiller** [comment]
@psoas ,
default-variables does a lot of stuff and mangled the light theme (was basically not usable). Recommend working on this for next release/patch in master branch to ensure it gets a lot of testing.

**Comment by sjpadgett** [comment]
Brady's correct. Light, Dark, Solar and Manila are handled very different than our color themes. Robert and Tyler were purposeful doing this. Some of the existing variables are duplicated and difficult to follow so Brady's last fix should be okay imo. Originally at one point the default-variables were patched out from including in light theme scss because regardless of the theme being compiled, the base BS theme has the color utility default color variables included prior to theme builds.
I showed the correct way to add the new color across all themes by adding to navmenu.scss.
However, the way we have now will be fine.

Stephen doesn't work on Sundays as it is family time. I'll be happy to look at the contact issue once I figure out the issue!
