### ISSUE TITLE
Lit js framework

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#5612]
After finishing a PoC project, [Lit](https://lit.dev/playground/) seems to be a compelling choice for our requirements to let server manage business logic and devices manage user interface. 

Has anyone explored it as a flexible [templating engine](https://lit.dev/playground/#sample=examples/expressions) instead of Smarty or Twig?

**Comment by sjpadgett** [comment]
First I've heard of it. From first impression it appears to make implementing web components straight forward and manageable.

I'm looking to continue work on the portal document/form templating design and rendering. Currently I use custom directives in a substitution fashion on rendering for various components. What I'd like to see is ability to create forms using canned custom templates to drag/drop onto a grid layout.

Since I'm currently looking into implementing FHIR Questionnaire and QuestionnaireResponse too hopefully finding some sponsors so I can make this a team effort, I've been looking at some available NIH tools to leverage: https://lhcforms.nlm.nih.gov especially for FHIR Smart apps. So whatever I do with templating, I need to make as universal as possible.

Thanks for sharing. I don't know how the community will react to yet another templating library however, I have an open mind and believe one should use the tools that best fits with the endeavor. The problem as always with introducing new dependencies is life cycle and maintainability going forward.

**Comment by mdsupport** [comment]
@sjpadgett, Lit is successor to Polymer - both public domain releases of Google's UI framework. Lit is likely to have better longevity and relevance than any of the js frameworks.

Our PoC was related to #5300 since the [processor engine](https://github.com/lhncbc/lforms) is also available as a web component. Litelements then provide base class for handling these. So it seems to be match with crying need for skills renewal.

The reference to templating (just one aspect of Lit) was to see if anyone has already tried it and found issues. We have been using crude, home-brewed templates forever as part of the basic belief that core role of a server is to manages data according to business logic while client/connector manages what happens to structured data/information provided by server. But then over the years seen so many ways of getting correct answer for 2+2!

Thank you for all the hard work towards certification.

**Comment by mdsupport** [comment]
To maintain data integrity, all current "forms" can be questionnaire objects with 3 interfaces (in PHP terms) - self, patient and partner. Then the weight can be tagged with different LOINC codes like 3142-7 (stated), 8350-1(with clothes) etc but stored centrally for a chart display. This approach will replace layouts and most, if not all, fields in "forms" that are observations.

From storage perspective, self (clinicians) updates can be direct but other responses can be queued as documents and then have other processes incorporate the relevant values during assessment step of workflow.

**Comment by sjpadgett** [comment]
@mdsupport I don't think we are on the same mission but could be wrong.
My focus is toward patient reported outcomes that will mainly end up in analytics for CDR. A CDR I'd hope to see evolve using AI and/or ML.
I agree from a storage POV storing as objects along with the object supporting meta data is a way to go. For questionnaire forms this is certainly ideal. However for responses it would become intense on searches, sorts or deriving statistics against individual answers w/o pulling in the answer objects and parsing. Questionnaire history would require a little thought.

I haven't looked recently but I believe, at least with MariaDB, JSON object support has improved. Problem is though, I believe MySQL and MariaDB has diverged in how JSON is supported. I'll need to investigate more.

If I get what you're saying, you look more to questionnaires becoming more central across all form requirements for OpenEMR.
Am I missing your point?

At any rate, I am going to open a developer forum thread on FHIR Questionnaire and response. It'd be my hope this will help organize and develop a consensus of how best to initially implement these resources. 
However we look at it our next logical step for our APIs is implementing insert, update and deletes. This presents a hard fact of security concerns and how we audit and have a human involve with any patient data changes. For questionnaires this doesn't pose as much of a security concern as other patient data changes might. At least concerning PRO.

I look forward to any and all input you would like to share and hopefully we can make this fun in the end.

**Comment by adunsulag** [comment]
@mdsupport I played with Polymer 4 years ago and at the time it had lots of changes that kept breaking things and browser support was spotty.  I eventually had to move away from it and used angular2+ for my frontend component infrastructure as the web component technology was not ready for prime time.  I'd be concerned about using lit due to the same issues but a lot can change in 4 years.  

The challenge in my opinion is that due to resource constraints OpenEMR needs to take a 5-10 year horizon on technology choices as there's just not a large enough development team in the community right now to replace / upgrade the frontend technology choices that are selected. That makes choosing frontend frameworks a challenging endeavor unfortunately.  

If the browsers have improved their web component support then perhaps that no longer becomes an issue due to the abstraction that web components provide, but I personally would want to play with it for quite a while in order to deal with issues such as component bundling, shadow dom css selectors, web component styling scopes, different browser behavior for template processing / injection.  Those were the problems I kept running into when using polymer as implementation was inconsistent and constantly changing especially when it came to styling and shadow dom stuff.  I only spent a few months on it but I knew people that got burned heavily when google completely replaced its shadow dom architecture in chrome.

**Comment by mdsupport** [comment]
@adunsulag Thx for sharing the experience. I think migration from pre ES6 was messy for the browsers. Hopefully lit will be ok for our use of limited components.

I understand your perspective re. choice the technology for at least couple of major releases. Still it would be good for the project to make a/any choice and work towards building libraries that make its use in subsequent development a no brainer. Otherwise every new developer adds to the chaos making even small maintenance into a major task.

**Comment by adunsulag** [comment]
@mdsupport I agree, I'd actually like to do a phone call with you sometime and pick your brain as I think that's very much a need and see if we can standardize on a decent library framework even if we take over one of the current frameworks, fork it, and own it.

**Comment by mdsupport** [comment]
@adunsulag That would be great. It will be after mid Sept when I return from my Covid revenge travel. Will try to put together something in the meanwhile. Cheers.
