### ISSUE TITLE
Custom Modules support autoloading without needing composer command

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5643]
Currently its cumbersome for someone to install a module that uses namespaces and autoloading.  Module writers currently have the option of using requires on all of their code to deal with the autoloading issue, or having to instruct their clients to add the module to the composer.json and run the ```composer dump-autoload``` command.  This requires the right version of composer to be installed, for the vendors and composer.lock file to be writeable and a number of other issues.  

What we'd like to have happen is a mechanism in place that allows module writers to just unzip a compressed module file into the OpenEMR installation and have the system be able to load the module classes without having to run any composer command.  We need to make sure this mechanism does not enable any PHP code execution until the end user has installed the module from the OpenEMR Manage Modules page (IE don't change the current mechanism of reading from the info.txt file to grab the module name).

There's been several debates about allowing OpenEMR users to autodownload modules and install them automatically on OpenEMR.   However, there's all kinds of security risks to allowing something like that to happen.  This issue is only to cover the use case of an end-user that has control of their server and can extract a zip file onto the filesystem to mitigate any remote code exploitation problems.  

If we figure out a way to securely auto-install a module we can handle that in a different issue.

**Comment by juggernautsei** [comment]
Here is my comment, for what it is worth. I have not been using the required statements all over the modules that I have built. I have taken the advice you gave me and built my own namespace within the module. 
I use composer a composer entry to set up autoloading of all of my classes. The only place I have to use a required statement is in the openemrbootstrap.php file. But after reviewing your skeleton code. In my next iteration of modules. I will get rid of that for the bootstrap class that you have in the skeleton. I treat all of my modules builds as self-contained programs. I one on my last projects. I built a simple router into the module to deliver pages needed for display. Now that I have lost focus on the comment purpose. Let me get back to what you are doing.

I understand you want to make the bar lower for module developers to get going in creating modules. That is great. But some of this comes down to how much does the module building know.    

I will put in an issue that I am having with building modules. I have voiced this issue before with you. I have tried to fix it on my own but can't get my head around how the code works.  

The issue is that there are a limited number of places that the top-level menu can be added to by the injection process. I have searched the code but can't find where the limitation occurs. I know I am missing the big picture view of how the menu augmentation works. (this is the part where I do the self-deprecation).  My wee little brain has reached its knowledge limit. (Wizard of oz reference now). I went to the wizard and asked for a bigger brain (the wizard is YouTube). But he stem cells for me. =^(.

Anyway, hope this was fun for you too!

**Comment by juggernautsei** [comment]
I do all of my module class loadings within the module itself before zipping it up. When the module is unzipped. There is no need to run the composer because that was already done and set within the module itself. No need to run the composer from the OpenEMR root.
When my module starts life, I build the composer and autoloading first. Once I do that, I have never had to worry about the class autoloading anywhere in my module. All I need is the require_once dirname(__DIR__) . "/vendor/autoload.php". All of my dependences are taken care of within the module with no need to disturb the root composer.

**Comment by juggernautsei** [comment]
Download and go through the code in this module https://sourceforge.net/projects/openemr-text-modules/. If you install it. It will run without having to run the root composer command.
Look at the folder text-messaging-app/public/index.php you will see.

require_once __DIR__ . "/../../../../../globals.php";         (I was being lazy here)
require_once __DIR__ . '/../../vendor/autoload.php';    (and here, need to go back and fix this)

use Juggernaut\App\Controllers\StoreTexts;
use OpenEMR\Common\Crypto\CryptoGen;
use OpenEMR\Common\Logging\EventAuditLogger;
use Juggernaut\App\Controllers\apiResponse;

The purpose of the API is to get replies back from the patient into the system. 
I think I have beat this drum enough.

**Comment by mdsupport** [comment]
We approached modules differently. You can glance at [this branch](https://github.com/mdsupport/openemr/tree/mdpubapps) that implements a dictionary based approach implemented through [this repo](https://github.com/mdsupport/mdpub). At its core we define various objects in a table and their interdependence in another table.

Zend or other php frameworks rely on directory based mechanisms to avoid dependency on a database. This application on other hand cannot exist without the database(s). So never understood the reasons for not leveraging database capabilities to the max.

Sorry for the brief post.
