### ISSUE TITLE
Patient Photograph on Calendar

### ISSUE THREAD

**Issue by QueenLinux** [openemr/openemr#568]
The patient photograph that pre-exists in the patient Documents be able to be viewed (with an option) on the Calendar tooltip when you hover over a patients name. Because the method 'goPID' exists in the calendar templates, theoretically, using that to pull the patient ID (Which it already does), along with the top patient photograph shouldn't be particularly hard. Does anyone at this time have any suggestions?

**Comment by mrpenelope** [comment]
Also, this is meant to be marked as enhancement.

**Comment by bradymiller** [comment]
This would be very nice and making it an option is a good idea. So, then if hover over it will see name,age,dob, and picture if it exists. Are you planning to do this?

**Comment by mrpenelope** [comment]
Yes, Mr. Miller, I do plan on this, as this was on my mind for the coming days on the project. Any tips you might have for someone who is trying to familiarize themselves with that method?

**Comment by bradymiller** [comment]
Recommend having a got at it and see what happens/breaks :)
(and always feel free to post the code here no matter the outcome)
The pitfall to avoid is to not call the image directly since a properly configured OpenEMR will not allow direct access to the stuff in documents dir via Apache (for good reason).

See here for good example on how to grab the image:
https://github.com/openemr/openemr/blob/aca3dd6ec9bf5ea873bea97d5528343ee161bbd1/interface/patient_file/summary/demographics.php#L120-L151
(note how it uses /controller.php to collect the file)

See here for a bad example:
https://github.com/openemr/openemr/blob/aca3dd6ec9bf5ea873bea97d5528343ee161bbd1/interface/patient_file/summary/demographics.php#L1314
(this direct call to a file will not work on a properly secured OpenEMR instance)

**Comment by bradymiller** [comment]
Hi everybody,

Regarding the non-optimal example linked above, is this something that can be removed, or is it being used?

**Comment by bradymiller** [comment]
Quick aside,
I don't mean to state the non-optimal code above is bad code. It's just older code and this was how we used to access things in documents until started using the more secure controller.php calls.

**Comment by bradymiller** [comment]
Just for reference, there is a potential related project for placing patient pic (so can collaborate on the process of collecting and showing the image):
https://github.com/openemr/openemr/issues
