### ISSUE TITLE
Appointment APIs need to handle recurring appointments

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5716]
Brady mentioned that in our AppointmentService we are not handling the recurring appointments correctly.

He stated:
The functions that collect the appointment(s) will break on recurrent appointments (this is because a recurrent appointment takes up only 1 row in the table). There is a very complicated function call that deals with this (in past there were many places where direct calls to the table were breaking on recurrent appointments which were then consolidated to use this function) at:
https://github.com/openemr/openemr/blob/master/library/appointments.inc.php#L366

We need to figure out how to handle the recurring appointments and how to present a uuid that represents the subsequent appointments.

**Comment by bradymiller** [comment]
Assigned this high priority :)

**Comment by mdsupport** [comment]
A complicated function is needed because PostNuke saves PHP objects in database fields. As a result only PHP code can reconstruct the entire series to return valid appointments. Also be aware that other fields not included in the PHP objects like appointment status are applied to entire recurrence series.

Project needs to seriously rethink value of recurring appointments. Most of these are really legacy requirements when the clinical reminders were not available - e.g. annual physical, 8 week follow up etc. During an encounter patients will at the most confirm next recurrence.
