### ISSUE TITLE
After editing the encounter the date is set to 00/00/0000

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#5839]
### Describe the bug

When we edit and encounter the date is changed from the original date to all zeros and a negative number is displayed in the chart

### To Reproduce
![image](https://user-images.githubusercontent.com/834958/195456544-aa26b460-9f98-4158-9cdb-bb79f0f0b877.png)

![image](https://user-images.githubusercontent.com/834958/195456743-63418042-9c8c-4a73-8862-2c6e08653155.png)

1. Open previously saved encounter
2. Save
3. 

### Expected behavior

Show the same date and time as previously saved.

### Client configuration

- Browser: Firefox Chrome
- OpenEMR version: 7.0.0(1)
- Operating system: Ubuntu 20.04.5

**Comment by stephenwaite** [comment]
hi @juggernautsei , what are the time and date locale settings in Globals?

**Comment by juggernautsei** [comment]
mm/dd/yyy is what is selected.

**Comment by juggernautsei** [comment]
I checked the database and when a new encounter is saved for the first time. The date is all zeros.

**Comment by stephenwaite** [comment]
huh, can't reproduce on the main demos running patch 1, anything else in locale that is different?

**Comment by juggernautsei** [comment]
Nope it is still happening when the encounter is being edited.

**Comment by tsimonq2** [comment]
This happened once on our EMR instance. The best thing I can think of is that we were using pure MySQL on the original server and MariaDB on the new server. While they *should* be compatible, perhaps something with date formatting.

If this is helpful, I have this in our playbook to verify all encounter dates are correct, so if this issue comes up again for us we can test a fix: `SELECT * FROM form_encounter WHERE date BETWEEN "0000-00-00" AND "2014-01-01"`

**Comment by juggernautsei** [comment]
Thanks for the advice @tsimonq2. 
I found the issue. On update the date format is 2022-07-13 1:00 am. This is the incorrect format to insert. Now, gotta figure out how to fixt it.

**Comment by stephenwaite** [comment]
Fixed in #6103
