### ISSUE TITLE
Procedure Order in encounter menu should move from Admin menu item to a new separate menu item called Orders.

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#5948]
(part of video tutorial)
Procedure Order in encounter menu should move from Admin menu item to a new separate menu item called Orders.

**Comment by mdsupport** [comment]
It will help the project to align itself with HL7/FHIR terms and contexts. Even if underlying code/tables are not refactored in minor fixes, at least the UI can establish a bookmark for future updates. From that perspective, current "procedure order" in this project is FHIR [ServiceRequest](https://www.hl7.org/fhir/servicerequest.html) with [ServiceRequest.intent](https://build.fhir.org/valueset-request-intent.html)=order and [ServiceRequest.category](https://build.fhir.org/servicerequest-definitions.html#ServiceRequest.category)=Laboratory Procedure.

For the developers, the ServiceRequest structure is a great hint for organizing a unified "Request"/"Order" screen.

**Comment by sjpadgett** [comment]
I believe the current procedure order is way to busy and perhaps needs to be broken into lab/electronic orders then separate clinician orders that are not electronic.
Current issue is we need a better or more central valueset since codifying is of import. Clinicians from my experience hate doing codes and will generally skip if allowed.
This is the current problem I have with collecting data required for such items as CCDA/FHIR or just dealing with codes in general.

**Comment by mdsupport** [comment]
@sjpadgett, I think until openemr data structures align with [Level 3-5 entities outlined on FHIR welcome page](https://build.fhir.org/index.html) these struggles will continue. While I understand happiness of clinicians to create random fields in forms/layouts/modules, as far as US practices are concerned project needs to require codes for every Level 4 element. Days of replicating paper notes in EMR and asking the recipient to figure out relevant details are gone.

To be clear, this issue(#5948) is UI specific but if data structures reflect a set of business processes, the UI needs to follow suit.
