### ISSUE TITLE
Patient image does not refresh after image deletion

### ISSUE THREAD

**Issue by gutiersa** [openemr/openemr#5985]
### Describe the bug
Deleted image continues to show up in left upper corner patient image area.

write concise description of what the bug is:
I had forgotten to crop a patient image prior to uploading it into the "patient photograph" in the documents section. So, I cropped the image and reuploaded it. I also deleted the un-cropped image. But, while the correct image shows up in the right hand side in the dashboard, the uncropped image is what continues to show up in the upper left bar. I thought this was a bug, but I am not able to reproduce this behavior in the demo.  I am using the v7 patch 1

Funny enough, this only happens with my data in firefox. In chrome the correct image comes up. This is very strange.
The demo has the correct behavior with both browsers.

### To Reproduce

delete image and reupload.

### Expected behavior
the correct image should appear at both patient image location.

### Client configuration

- Browser: firefox
- OpenEMR version: 7.0.1
- Operating system: windows 10

**Comment by robertdown** [comment]
The Patient Banner Bar would not be automatically refreshed upon deletion/upload of a photo once the patient in question has been loaded.

To force the PBB to refresh close the currently opened patient and open that patient back up.

Try the following steps to see if your desired outcome can be accomplished:

1. Open a patient
2. Navigate to the Documents section
3. Upload a patient photo
4. Close the patient (by clicking the ```x``` next to the name on the Patient Banner Bar
5. Re-open the patient
6. Navigate to the Documents section
7. Upload an _updated_ patient photo
8. Close the patient (by clicking the ```x``` next to the name on the Patient Banner Bar
9. Re-open the patient

**Expected behavior**: Patient photo in the PBB should be the _updated_ photo

**Comment by gutiersa** [comment]
Thanks for your reply. I have actually tried all of the above. The only thing I have not done is clearing my firefox cache. I suspect that may be the issue. I will lose a lot of stuff if I do so. I am not sure what to do!
