### ISSUE TITLE
Keep getting logged out of demo

### ISSUE THREAD

**Issue by vertigo220** [openemr/openemr#5991]
### Describe the bug

Keep getting logged out of demo. Just tried it and within ~5 minutes I got logged out twice. Obviously not trying again.

### Client configuration

- Browser: Brave 1.45.127
- OpenEMR version: ?
- Operating system: Win10

**Comment by vertigo220** [comment]
Ok, I guess you don't want users and support. Glad I realized that before wasting more time on this.

**Comment by robertdown** [comment]
Hi @vertigo220,

Thank you for reporting the issue. Unfortunately, this repository is for issues specific to the code base of OpenEMR. As our demos are heavily used and open to anybody all using the same credentials, we do have some issues from time to time. I would recommend trying again tomorrow, our demo's are rebuilt nightly. If the problem persists, consider reporting the issue on our community forums to see if others are experiencing the same issue.

In addition, if you would like to run a demo locally without other users, our Docker setup is a quick way to get up and running with your own local install.

I could not replicate this issue in 7.0.0 patch 1 or our on master branch from git, leading me to believe this problems were not related to the codebase. We will monitor the demos tomorrow to see if any other users report a problem.

**Comment by bradymiller** [comment]
hi @vertigo220 , May also be the Brave browser. If can replicate it on Brave again, then would see if can replicate it on Chrome/Firefox. If it's Brave, guessing there is something in it that kills cookies (and as a result sessions) after limited time.

**Comment by bradymiller** [comment]
Confirmed the bug in both firefox and Brave on the demo (as an aside, just tried out the Brave browser. pretty nifty that it can go right to Tor browsing; i've always wanted to get a OpenEMR demo served on the dark web and this may provide me some incentive to figure out how to do that :) )
I am pretty confident it is the mechanism that resets the password hashes every 5 minutes:
https://github.com/openemr/demo_farm_openemr/blob/master/demo_build.sh#L984
(we had to add this in the distant past since an entity was running some sort of automated script that was changing all the user passwords in the demos every hours or so. however what has happened is that the demos are reset to an outdated hash; so when a user logs in a modern hash is created; but then every 5 minutes the hash is changed back; and every time a openemr script is run it makes sure the hash in the session matches the hash in the database; so it breaks)
Gonna comment out this feature in demos and 90% certain that when the demos reset tonight they will work :pray:

**Comment by mdsupport** [comment]
Why not have demo script set few session variables that are checked by standard code? One possible setup would be : 

1. Demo script injects either $_SESSION or $GLOBALS variables like : 
   - installation_role = 'demo'
   - demo_users = ['admin', ...]
   
2. User maintenance script[s] check for installation role and skip password updates for demo_users

3. Extend same approach for other malicious or ignorant actions that are known to render demos useless for a day. This could be use of layout editor to alter patient_data structure.

**Comment by mdsupport** [comment]
Or more generic approach of a installation role module can be implemented. That can allow clean, extensible code for ippf, demo or whatever - e.g. inpatient or behavior related to practice specialties.

**Comment by bradymiller** [comment]
ok, demos are working (my initial fix broke the bash script which then had to fix with another fix :)  https://github.com/openemr/demo_farm_openemr/commit/a393d378103225196f7b5a16065a8513e1e2ccb4 )

thanks for the report @vertigo220 !!

Agree on those recommendations @mdsupport since the current password resetting mechanism won't work when users modify hashing settings in globals.
