### ISSUE TITLE
Patient Modernization

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#624]
Starting work on the Patient entity, repo, and service.

Follow along at https://github.com/robertdown/openemr/tree/patient-modernization

**Comment by bradymiller** [comment]
Won't this be tough since this table is basically fully customizable via the layouts engine?

**Comment by MatthewVita** [comment]
@bradymiller ah, good point. Any table that can be customized on the fly won't be possible in Doctrine. The best we can do is separate the business logic from the view in a PatientService.php, which is still elegant from a code perspective.

**Comment by mdsupport** [comment]
@MatthewVita & @bradymiller  This [sf discussion](https://sourceforge.net/p/openemr/discussion/202505/thread/8abc2bec/?limit=25#9166) is one of the constant issues with customizable tables.  

I would suggest we use doctrine and/or standard techniques for released codebase - specially for central entities like patients.  A fix would be to use some mechanism that will disable delete option in layout engine since users can always hide these fields.  As an example, if doctrine can return the list of fields it is configured for patient_data, that can be used to disable deletion.

**Comment by robertdown** [comment]
It looks like a certain number of fields are hard coded and essentially required - could those fields be used as a base Entity?

**Comment by mdsupport** [comment]
I think all fields included in standard installation should be part of base entity.  It should be responsibility of the developer adding new fields to modify the model if necessary.  Otherwise they would be simple input/output fields with no model support.

In the long run (at least for mySQL,) use of json data type needs to be considered since current logic drops the column regardless of populated data if an inexperienced user deletes an any field.  But that's for a later day?

**Comment by MatthewVita** [comment]
I would say we can approach this problem in two stages:

1) Employ a nice service class to handle all of the business logic via traditional handcoded SQL.

2) Use a standard Doctrine entity/repository for all columns and use a NoSQL approach with the custom "columns" (perhaps we can put a `JSON` string in a `TEXT` column called `custom`). I would say forcing users to go with MySQL 5.7 to get native JSON data type isn't a great idea (maybe in a couple of years it will be more common). I've had to do something like this in the past with MSSQL and an XML column... as long as the column doesn't get too out of hand, it's a decent solution!

-m

**Comment by MatthewVita** [comment]
With that said, stage 1 is much more straightforward. Stage 2 is a big project and we'll probably want to harden the overall feature to eliminate some of the issues that mdsupport mentioned!
