### ISSUE TITLE
The client app should avoid re-authenticate during it’s launch within OpenEMR

### ISSUE THREAD

**Issue by YuvaReddy** [openemr/openemr#6525]
### Describe the bug
In OpenEMR, registered a client app and tried to launch it with in the hosted open EMR instance. Everytime during the launch it is redirecting to login page for user authentication instead of using the launch context of logged in openEMR user. It should request additional login and use SSO, similar to other EHR systems.

### To Reproduce
1. Register a client app (below is sample screenshot)
![image](https://github.com/openemr/openemr/assets/42370221/86f8af86-44eb-4632-98cf-97b87a2662ee)
2. Try to launch it from any patient demographic/dashboard (below is sample screenshot)
![image](https://github.com/openemr/openemr/assets/42370221/31af8113-335b-401d-86aa-6f0e09303f5f)

### Expected behavior
Current flow: Launch page → Login page (manually enter login details and Authorize) → Redirect page
Expected flow: Launch page → Redirect page
Can we bypass this authentication as the user have already authenticated into the system?

### Client configuration
Using Open EMR version 7.0.1 version Linux zip ([link 1](https://www.open-emr.org/wiki/index.php/OpenEMR_7.0.1_Linux_Installation))
Client App using FHIR-client JS library ([link 1](http://docs.smarthealthit.org/client-js/#smart-api))

**Comment by adunsulag** [comment]
Are you expecting the login bypass if the offline_scope is requested?  OpenEMR doesn't currently support the online_access scope and we assume most applications will request the offline_access scope to avoid showing the scope authorization screen to users every time the app launches. 

As the offline_access scope is a very sensitive scope to grant (since it lasts for a year) we made the decision to force the login screen due to the higher security risk granting that scope gives. We debated this a lot when we built this a few years ago, we decided to force the login screen as we felt that most applications will require the offline_access scope.

I'm interested in your experience with other EMRs,  do they let you get the offline_access scope w/o requiring a login?  I was under the impression that Cerner required it but perhaps that has changed now.  I don't know if Epic bypasses it or not.

Or are you expecting the user to have to do the scope granting screen each time they launch the app since their authorization token only lasts an hour?

Please note that we would need to check with our certification lab to see if making a change like this requires re-certification.  If it does require re-certification on our g10 FHIR interface, then it will likely take some time to bring this change into the codebase.

**Comment by YuvaReddy** [comment]
Hi @adunsulag 
Our main moto is to bypass the second authentication, be it for online or offline scope. We are looking at the client application inside EMR, not a standalone application. We have been conveyed that EPIC and Athena doesn't require the second level authentication, we were able to crack it in the EPIC sandbox too.

**Comment by adunsulag** [comment]
I've been doing some work in adding a new smart app launching intent inside the encounters form and I've come across a use case that forces the issue of why we want to skip the authentication screen the first time.  In previous SMART apps we figured an app would only require a user to authenticate at most once every three months if they were requesting the offline_access scope.

However, in working with the launch/encounter scope and our OpenEMR encounter launch intent I ran into the problem that the spec requires that we bind the access token to the specifically selected encounter without being able to select a new encounter. If you want to select a new encounter (or a new patient when using launch/patient) then you HAVE to reauthenticate and reauthorize the smart app in order to get a new access token bound to the new context.  This becomes a very painful experience if you are switching between multiple encounters for a single patient.

I'm going to push up a draft PR that will enable OpenEMR administrators to turn on this functionality to skip the authentication / authorization piece on a per app setting.  Since this has an impact on our certification piece the functionality will be turned off by default but can be enabled in the globals.  Until we get clarification from our certification partners, installations needing to run the certified product should avoid turning this feature on.
