### ISSUE TITLE
Vitals -  vitals history section always shows labels in english

### ISSUE THREAD

**Issue by macomeza** [openemr/openemr#6858]
### Describe the bug

I am translating OpenEMR to spanish latin america, but I have noticed that vitals history shows its header in english, as well as a back to top and a warning (Patient has no other vital history to display) when you create a patient first vitals record.

### To Reproduce
![image](https://github.com/openemr/openemr/assets/77448377/11b41523-0c42-491c-a43f-4d71f2d6692f)

### Expected behavior

Be able to translate labels to spanish.

### Client configuration

- Browser:Chrome
- OpenEMR version:7.0.1
- Operating system:Windows. Server running Ubuntu 22.04

**Comment by bradymiller** [comment]
Hi @macomeza ,
You can add those constants in your OpenEMR instance (Admin->System-Language) and then do the definitions:

(at some point we need to do an official update to pick up these relatively new constants, but we are a ways from doing that since need to also update that script to find these new constants in twig format)

**Comment by macomeza** [comment]
I have just get to hang of it! Thanks!
