### ISSUE TITLE
Restyle front dashboard cards

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#6883]
There is a hundred ways this can be done however I think the general consensus is, three top cards with prescriptions on it own row. 
Really only minor adjustments to code as most everything is there, thanks Robert!

I decided to reduce Allergies and Issues to col-3 and medications to col-6 for readability.

![image](https://github.com/openemr/openemr/assets/1859985/4ac7c93f-b477-43b9-914f-b73d25237dd8)
![image](https://github.com/openemr/openemr/assets/1859985/82652cd6-de19-420f-8fff-916c7632d2be)

Of course there may be other opinions so please let me know soon as I'm moving onward:)
btw: Thanks for the Allergy/issues card populate fixes @bradymiller !

**Comment by sjpadgett** [comment]
It'd be nice to have a collapse all button!

**Comment by bradymiller** [comment]
Looks much better!
- Users generally will keep same core tabs open (so the persistence mechanism should be enough)
- Speaking of expand/collapse, are we ok in assuming that users will no that the expand/collapse mechanism happens when click on the titlle of the widget (in past, there used to be a icon(expand/collapse depending on state) that showed this was case)
- One thin i noticed, if that click on that enlarge button in top right it really expands the real estate, but is is no longer persistent (pretty sure that used to be persistent in the past).

**Comment by sjpadgett** [comment]
I'll try to address concerns

**Comment by mdsupport** [comment]
Bootstrap UI component to handle this is [Accordion](https://getbootstrap.com/docs/5.3/components/accordion/). Until 5.x is brought in, a simple JS can simulate basic idea of up/down arrow as a placeholder for full features to come later.
