### ISSUE TITLE
Quest lab result display specimen date

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#6917]
### Describe the problem

Lab results do not show the specimen date. 
Ron at Quest asked to display date under specimen on the lab results. 

### Describe the solution you'd like

The date to show where the specimen column is located on the lab results page.

**Comment by sjpadgett** [comment]
Is the specimen day included in the results HL7?
Also, is it part of quest spec? It seems new because I don’t recall needing it for when I certified.

**Comment by juggernautsei** [comment]
I did not look for it. I took the shortcut out. I am too lazy to go looking for the specimen date when the collection date was right there. I will ask Ron if the specimen date is contained in the result file and where.

**Comment by sjpadgett** [comment]
I think my point is that a specimen date is part of the order and is only useful to the lab and not the results being reviewed by a doctor thus no need for the specimen date because why would the clinician need to know that date? I would think they'd most liking refer to the order date. So, why is this Quest engineer requiring this information be part of the results when that information is part of the order? I'm just saying some of these guys will run you ragged when it either is not part of the spec or it's is something arbitrary. Just saying, know if it is in the spec or give you a darn good reason why OpenEMR needs to display this useless data! Just saying sometimes a little pushback is a good thing. Not saying beat the guy up or anything-)

**Comment by sjpadgett** [comment]
Sorry Sherwin, I got a little carried away that last post. It's a pet peeve of mine when doing any interop turnup where the distant try to get you to do things not required.
