### ISSUE TITLE
error message on changing table in demographic forms

### ISSUE THREAD

**Issue by ruthkonyn** [openemr/openemr#6984]
### Describe the bug
admin/forms/layouts - demographics. Change a list. An error message is displayed

concise description of what the bug is:
if one clicks on the list field, to change the list to be used, an error message is displayed in a pop up window in the 'select list' window. It varies from system to system, examples are 

 `DataTables warning: table id=my_data_table - Requested unknown parameter '2' for row 0, column 2. For more information about this error, please see http://datatables.net/tn/4`
and
`undefined
URL: undefined
Line: undefined Column: undefined
Error object: undefined`

If one clicks 'ok' to each error message then one is finally able to change the table

### To Reproduce

![image](https://github.com/openemr/openemr/assets/49122477/91eead70-b087-47c6-8c5b-ff5caf29c6a5)

1. choose menu admin/forms/layouts 
2.  use drop down to choose 'demographics'. 
3. click on a 'list' field to change the list
5. click 'ok' until errors stop displaying
6. procede to change the list as desired

### Expected behavior

one should be able to change the list without error messages displaying first

### Client configuration

- Browser: firefox
- OpenEMR version: 7.0.1(1) and  7.0.2-dev
- Operating system: linux 

possibly other OS and browser, i can find out if necessary

**Comment by sjpadgett** [comment]
This is easily verified but I've been unable to solve taking a cursory look. I will say it is prob a null being sent to datatable. Prob a past PHP warning/error fix with a coalescing operator using a null instead of string. Just a guess but I'm setting this issue to release blocking as I don't know if I can fix soon and with LBF being used by many we need to fix before release.
