### ISSUE TITLE
not_due not working in the Clinical Reminders widget

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#7200]
not_due not working in the Clinical Reminders widget (just shows empty string instead of `Not Due`)

**Comment by hanksterr7** [comment]
@bradymiller 
The Clinical Reminders widget (I believe) is not supposed to show rule execution instance that are "Not Due". The Clinical Reminders detail page does show these results, and previously was showing an empty string instead of Not Due. 
I see your fix (a missing single quote). Looks better than what I had implemented. I will test yours and confirm

**Comment by hanksterr7** [comment]
I tested the fix (adding the single quote). In the Clinical Reminders Details display, the fix now causes Not Due to show in green, instead of showing an empty string. But this text (and color) displays regardless of whether the rule status is actually not due, due soon, or due. The correct status, and status color, displays in the Clinical Reminders widget in the dashboard.
Applying the fix to my code causes the correct status to show in all cases in the Clinical Reminders Details display, although the color remains black, and an extra ! icon shows when not due. This is because I was setting the status to Not Due instead of not_due as an attempt to solve the empty status display. Reverting my change, so I set status to not_due, causes proper text and color to show in all cases in the Clinical Reminders Details display. I will send in a new commit with this change
