### ISSUE TITLE
List Edit has a save limit of 40

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#7694]
### Describe the bug

I'm pretty sure we have lists that are greater than 40 items however when matrix added the pagination to list editor a 40 row limit was placed on the page view size. Not knowing that the editor save routine deletes all rows in the list first and then saves the rows that are posted from the current page thus missing the whole list size.
This was brought to our attention by a forum users post maxing out fee sheet visit type cpt4.

### To Reproduce
save a list longer than 40 rows. Only the 40 shown in UI view are saved.

### Expected behavior
Not sure what I'll do. Maybe if list is longer than 40 rows, expand the list before post. This has inherit issue if list is too large for browser to handle.
The actual issue is we took the easy route(no judgment by me as I'm the laziest) in saving lists by just rewriting the entire list. Maybe I'll change to an update/insert sequel query instead.

I promised myself to stop taking on issues but it's simply not in my nature to ignore once I see them so remember to click the donation button to encourage me!:)

### Client configuration

- Browser:
- OpenEMR version: all back to at least v6
- Operating system: all

**Comment by mdsupport** [comment]
How about following changes to UI with minimal coding effort -
1. Remove 'Save' button at the end.
2. Add js code to disable updates to all editable controls in the displayed list entries.
3. Add js code to offer 'Change' and 'Delete' buttons on hover. Or switch to edit on click.
4. Let js code enable all editable controls for a single record. Add 'Save', 'Delete' buttons to the end of `<div>`.
5. js code to make sure only one editable record is active at a time.
6. Modify the form update code to act on a single record rather than 'delete and recreate'.
7. Refresh the list after every updates to reflect order changes.

**Comment by sjpadgett** [comment]
Thanks @mdsupport I will prob get to this today and I'll update here...

**Comment by sjpadgett** [comment]
It look like I made a mistake assuming that if fee sheet had a save limit, so does other list types. Not true and normal list save has a pretty good save work flow.
So will work on fee sheet.
