### ISSUE TITLE
feat: Appointment reminder notifications Clickatell Integration

### ISSUE THREAD

**Issue by ChrisOstler** [openemr/openemr#7822]
### Appointment reminder SMS and email notifications don't work

Appointment reminder SMS messages (via Clickatell) and emails (through Google Workspaces account) do not work.  Clickatell no longer supports new customers using the API used for the Clickatell integration, and email reminders use a different email sending configuration that did not work with GMail/Google Workspaces.

### To Reproduce
Configure SMS notification settings and email sending.  Uncomment the exit statements in cron_sms_notificaiton.php and cron_email_notification.php and invoke the scripts.  Configure a patient with contact details, HIPPA opt ins, and an applicable upcoming appointment.  Invoke the notification scripts.

No email or SMS is received.

### Expected behavior
Email and SMS is received after scripts are invoked.

### Client configuration
N/A

**Comment by sjpadgett** [comment]
If you want to test new client I use Secure Messaging instead of running appointment reminders.
Turn Portal on and use Miscellaneous->Portal Dashboard. If module is enabled you should have a Send SMS button

![image](https://github.com/user-attachments/assets/8652540a-ab8c-490d-9f13-175447fc6cd1)

Also sending to clickatell phone should show in log. I haven't been able to test the SMS U.I call/message log since I last tested Twilio two years ago and since I recently put RC SMS back in module so I'm hoping you'll be able to. I'm waiting for one of our users to be approved by RC new SMS capability so I can test and fix if necessary. I quit carrying all these accounts for testing module especially since RC insist on me giving up and reporting my privacy to gov..
