### ISSUE TITLE
jquery 1.6.4 removal

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#820]
Following 4 files use jquery-1.6.4.min.js.  Could someone please direct us to any document/link specifying the reason(s) why current 3-1-1 version (or at least 1-7 or above) should not be used instead?

- [x] interface/main/calendar/modules/PostCalendar/pntemplates/default/views/header.html
- [x] interface/patient_file/summary/create_portallogin.php
- [x] interface/patient_file/summary/demographics.php
- [x] interface/main/left_nav.php

**Comment by bradymiller** [comment]
The only main limitation I have noted regarding jquery is that fancybox is stuck at jquery 1.7.2; so option in those cases is to go to 1.7.2 if wish to get rid of 1.6.4. Also, if the script has other old jquery plugins (like the Administration->ACL), then may be sticky issues. Otherwise, recommend pushing it up and testing it (there are some things that break occasionally). As we bring the standard header class which brings in jquery 3.1.1 and bootstrap throughout the codebase, these old jquery versions will start dropping off :)

**Comment by bradymiller** [comment]
jquery versions:
- [ ] jquery-min-1-10-2
- [ ] jquery-min-1-11-1
- [ ] jquery-min-1-11-3
- [ ] jquery-min-1-2-1
- [ ] jquery-min-1-2-2
- [ ] jquery-min-1-3-2
- [ ] jquery-min-1-4-2
- [ ] jquery-min-1-4-3
- [ ] jquery-min-1-5
- [ ] jquery-min-1-6-4
- [ ] jquery-min-1-7-2
- [ ] jquery-min-1-9-1
- [ ] jquery-min-2-2-0
- [ ] jquery-min-3-1-1

**Comment by bradymiller** [comment]
@mdsupport ,
Got rid of jquery 1.6.4 and expanded this issue to track the migration of jquery to 3.1.1.

**Comment by bradymiller** [comment]
Actually, will close this and reopen issue to make it clear.
