### ISSUE TITLE
Low Cost Medical Devices Search for OpenEMR Integration

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#978]
We wish to provide an affordable and high-quality hardware solution in order to be compliant with an API being developed for OpenEMR. In doing so, less financially-strapped hospitals will become at parity with the "data centric" style of US HIT.

- [x] Investigate the markets
- [x] @MatthewVita to note the eventual documentation style will need to be "documentation" and not "advise".  (see comment https://github.com/openemr/openemr/issues/978#issuecomment-319731395 and the one below it)
- [ ] @TheToolbox to record his unique perspectives on the device testing strategies
- [x] answer Libelium (MySignals) proposal  - Discount until 7/31
- [x] see if Libelium (MySignals) can sell us just the EKG device for testing (no CPU)
- [ ] Look for low cost EKG and Pulse Oximeter/Blood Oxygen devices that are either usb devices or RaspPis that work with cheap Android tablets or Windows netbooks.

For more information on MySignals: http://www.my-signals.com/#what-is-mysignals

Note: This ticket is for tracking Andre and Matthew's work.

**Comment by andremillet** [comment]
although I still have no email reponse, these are the components I asked for:

[ECG Electrocardiogram Sensor PRO for MySignals (eHealth Medical Development Platform)](https://www.cooking-hacks.com/ecg-electrocardiogram-sensor-mysignals-ehealth-medical)

[SPO2 Pulse Oxygen in Blood Sensor PRO for MySignals (eHealth Medical Development Platform)](https://www.cooking-hacks.com/spo2-pulse-oxygen-in-blood-sensor-mysignals-ehealth-medical)

[Blood Pressure Sensor PRO for MySignals (eHealth Medical Development Platform)](https://www.cooking-hacks.com/blood-pressure-sensor-mysignals-ehealth-medical)

**Comment by MatthewVita** [comment]
Awesome! Great work @andremillet

**Comment by MatthewVita** [comment]
@bradymiller let me know if you think the board would be cool with paying for these test devices. If not, I'll foot the bill.

**Comment by MatthewVita** [comment]
It will be a total of $464.78 + shipping... so maybe $500ish

**Comment by MatthewVita** [comment]
BTW, the only way this _wont_ work is if they don't support our ask to bypass this thing:

https://www.cooking-hacks.com/media/cooking/images/documentation/mysignals_software/mysignals_box_small.jpg

...this is their "CPU", but it's not cheap

**Comment by andremillet** [comment]
I think it is worthy to check this link:
https://www.cooking-hacks.com/ehealth-sensors-complete-kit-biometric-medical-arduino-raspberry-pi

there is a 1.0 discontinued kit that works with 4 sensors. may be we can
find cheaper at ebay

**Comment by MatthewVita** [comment]
@andremillet brilliant. I just used the Wayback machine to see the page in an older form and they were asking €450.00 for it, which is a tad costly but reasonable in comparison to the CPU they are offering now

**Comment by MatthewVita** [comment]
BTW, Ebay is a bad idea because we need a strong partner that is _currently_ manufacturing the hardware. If go with the Ebay route, there's only a finite amount left.

Perhaps we can partner with MySignals to see if we can get them to make us these older boards with a nice case. I realize this is very much entering the non-FLOSS arena, so I think it is best to wait on Robert's comments on the ethics of this and then we can maybe continue all of this device work _outside_ of the OpenEMR project (Team Epsilon or just use one of personal repos).

**Comment by andremillet** [comment]
ok. I will keep searching. They seemed to have a strong open source core so
my guess is that it has started as a non-profitable project. If this
'ground zero' can be found, may be we could continue this version, if there
was any in the past

**Comment by MatthewVita** [comment]
It's possible. I'm thinking if we were just some random person on the internet asking for the initial version, they would say no. However, since we can possibly open up a small stream of business from our end user population, they may be willing to talk

**Comment by andremillet** [comment]
see we will soon, my young padawan. 😁

**Comment by andremillet** [comment]
Sergio answered the email, and I forwarded it to you, so you could take a look at the technical details.

- Sensors can be purchased separately: please see the prices though this link.
- However it is necessary to connect the sensors to MySignals Hub in order to forward the information to the Cloud: all the data gathered by MySignals is encrypted and sent to the user's private account at Libelium Cloud through WiFi or Bluetooth. The data can be displayed on a tablet or smartphone with Android or iPhone apps.
- Libelium offers two different API's for developers to access the information:
The Android / iOS API allows to get information directly from MySignals using Bluetooth. 
Android: Java
Apple: Objetive-C or Swift
- The API Cloud allows to access to the user's private account and get the information previously stored, to be displayed on a third party platform.
You can export data with php in JSON format.

In this link http://www.libelium.com/downloads/documentation/mysignals_technical_guide.pdf#page=223 
you have the technical documentation about how to use both methods.

**Comment by MatthewVita** [comment]
I see. Can you ask him if the old hub can be used instead? Perhaps mentioned our OpenEMR user base may provide a steady stream of revenue for them because they are looking for low-cost devices such as these and cannot afford the more expensive components such as the hub

**Comment by andremillet** [comment]
Done. Waiting for an answer.


*André Millet*


2017-08-01 16:11 GMT-03:00 Matthew Vita <notifications@github.com>:

**Comment by andremillet** [comment]
received the following answer:
>I regret to say that sensors are not >compatible with the old version of >MySignals ("eHealth Platform").
>If you need further information, please >contact me.

**Comment by andremillet** [comment]
My suggestion is that we still try to acquire this first version somehow, for testing purposes only

**Comment by TheToolbox** [comment]
I may actually be somewhat helpful here! This is what I studied in undergrad. The difficulty with some of these solutions is the testing infrastructure behind them. Much of the cost of these devices comes from the certifications that they will work as expected. Cleaning and trimming the signals is easily as important as simply gathering them. The other issue that may be relevant is that certain hardware lends itself to signals acquisition. The raspberry pi, for example, doesn't have an ADC (to my last recollection), which would prevent us from simply jamming sensors into it, and necessitate the design of additional hardware (chip-based ADCs, noise filters, etc.) in order to get the signals in. With a goal of putting together a low-cost hardware offering, it would be great to get some industry thoughts, especially when it comes to regulatory requirements, since the FDA is super strict about these things, and I'm sure other nations' governing bodies are as well. I'll try to get in contact with my friend at GE, and hopefully she might be able to point us in a positive direction as well. This will definitely be a huge value-add for ERs in many nations, and it's exciting to see people working toward it!

**Comment by andremillet** [comment]
awesome, Jason! thx in advance!

**Comment by MatthewVita** [comment]
@TheToolbox sounds great! We need more resources for this project as it is ambitious.

As far as FDA strictness, we may not have as much to worry about in other countries. This is good because that means we can make use of more unorthodox solutions (for instance, the products Andre and I are looking at "are not medical devices" :) ) - since we don't have to provide any warranties with anything because we're open source, this may work for a lot of non-US users that are not as lucky when it comes to finances (medical devices, as you know are VERY expensive. One US-style EKG is the cost of all of these little bluetooth/rasppi solutions)

**Comment by MatthewVita** [comment]
I should be clear that this does NOT mean we don't care about quality or testing. I am willing to spend personal funds buying and testing these devices for us. We just can't guarantee anything. This is in line with our license:

>  THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY
APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT
HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY
OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM
IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF
ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

**Comment by MatthewVita** [comment]
I have a little story. So, up until recently, my wife's glucose monitor was not to be taken literally. If it said that she had a high or low glucose number, it was instructed that she actually take a reading with an FDA approved "finger prick" device. Recently, the company got FDA approval for the monitor to be taken literally (and it was always accurate for her anyways).

This may be an approach that can be documented (read: documented, not _advised_) should one of the bluetooth/rasppi solutions "act up". Heart rate of 999 may be suspect :)

**Comment by andremillet** [comment]
>although I think @andremillet and I have a heart rate of 999 with excitement looking up all of these devices!

It's over 9000! lol

**Comment by robertdown** [comment]
I think we're going to try to sponsor a challenge at an upcoming medical hackathon for a group of engineering, medical, and CS students work on creating an open source, low-cost medical device. The areas I'd like to see are a glucometer, a vital signs matching, and a portal EKG device. I'm still working on the details but do keep this in mind. I'm also trying to get my university and perhaps the hospital I work out to offer sponsorships.

**Comment by MatthewVita** [comment]
Okay sounds like a plan. We'll play it by ear

**Comment by TheToolbox** [comment]
I was able to talk a bit with the handful of engineers I know out in the field. The general consensus was that putting new hardware options together is not an easy task. Interestingly, security factored highly in their considerations, which is an issue I think we are more than capable of tackling without undue issues. The other concerns that they expressed, similar to what I had said, is that any devices would have to clear the bar of "are you better off with the device than without it". This may seem obvious, but actually knowing that this bar has been cleared is not always so apparent. While an EKG may look like a good pattern, verifying its usefulness is a very different matter. Pulse oximeters and auto bp cuffs present much easier targets due to their lower-bandwidth, higher error-margin natures, and I'd definitely recommend attacking them first. 

The other suggestion that was made was to find out what organizations like Doctors without Borders are using in the field. Perhaps those options are cheap already, and integrating with them or improving on them might be an easy win for us. 

As an aside w.r.t. liability/legality, my understanding is that not only would non-certified devices have to state no guarantees, but more explicitly would have to call themselves non-medical devices. It would be interesting to see a parallel openMedicalHardware project started up, since it would take a large effort to move in that direction. 

My final thoughts are that easier devices should be attempted first, and a solid common brain-piece should be selected and vetted before moving on to sophisticated diagnostic tools. I don't know if a PI can keep up with a 500(?)hz EKG signal, but if it is the right tool for this job, then perhaps an adc like the [ads1115](https://cdn-shop.adafruit.com/datasheets/ads1115.pdf) or something fancier like the [ads1263](http://www.ti.com/lit/ds/symlink/ads1263.pdf) would be appropriate. A large list of available options can be found [here](https://www.digikey.com/products/en/integrated-circuits-ics/data-acquisition-analog-to-digital-converters-adc/700). Sensors/Probes I suspect might be easier to come by, which is good, but they may be more expensive per unit. Hopefully some of these ramblings give insight.

**Comment by robertdown** [comment]
Suggest migrating this to the forums, it's better suited for these longer form conversations.

**Comment by andremillet** [comment]
>Suggest migrating this to the forums, it's better suited for these longer
form conversations.
I second that.


*André Millet*


2017-08-08 18:34 GMT-03:00 Robert Down <notifications@github.com>:
